import { contextBridge, ipcRenderer } from 'electron';
import type { AutonomyDesktopApi, AutonomyStatus, AvatarTestAction, DashboardStatus, DesktopApi, DesktopAvatarEvent, HostContext, HostDesktopApi, HostRequest, HostTrigger, OrchestratorEvent, LiveRuntimeDesktopApi, BroadcastDesktopApi, TikTokDesktopApi, Phase11ValidationApi, DecisionDesktopApi, RehearsalDesktopApi } from '../../../../packages/shared-types/src/index.js';

const api: DesktopApi & HostDesktopApi & AutonomyDesktopApi & LiveRuntimeDesktopApi & BroadcastDesktopApi & TikTokDesktopApi & Phase11ValidationApi & DecisionDesktopApi & RehearsalDesktopApi = {
  getStatus: () => ipcRenderer.invoke('status:get'), checkAI: () => ipcRenderer.invoke('ai:check'), getOllamaDiagnostics:()=>ipcRenderer.invoke('ai:diagnostic'),
  startSession: () => ipcRenderer.invoke('session:start'), stopSession: () => ipcRenderer.invoke('session:stop'),
  generateHost: (request: HostRequest) => ipcRenderer.invoke('host:generate', request),
  hostEvent: (trigger: 'HUMAN_ENTERED' | 'HUMAN_LEFT', context: HostContext) => ipcRenderer.invoke('host:event', { trigger, context }),
  setAutonomy: (enabled: boolean) => ipcRenderer.invoke('autonomy:set', { enabled }),
  listProducts: () => ipcRenderer.invoke('products:list'), saveProduct: (product: unknown) => ipcRenderer.invoke('products:save', product),
  selectProduct: (request: { context: HostContext; conversation: string; audienceIntent?: string }) => ipcRenderer.invoke('products:select', request),
  submitAudienceEvent: (event: unknown) => ipcRenderer.invoke('audience:submit', event),
  getLocalProductionRehearsal:()=>ipcRenderer.invoke('local-production-rehearsal:status'),
  setLocalProductionRehearsal:(enabled:boolean)=>ipcRenderer.invoke('local-production-rehearsal:set',{enabled}),
  listAudienceLearning: () => ipcRenderer.invoke('audience:learning:list'), labelAudienceLearning: (id: string, label: 'PENDING' | 'GOOD' | 'BAD' | 'NEEDS_REVIEW') => ipcRenderer.invoke('audience:learning:label', { id, label }),
  listPersonalities: () => ipcRenderer.invoke('personality:list'), setPersonality: (id: string) => ipcRenderer.invoke('personality:set', { id }),
  scanMusicLibrary: () => ipcRenderer.invoke('music:scan'), listMusicTracks: () => ipcRenderer.invoke('music:list'),
  requestMusic: (trackId: string) => ipcRenderer.invoke('music:request', { trackId }), musicPlaybackCompleted: (trackId: string) => ipcRenderer.invoke('music:playback:completed', { trackId }), getMusicStatus: () => ipcRenderer.invoke('music:status'),
  speak: (request) => ipcRenderer.invoke('voice:speak', request), testVoice: () => ipcRenderer.invoke('voice:test'),
  voicePause: () => ipcRenderer.invoke('voice:pause'), voiceResume: () => ipcRenderer.invoke('voice:resume'), voiceStop: () => ipcRenderer.invoke('voice:stop'),
  voiceCancel: (requestId) => ipcRenderer.invoke('voice:cancel', { requestId }), voicePlaybackStarted: (requestId) => ipcRenderer.invoke('voice:playback:started', { requestId }),
  voicePlaybackCompleted: (requestId, success) => ipcRenderer.invoke('voice:playback:completed', { requestId, success }),
  getVoiceStatus: () => ipcRenderer.invoke('voice:status'), getAudioState: () => ipcRenderer.invoke('audio:state'), getAudioDevices: () => ipcRenderer.invoke('audio:devices'),reportAudioDevices:(devices)=>ipcRenderer.invoke('audio:devices:report',devices),getCurrentAudioDevice:()=>ipcRenderer.invoke('audio:current'),
  setAudioDevice: (deviceId) => ipcRenderer.invoke('audio:device:set', { deviceId }),ackAudioDevice:(requestId,success)=>ipcRenderer.send('audio:device:result',{requestId,success}),stopAllAudio:()=>ipcRenderer.invoke('audio:stop:all'),setMasterVolume: (value) => ipcRenderer.invoke('audio:volume:master', { value }),
  setVoiceVolume: (value) => ipcRenderer.invoke('audio:volume:voice', { value }), setMusicVolume: (value) => ipcRenderer.invoke('audio:volume:music', { value }),
  setAudioMuted: (muted) => ipcRenderer.invoke('audio:mute', { muted }), emergencyAudioStop: () => ipcRenderer.invoke('audio:emergency:stop'),
  resetAudioEmergency: () => ipcRenderer.invoke('audio:emergency:reset'), resolveAudioAsset: (kind, id) => ipcRenderer.invoke('audio:asset', { kind, id }),
  controlMusic: (action, trackId) => ipcRenderer.invoke('music:control', { action, ...(trackId ? { trackId } : {}) }),
  getAvatarState:()=>ipcRenderer.invoke('avatar:state:get'),connectAvatar:()=>ipcRenderer.invoke('avatar:connect'),disconnectAvatar:()=>ipcRenderer.invoke('avatar:disconnect'),testAvatar:(action:AvatarTestAction)=>ipcRenderer.invoke('avatar:test',action),avatarHostResponse:(response,trigger)=>ipcRenderer.invoke('avatar:host-response',{response,trigger}),avatarSpeechFailed:()=>ipcRenderer.invoke('avatar:speech:failed'),setAvatarHumanTakeover:(active)=>ipcRenderer.invoke('avatar:human-takeover',{active}),resetAvatar:()=>ipcRenderer.invoke('avatar:reset'),emergencyAvatarStop:()=>ipcRenderer.invoke('avatar:emergency:stop'),
  onAvatarEvent(callback:(event:DesktopAvatarEvent)=>void){const listener=(_e:Electron.IpcRendererEvent,event:DesktopAvatarEvent)=>callback(event);ipcRenderer.on('avatar:event',listener);return()=>ipcRenderer.removeListener('avatar:event',listener)},
  getAutonomyStatus: () => ipcRenderer.invoke('autonomy:status'), controlAutonomy: (action: 'pause' | 'resume' | 'stop') => ipcRenderer.invoke('autonomy:control', { action }),
  getLiveRuntime: () => ipcRenderer.invoke('live-runtime:status'), controlLiveRuntime: (action) => ipcRenderer.invoke('live-runtime:control', { action }),
  getBroadcastStatus: () => ipcRenderer.invoke('broadcast:status'), controlBroadcast: (action) => ipcRenderer.invoke('broadcast:control', { action }),
  getTikTokStatus:()=>ipcRenderer.invoke('tiktok:status'),beginTikTokAuthorization:()=>ipcRenderer.invoke('tiktok:connect'),cancelTikTokAuthorization:()=>ipcRenderer.invoke('tiktok:cancel'),disconnectTikTok:()=>ipcRenderer.invoke('tiktok:disconnect'),refreshTikTokConnection:()=>ipcRenderer.invoke('tiktok:refresh'),getTikTokCapabilities:()=>ipcRenderer.invoke('tiktok:capabilities'),syncTikTokProducts:()=>ipcRenderer.invoke('tiktok:sync-products'),getTikTokAccount:()=>ipcRenderer.invoke('tiktok:account'),
  getPhase11Validation:()=>ipcRenderer.invoke('validation:status'),startPhase11Validation:()=>ipcRenderer.invoke('validation:session:start'),completePhase11Validation:()=>ipcRenderer.invoke('validation:session:complete'),runPhase11AutomatedChecks:()=>ipcRenderer.invoke('validation:run-automated'),recordPhase11Human:(input)=>ipcRenderer.invoke('validation:record-human',input),recordPhase11Software:(input)=>ipcRenderer.invoke('validation:record-software',input),
  getDecisionStatus:()=>ipcRenderer.invoke('decision:status'),setDecisionIntelligenceEnabled:(enabled)=>ipcRenderer.invoke('decision:set-enabled',{enabled}),
  getRehearsalStatus:()=>ipcRenderer.invoke('rehearsal:status'),startRehearsal:(scenarioId,mode)=>ipcRenderer.invoke('rehearsal:start',{scenarioId,mode}),runAllRehearsals:(mode)=>ipcRenderer.invoke('rehearsal:run-all',{mode}),stopRehearsal:()=>ipcRenderer.invoke('rehearsal:stop'),resetRehearsal:()=>ipcRenderer.invoke('rehearsal:reset'),clearRehearsalReport:()=>ipcRenderer.invoke('rehearsal:clear-report'),
  onRehearsalUpdate(callback){const listener=(_e:Electron.IpcRendererEvent,snapshot:import('../../../../packages/live-rehearsal/src/index.js').RehearsalSnapshot)=>callback(snapshot);ipcRenderer.on('rehearsal:changed',listener);return()=>ipcRenderer.removeListener('rehearsal:changed',listener)},
  onLiveRuntimeEvent(callback) { const listener=(_e:Electron.IpcRendererEvent,event:import('../../../../packages/live-runtime/src/index.js').RuntimeEvent)=>callback(event);ipcRenderer.on('live-runtime:event',listener);return()=>ipcRenderer.removeListener('live-runtime:event',listener); },
  onOrchestratorEvent(callback: (event: OrchestratorEvent) => void) { const listener = (_e: Electron.IpcRendererEvent, event: OrchestratorEvent) => callback(event); ipcRenderer.on('orchestrator:event', listener); return () => ipcRenderer.removeListener('orchestrator:event', listener); },
  onStatus(callback: (status: DashboardStatus) => void) { const listener = (_e: Electron.IpcRendererEvent, status: DashboardStatus) => callback(status); ipcRenderer.on('status:changed', listener); return () => ipcRenderer.removeListener('status:changed', listener); },
  onAudioEvent(callback) { const listener = (_e: Electron.IpcRendererEvent, event: import('../../../../packages/shared-types/src/index.js').DesktopAudioEvent) => callback(event); ipcRenderer.on('audio:event', listener); return () => ipcRenderer.removeListener('audio:event', listener); },
};
contextBridge.exposeInMainWorld('desktop', api);
