import {randomUUID} from 'node:crypto';
import type {TikTokConnectorConfig,TikTokConnectorStatus,TikTokConnectionState,CredentialStore,StoredTikTokCredentials,TikTokAccount,TikTokErrorCode,TikTokCapabilityKey,TikTokAuthorizationCallback} from './types.js';
import {isTikTokConfigured} from './config.js';
import {AuthorizationStateManager} from './oauth/authorization-state.js';
import {buildAuthorizationUrl} from './oauth/oauth-client.js';
import {LoopbackCallbackServer} from './oauth/callback-handler.js';
import {TikTokApiClient} from './api/tiktok-api-client.js';
import {TikTokApiError,apiError} from './api/api-error.js';
import {PermissionManager} from './auth/permission-manager.js';
import {toTikTokAccount} from './auth/account-manager.js';
import type {UserProfile} from './types.js';
export interface TikTokConnectorDependencies {store:CredentialStore;openExternal:(url:string)=>Promise<void>;fetch?:typeof fetch;now?:()=>number;callbackFactory?:(port:number)=>LoopbackCallbackServer;onState?:(state:TikTokConnectionState)=>void;setTimer?:(fn:()=>void,ms:number)=>ReturnType<typeof setTimeout>;clearTimer?:(timer:ReturnType<typeof setTimeout>)=>void}
export class TikTokConnector {
 private readonly now:()=>number;private readonly states:AuthorizationStateManager;private readonly api:TikTokApiClient|null;private readonly callbackFactory:(port:number)=>LoopbackCallbackServer;private readonly setTimer:(fn:()=>void,ms:number)=>ReturnType<typeof setTimeout>;private readonly clearTimer:(timer:ReturnType<typeof setTimeout>)=>void;private state:TikTokConnectionState='DISCONNECTED';private permissions:PermissionManager;private credentials:StoredTikTokCredentials|null=null;private profile:UserProfile|null=null;private callback:LoopbackCallbackServer|null=null;private authTask:Promise<void>|null=null;private authGeneration=0;private credentialGeneration=0;private refreshInFlight:Promise<StoredTikTokCredentials>|null=null;private timer:ReturnType<typeof setTimeout>|null=null;private account:TikTokAccount|null=null;private lastValidatedAt:number|null=null;private errorCount=0;private lastErrorCode:TikTokErrorCode|null=null;private lastSyncAt:number|null=null;private lastSuccessAt:number|null=null;private lastFailureAt:number|null=null;private itemsSynced=0;private itemsSkipped=0;
 constructor(private readonly config:TikTokConnectorConfig,private readonly deps:TikTokConnectorDependencies){this.now=deps.now??Date.now;this.states=new AuthorizationStateManager(this.now);this.permissions=new PermissionManager(config.scopes);this.callbackFactory=deps.callbackFactory??(port=>new LoopbackCallbackServer(port));this.setTimer=deps.setTimer??setTimeout;this.clearTimer=deps.clearTimer??clearTimeout;this.api=isTikTokConfigured(config)?new TikTokApiClient({clientKey:config.clientKey!,clientSecret:config.clientSecret!,redirectUri:config.redirectUri!,requestTimeoutMs:config.requestTimeoutMs},deps.fetch??fetch):null}
 async initialize(){if(!this.deps.store.isAvailable())return this.status();this.credentials=await this.deps.store.read();if(this.credentials){this.permissions.setGranted(this.credentials.grantedScopes);this.account=this.makeAccount(this.credentials);this.state=this.permissions.hasScope('user.info.basic')?'CONNECTED':'PERMISSION_LIMITED';this.notify();this.scheduleRefresh()}return this.status()}
 async beginAuthorization(){if(this.state==='AUTHORIZING'||this.state==='DISCONNECTING')return this.status();if(!this.api||!this.config.redirectUri||!this.config.clientKey){this.setError('INVALID_REQUEST');return this.status()}if(!this.deps.store.isAvailable()){this.setError('FORBIDDEN');return this.status()}const redirect=new URL(this.config.redirectUri);const port=Number(redirect.port);if(!Number.isInteger(port)||port<1||port>65535){this.setError('INVALID_REQUEST');return this.status()}this.state='AUTHORIZING';this.lastErrorCode=null;this.notify();const generation=++this.authGeneration;this.authTask=this.runAuthorization(generation);return this.status()}
 async cancelAuthorization(){if(this.state!=='AUTHORIZING')return this.status();this.authGeneration++;this.states.clear();await this.callback?.shutdown();this.callback=null;this.state=this.credentials?'CONNECTED':'DISCONNECTED';this.lastErrorCode=null;this.notify();return this.status()}
 async disconnect(){if(this.state==='DISCONNECTING')return this.status();this.state='DISCONNECTING';this.notify();this.authGeneration++;this.credentialGeneration++;this.stopRefreshTimer();this.states.clear();await this.callback?.shutdown();this.callback=null;this.authTask=null;this.refreshInFlight=null;this.credentials=null;this.profile=null;this.account=null;this.permissions=new PermissionManager(this.config.scopes);await this.deps.store.clear();this.state='DISCONNECTED';this.lastErrorCode=null;this.notify();return this.status()}
 async refreshConnection(){if(!this.credentials||!this.api){this.setError('UNAUTHORIZED');return this.status()}const generation=this.credentialGeneration;try{this.state='REFRESHING';this.notify();const current=await this.getValidCredentials(false);if(generation!==this.credentialGeneration)return this.status();if(this.permissions.hasScope('user.info.basic')){this.profile=await this.api.getUserProfile(current.accessToken);if(generation!==this.credentialGeneration)return this.status();if(this.profile.open_id!==current.openId)throw apiError('INVALID_RESPONSE','user-info-identity')}this.account=this.makeAccount(current);this.lastValidatedAt=this.now();this.state=this.permissions.hasScope('user.info.basic')?'CONNECTED':'PERMISSION_LIMITED';this.lastErrorCode=null;this.scheduleRefresh()}catch(error){this.capture(error);if(error instanceof TikTokApiError&&['UNAUTHORIZED','FORBIDDEN','TOKEN_REFRESH_FAILED'].includes(error.detail.code)){this.state='REAUTH_REQUIRED';this.permissions.setReauthRequired()}else this.state=this.credentials?'ERROR':'DISCONNECTED'}this.notify();return this.status()}
 async syncProducts(){this.lastSyncAt=this.now();this.itemsSynced=0;this.itemsSkipped=0;this.lastErrorCode='NOT_SUPPORTED';this.notify();return{status:'NOT_VERIFIED' as const,message:'Showcase/LIVE product APIs are not verified or approved for this app; local Product Engine data was not changed.'}}
 async getAccount(){return this.account?structuredClone(this.account):null}
 getCapabilities(){const profileOk=Boolean(this.profile&&this.permissions.hasScope('user.info.basic'));return{TIKTOK_LOGIN:{status:this.account?'AVAILABLE':'UNKNOWN',reason:this.account?'Account authorization and identity validated':'Login Kit app approval/configuration has not been confirmed'},BASIC_PROFILE:{status:profileOk?'AVAILABLE':this.account?'NOT_AUTHORIZED':'UNKNOWN',reason:profileOk?'user.info.basic granted and profile validated':this.account?'Required scope/profile is unavailable':'Not verified until authorization'},DISPLAY_API:{status:this.profile?'AVAILABLE':'UNKNOWN',reason:this.profile?'Official /v2/user/info response validated':'No successful official Display API response'},CREATOR_AUTHORIZATION:{status:'NOT_VERIFIED',reason:'No creator authorization API for this app is configured or verified'},SHOWCASE_PRODUCTS:{status:'NOT_VERIFIED',reason:'Login Kit/Display API do not provide verified showcase access'},LIVE_PRODUCT_ACCESS:{status:'NOT_VERIFIED',reason:'No approved TikTok LIVE product API is configured or verified'},AFFILIATE_PRODUCT_ACCESS:{status:'NOT_VERIFIED',reason:'No approved affiliate product API is configured or verified'}} satisfies Record<TikTokCapabilityKey,{status:string;reason:string}>}
 status():TikTokConnectorStatus{const granted=this.permissions.getGrantedScopes();const missing=this.permissions.getMissingScopes();const secure=this.deps.store.isAvailable();const connected=Boolean(this.account);const capabilities=this.getCapabilities();return{state:this.state,configured:Boolean(this.api&&this.config.redirectUri),secureStorageAvailable:secure,account:this.account?structuredClone(this.account):null,requestedScopes:[...this.config.scopes],grantedScopes:granted,missingScopes:missing,permissionState:this.permissions.getState(),capabilities,syncStatus:!this.api?'NOT_CONFIGURED':connected||this.lastSyncAt!==null?'NOT_VERIFIED':'NOT_CONFIGURED',lastSyncAt:this.lastSyncAt,lastSuccessAt:this.lastSuccessAt,lastFailureAt:this.lastFailureAt,itemsSynced:this.itemsSynced,itemsSkipped:this.itemsSkipped,errorCount:this.errorCount,lastErrorCode:this.lastErrorCode,qrAuthorization:'QR_AUTH_UNAVAILABLE'} as TikTokConnectorStatus}
 async shutdown(){this.stopRefreshTimer();this.authGeneration++;this.states.clear();await this.callback?.shutdown();this.callback=null}
 private async runAuthorization(generation:number){try{const pending=this.states.create(this.config.redirectUri!,this.config.scopes);const port=Number(new URL(this.config.redirectUri!).port);this.callback=this.callbackFactory(port);await this.callback.start(this.config.authorizationTimeoutMs);if(generation!==this.authGeneration){await this.callback.shutdown();return}const url=buildAuthorizationUrl({clientKey:this.config.clientKey!,redirectUri:this.config.redirectUri!,scopes:pending.requestedScopes,state:pending.state,codeChallenge:pending.challenge});await this.deps.openExternal(url);if(generation!==this.authGeneration){await this.callback.shutdown();return}const cb=await this.callback.wait();if(generation!==this.authGeneration)return;if(cb.error==='timeout')throw apiError('TIMEOUT','oauth-callback');if(cb.error==='cancelled')throw apiError('USER_CANCELLED','oauth-callback');await this.finishAuthorization(cb,pending.verifier,generation)}catch(error){if(generation===this.authGeneration){this.setError(error instanceof Error&&error.message==='STATE_MISMATCH'?'STATE_MISMATCH':error instanceof TikTokApiError?error.detail.code:'UNKNOWN')}await this.cleanupAuthorization()}finally{if(generation===this.authGeneration)this.authTask=null}}
 private async finishAuthorization(callback:TikTokAuthorizationCallback,verifier:string,generation:number){this.states.consume(callback.state);if(callback.error){if(callback.error==='access_denied')throw apiError('USER_CANCELLED','oauth-callback');throw apiError('FORBIDDEN','oauth-callback')}if(!callback.code||callback.code.length>2048)throw apiError('INVALID_RESPONSE','oauth-callback');const token=await this.api!.exchangeCode(callback.code,verifier);const granted=token.scope.split(',').map(s=>s.trim()).filter(Boolean);const stored:StoredTikTokCredentials={connectionId:randomUUID(),accessToken:token.access_token,refreshToken:token.refresh_token,accessExpiresAt:this.now()+token.expires_in*1000,refreshExpiresAt:this.now()+token.refresh_expires_in*1000,openId:token.open_id,grantedScopes:granted,connectedAt:this.now(),displayName:null,avatarUrl:null};if(generation!==this.authGeneration)return;await this.deps.store.write(stored);if(generation!==this.authGeneration){if(!this.credentials)await this.deps.store.clear();return}this.credentials=stored;this.permissions.setGranted(granted);if(this.permissions.hasScope('user.info.basic')){try{this.profile=await this.api!.getUserProfile(stored.accessToken);if(generation!==this.authGeneration){this.profile=null;if(!this.credentials)await this.deps.store.clear();return}if(this.profile.open_id!==stored.openId)throw apiError('INVALID_RESPONSE','user-info-identity');stored.displayName=this.profile.display_name??null;stored.avatarUrl=this.profile.avatar_url??null;await this.deps.store.write(stored);if(generation!==this.authGeneration){this.profile=null;if(!this.credentials)await this.deps.store.clear();return}}catch(error){if(error instanceof TikTokApiError&&['FORBIDDEN','UNAUTHORIZED'].includes(error.detail.code)){this.profile=null}else throw error}}this.credentials=stored;this.permissions.setGranted(granted);this.account=this.makeAccount(stored);this.lastValidatedAt=this.now();this.lastSuccessAt=this.now();this.lastErrorCode=null;this.state=this.profile?'CONNECTED':'PERMISSION_LIMITED';this.scheduleRefresh();this.notify()}
 private async getValidCredentials(force=false):Promise<StoredTikTokCredentials>{if(this.refreshInFlight)return this.refreshInFlight;if(!this.credentials||!this.api)throw apiError('UNAUTHORIZED','token-manager');const current=this.credentials;const credentialGeneration=this.credentialGeneration;if(!force&&current.accessExpiresAt-this.now()>300_000)return current;if(current.refreshExpiresAt<=this.now())throw apiError('TOKEN_REFRESH_FAILED','token-manager');this.refreshInFlight=(async()=>{const refreshed=await this.api!.refresh(current.refreshToken);if(refreshed.open_id!==current.openId)throw apiError('INVALID_RESPONSE','token-refresh-identity');const scopes=refreshed.scope.split(',').map(s=>s.trim()).filter(Boolean);const next:StoredTikTokCredentials={...current,accessToken:refreshed.access_token,refreshToken:refreshed.refresh_token,accessExpiresAt:this.now()+refreshed.expires_in*1000,refreshExpiresAt:this.now()+refreshed.refresh_expires_in*1000,grantedScopes:scopes};if(credentialGeneration!==this.credentialGeneration)throw apiError('USER_CANCELLED','token-refresh');await this.deps.store.write(next);if(credentialGeneration!==this.credentialGeneration){if(!this.credentials)await this.deps.store.clear();throw apiError('USER_CANCELLED','token-refresh')}this.credentials=next;this.permissions.setGranted(scopes);this.account=this.makeAccount(next);this.lastSuccessAt=this.now();this.lastErrorCode=null;this.scheduleRefresh();return next})();try{return await this.refreshInFlight}catch(error){this.capture(error);if(error instanceof TikTokApiError&&['UNAUTHORIZED','FORBIDDEN','INVALID_REQUEST'].includes(error.detail.code)){this.state='REAUTH_REQUIRED';this.permissions.setReauthRequired()}throw error}finally{this.refreshInFlight=null}}
 private scheduleRefresh(){this.stopRefreshTimer();if(!this.credentials)return;const delay=Math.max(1000,this.credentials.accessExpiresAt-this.now()-300_000);this.timer=this.setTimer(()=>{const generation=this.credentialGeneration;void this.getValidCredentials(true).then(()=>{if(generation!==this.credentialGeneration)return;if(this.state==='REFRESHING')this.state='CONNECTED';this.notify()}).catch(error=>{if(generation!==this.credentialGeneration)return;if(error instanceof TikTokApiError&&error.detail.code==='USER_CANCELLED')return;if(error instanceof TikTokApiError&&['UNAUTHORIZED','FORBIDDEN','INVALID_REQUEST'].includes(error.detail.code)){this.state='REAUTH_REQUIRED';this.permissions.setReauthRequired()}else this.state='ERROR';this.capture(error);this.notify()})},Math.min(delay,2_147_000_000));this.timer.unref?.()}
 private stopRefreshTimer(){if(this.timer){this.clearTimer(this.timer);this.timer=null}}
 private makeAccount(c:StoredTikTokCredentials){return toTikTokAccount({connectionId:c.connectionId,openId:c.openId,displayName:c.displayName,avatarUrl:c.avatarUrl,scopes:c.grantedScopes,connectedAt:c.connectedAt,lastValidatedAt:this.lastValidatedAt??c.connectedAt})}
 private async cleanupAuthorization(){this.states.clear();await this.callback?.close();this.callback=null;if(this.state==='AUTHORIZING')this.state=this.credentials?'CONNECTED':'DISCONNECTED';this.notify()}
 private capture(error:unknown){this.errorCount++;this.lastFailureAt=this.now();this.lastErrorCode=error instanceof TikTokApiError?error.detail.code:'UNKNOWN'}private setError(code:TikTokErrorCode){this.errorCount++;this.lastFailureAt=this.now();this.lastErrorCode=code;this.state=code==='USER_CANCELLED'?'DISCONNECTED':'ERROR';this.notify()}private notify(){this.deps.onState?.(this.state)}
}

