import{describe,expect,it,vi}from'vitest';
import type{AIHealthStatus,AIRequest,AIResponse,HostContext}from'../packages/shared-types/src/index.js';
import{HostContextSchema,HostRequestSchema,HostResponseSchema}from'../packages/protocol/src/index.js';
import{HostEngine,HostEngineError,HostPromptBuilder,hostResponseToCommands,parseHostResponse,parseHostResponseWithDiagnostics}from'../packages/host-engine/src/index.js';
import{Logger}from'../packages/logging/src/index.js';

const baseContext:HostContext={sessionId:'test-session',recentConversation:[],humanHostPresent:false};
const rawResponse=JSON.stringify({speech:'Halo semuanya, aku host kalian!',emotion:'friendly',gesture:'wave',scene:'AVATAR',intent:'greeting'});
const health:AIHealthStatus={available:true,provider:'ollama',model:'test-model'};
function provider(answer=rawResponse,options:{health?:AIHealthStatus;error?:Error}={}){return{getName:()=> 'ollama',healthCheck:vi.fn(async()=>options.health??health),generate:vi.fn(async(_request:AIRequest):Promise<AIResponse>=>{if(options.error)throw options.error;return{text:answer,provider:'ollama',model:'test-model',latencyMs:15}})}}
const prompts=()=>new HostPromptBuilder(`${process.cwd()}/data/prompts/host-system.md`);

describe('Host schemas',()=>{
 it('accepts a complete and absent-human context',()=>{expect(HostContextSchema.safeParse(baseContext).success).toBe(true);expect(HostContextSchema.safeParse({...baseContext,humanHostPresent:false}).success).toBe(true)});
 it('accepts every manual Phase 1 and reserved trigger',()=>{for(const trigger of ['MANUAL','COMEDY','HUMAN_ENTERED','HUMAN_LEFT','COMMENT','PRODUCT_INTRO','PRODUCT_DEMO','PROMOTION','TOPIC_CHANGE','IDLE_FILLER'])expect(HostRequestSchema.safeParse({type:'HOST_RESPONSE',trigger,context:baseContext}).success).toBe(true)});
 it('rejects personality metadata outside the strict HostContext schema while accepting the projected public fields',()=>{const full={id:'friendly',name:'Ramah',style:'Warm',description:'private manager metadata'};expect(HostRequestSchema.safeParse({type:'HOST_RESPONSE',trigger:'MANUAL',context:{...baseContext,personality:full}}).success).toBe(false);const{id,name,style}=full;expect(HostRequestSchema.safeParse({type:'HOST_RESPONSE',trigger:'MANUAL',context:{...baseContext,personality:{id,name,style}}}).success).toBe(true)});
 it('rejects invalid human state and malformed requests',()=>{expect(HostContextSchema.safeParse({...baseContext,humanHostState:'dancing'}).success).toBe(false);expect(HostRequestSchema.safeParse({type:'SPEAK',trigger:'MANUAL',context:baseContext}).success).toBe(false)});
 it('accepts valid host responses and rejects invalid enums or missing speech',()=>{expect(HostResponseSchema.safeParse(JSON.parse(rawResponse)).success).toBe(true);for(const response of [{speech:'hi',emotion:'angry',gesture:'wave',intent:'greeting'},{speech:'hi',emotion:'friendly',gesture:'dance',intent:'greeting'},{speech:'hi',emotion:'friendly',gesture:'wave',intent:'buy_now'},{emotion:'friendly',gesture:'wave',intent:'greeting'}])expect(HostResponseSchema.safeParse(response).success).toBe(false)});
});

describe('AI parser and command mapping',()=>{
 it('parses JSON in a code fence and sanitizes markdown',()=>{const parsed=parseHostResponse('```json\n{"speech":"**Halo** [teman](https://example.test)!","emotion":"happy","gesture":"talking","intent":"general_chat"}\n```');expect(parsed.speech).toBe('Halo teman!')});
 it('safely extracts a JSON object surrounded by provider text',()=>{expect(parseHostResponse(`Result: ${rawResponse}`).speech).toContain('Halo semuanya')});
 it.each(['plain text','{broken json','{"speech":"hello","emotion":"angry","gesture":"wave","intent":"greeting"}','{"speech":"hello","emotion":"friendly","gesture":"wave","intent":"unknown"}','{"emotion":"friendly","gesture":"wave","intent":"greeting"}'])('returns INVALID_AI_RESPONSE for unsafe model output',raw=>{expect(()=>parseHostResponse(raw)).toThrowError(HostEngineError);try{parseHostResponse(raw)}catch(e){expect((e as HostEngineError).code).toBe('INVALID_AI_RESPONSE')}});
 it('keeps the gesture enum strict while mapping a gesture-only model error to a safe allowed gesture',()=>{const raw='{"speech":"Halo, selamat datang.","emotion":"friendly","gesture":"dance","intent":"greeting"}';expect(HostResponseSchema.safeParse(JSON.parse(raw)).success).toBe(false);expect(parseHostResponseWithDiagnostics(raw)).toEqual({response:{speech:'Halo, selamat datang.',emotion:'friendly',gesture:'talking',intent:'greeting'},normalizations:['INVALID_GESTURE_DEFAULTED_TO_TALKING']});expect(()=>parseHostResponse(raw.replace('"emotion":"friendly"','"emotion":"angry"'))).toThrowError(HostEngineError)});
 it('maps speech, emotion, gesture and optional scene into validated commands',()=>{expect(hostResponseToCommands(parseHostResponse(rawResponse))).toEqual([{type:'SPEAK',text:'Halo semuanya, aku host kalian!',priority:'normal'},{type:'SET_EMOTION',emotion:'friendly'},{type:'SET_GESTURE',gesture:'wave'},{type:'SET_SCENE',sceneId:'AVATAR'}]);const noScene=parseHostResponse(JSON.stringify({speech:'Hai.',emotion:'neutral',gesture:'idle',intent:'general_chat'}));expect(hostResponseToCommands(noScene)).toHaveLength(3)});
});

describe('Host prompt and engine',()=>{
 it('loads editable personality and includes trigger and human context',async()=>{const builder=prompts();const prompt=await builder.build({type:'HOST_RESPONSE',trigger:'COMEDY',context:{...baseContext,humanHostPresent:true,humanHostState:'coding'}});expect(prompt.systemPrompt).toContain('natural Indonesian');expect(prompt.userPrompt).toContain('COMEDY');expect(prompt.userPrompt).toContain('"humanHostState":"coding"');expect(prompt.userPrompt).toContain('"humanHostPresent":true')});
 it('builds absent-human context without inventing a co-host',async()=>{const prompt=await prompts().build({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext});expect(prompt.userPrompt).toContain('"humanHostPresent":false')});
 it('generates a validated response and logs request, latency, and commands',async()=>{const ai=provider(),sink=vi.fn(),engine=new HostEngine(ai,prompts(),new Logger(sink));const result=await engine.generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext,instruction:'Introduce yourself'});expect(result.ok).toBe(true);if(result.ok){expect(result.response.speech).toContain('Halo');expect(result.commands).toHaveLength(4);expect(result.latencyMs).toBe(15)}expect(ai.generate).toHaveBeenCalledOnce();expect(sink.mock.calls.map(c=>c[0].event)).toEqual(['request','response_validated'])});
 it('records safe gesture normalization and returns only an enum-validated command',async()=>{const ai=provider('{"speech":"Halo semuanya.","emotion":"friendly","gesture":"dance","intent":"greeting"}'),sink=vi.fn(),engine=new HostEngine(ai,prompts(),new Logger(sink));const result=await engine.generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext});expect(result).toMatchObject({ok:true,response:{gesture:'talking'}});if(result.ok)expect(result.commands).toContainEqual({type:'SET_GESTURE',gesture:'talking'});expect(sink.mock.calls[1]?.[0].payload.normalizations).toEqual(['INVALID_GESTURE_DEFAULTED_TO_TALKING'])});
 it('passes coding and holding-product context into AI prompt',async()=>{for(const state of ['coding','holding_product'] as const){const ai=provider(),engine=new HostEngine(ai,prompts());const result=await engine.generate({type:'HOST_RESPONSE',trigger:'COMEDY',context:{...baseContext,humanHostPresent:true,humanHostState:state}});expect(result.ok).toBe(true);expect(ai.generate.mock.calls[0]?.[0].userPrompt).toContain(`"humanHostState":"${state}"`)}});
 it('supports a human-absent request',async()=>{const result=await new HostEngine(provider(),prompts()).generate({type:'HOST_RESPONSE',trigger:'COMEDY',context:baseContext});expect(result.ok).toBe(true)});
 it('rejects product speech that fails factual policy before mapping executable commands',async()=>{const product={id:'P007',name:'Mug',price:120,currency:'IDR',description:'',category:'drinkware',promoPrice:undefined,benefits:[],specifications:[],variants:[],stock:8,sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[]};const ai=provider(JSON.stringify({speech:'Harganya hanya 30 ribu.',emotion:'friendly',gesture:'present',intent:'product_intro'}));const engine=new HostEngine(ai,prompts(),new Logger(()=>undefined),undefined,undefined,()=>false);const result=await engine.generate({type:'HOST_RESPONSE',trigger:'PRODUCT_INTRO',context:{...baseContext,currentProduct:product}});expect(result).toMatchObject({ok:false,code:'INVALID_AI_RESPONSE'});});
 it('returns AI_OFFLINE without generating when provider is unavailable',async()=>{const ai=provider(rawResponse,{health:{available:false,provider:'ollama'}}),result=await new HostEngine(ai,prompts()).generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext});expect(result).toMatchObject({ok:false,code:'AI_OFFLINE'});expect(ai.generate).not.toHaveBeenCalled()});
 it('returns MODEL_NOT_FOUND when no configured model is available',async()=>{const result=await new HostEngine(provider(rawResponse,{health:{available:true,provider:'ollama'}}),prompts()).generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext});expect(result).toMatchObject({ok:false,code:'MODEL_NOT_FOUND'})});
 it('classifies timeout and malformed AI output as safe failures',async()=>{const timed=await new HostEngine(provider(rawResponse,{error:new Error('request timed out')}),prompts()).generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext});expect(timed).toMatchObject({ok:false,code:'AI_TIMEOUT'});const invalid=await new HostEngine(provider('not JSON'),prompts()).generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext});expect(invalid).toMatchObject({ok:false,code:'INVALID_AI_RESPONSE'})});
 it('gates human enter/leave triggers on autonomy and applies cooldown',async()=>{let now=1000;const ai=provider(),engine=new HostEngine(ai,prompts(),new Logger(()=>undefined),()=>now,5000);expect(await engine.handleHumanEvent('HUMAN_ENTERED',{...baseContext,humanHostPresent:true})).toMatchObject({ok:false,code:'AUTONOMY_OFF'});engine.setAutonomy(true);expect((await engine.handleHumanEvent('HUMAN_ENTERED',{...baseContext,humanHostPresent:true})).ok).toBe(true);expect(await engine.handleHumanEvent('HUMAN_LEFT',baseContext)).toMatchObject({ok:false,code:'COOLDOWN'});now+=5001;expect((await engine.handleHumanEvent('HUMAN_LEFT',baseContext)).ok).toBe(true)});
 it('allows manual generation with autonomy both OFF and ON',async()=>{const engine=new HostEngine(provider(),prompts());expect(engine.isAutonomyEnabled()).toBe(false);expect((await engine.generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext})).ok).toBe(true);engine.setAutonomy(true);expect(engine.isAutonomyEnabled()).toBe(true);expect((await engine.generate({type:'HOST_RESPONSE',trigger:'MANUAL',context:baseContext})).ok).toBe(true)});
});
