import {afterEach,describe,expect,it,vi} from 'vitest';
import type {HostContext,HostGenerationResult,HostRequest,OrchestratorEvent,AutonomousAction} from '../packages/shared-types/src/index.js';
import {AutonomousOrchestrator,DecisionEngine,type LiveSessionState,type Scheduler,type ShowRuntimePort} from '../packages/orchestrator/src/index.js';
import {ProductCatalog,ProductContextBuilder,ProductSchema,ProductSelector,SQLiteProductRepository,SalesStrategyEngine} from '../packages/product-engine/src/index.js';
import {DatabaseSync} from 'node:sqlite';
import {initializeDatabase} from '../apps/desktop/src/main/database.js';
import {DecisionIntelligence,OutputJudge,type DecisionProvider,type DecisionRequest,type DecisionResult} from '../packages/decision-intelligence/src/index.js';

class FakeScheduler implements Scheduler { private n=0; readonly jobs=new Map<number,{callback:()=>void;delay:number}>();schedule(callback:()=>void,delay:number){const id=++this.n;this.jobs.set(id,{callback,delay});return id;}cancel(id:unknown){this.jobs.delete(id as number);}runNext(){const [id,job]=this.jobs.entries().next().value??[];if(job){this.jobs.delete(id as number);job.callback();}return job?.delay??null;} }
const fixture=(values:Record<string,unknown>={})=>ProductSchema.parse({id:'A',name:'Product A',category:'home',price:250,currency:'IDR',promoPrice:null,description:'',benefits:['Easy to store'],specifications:['Small size'],variants:[],stock:4,images:[],status:'ACTIVE',sellingPoints:['Compact'],targetAudience:[],preferredTalkingPoints:['Compact item'],forbiddenClaims:[],priority:50,...values});
const successful:HostGenerationResult={ok:true,response:{speech:'Halo, mari kita mulai.',emotion:'friendly',gesture:'talking',intent:'general_chat'},commands:[{type:'SPEAK',text:'Halo, mari kita mulai.',priority:'normal'}],provider:'test',model:'test',latencyMs:1};
let db:DatabaseSync|undefined;
const harness=(items=[fixture()],options:{now?:()=>number;cooldowns?:Partial<{tickMs:number;globalSpeechMs:number;productIntroMs:number;repeatedProductMs:number;backoffMs:number;backoffMaxMs:number}>;answer?:HostGenerationResult;answerFor?:(request:HostRequest)=>HostGenerationResult;catalog?:ProductCatalog;audienceTask?:{text:string;intent:string};decisionProvider?:DecisionProvider;showRuntime?:ShowRuntimePort}={})=>{
 db=initializeDatabase(':memory:');const catalog=options.catalog??new ProductCatalog(new SQLiteProductRepository(db));for(const p of items)catalog.save(p);const scheduler=new FakeScheduler();const events:OrchestratorEvent[]=[];const requests:HostRequest[]=[];const hostEngine={generate:vi.fn(async(request:HostRequest)=>{requests.push(request);return options.answerFor?.(request)??options.answer??successful;})};const base:HostContext={sessionId:'test',recentConversation:[],humanHostPresent:false};const tasks=options.audienceTask?[{event:{source:'simulator',type:'COMMENT',text:options.audienceTask.text,timestamp:100},intent:options.audienceTask.intent,mode:'FULL_RESPONSE',priority:80,enqueuedAt:100}]:[];const audienceQueue={next:()=>tasks.shift(),clear:()=>{tasks.length=0},size:tasks.length};const decisionProvider:DecisionProvider=options.decisionProvider??{id:'no-jev',isAvailable:async()=>false,decide:async(_request:DecisionRequest):Promise<DecisionResult>=>{throw new Error('not available')}};const orchestrator=new AutonomousOrchestrator({hostEngine,catalog,productSelector:new ProductSelector(catalog,0,options.now),context:()=>({recentConversation:base.recentConversation,humanHostPresent:base.humanHostPresent}),emit:event=>events.push(event),scheduler,...(options.now?{now:options.now}:{}),cooldowns:{tickMs:5,globalSpeechMs:0,productIntroMs:0,repeatedProductMs:0,backoffMs:20,backoffMaxMs:100,...options.cooldowns},salesStrategy:new SalesStrategyEngine(),productContextBuilder:new ProductContextBuilder(),audienceQueue,decisionIntelligence:new DecisionIntelligence({primary:decisionProvider}),outputJudge:new OutputJudge(),...(options.showRuntime?{showRuntime:options.showRuntime}:{})});return{orchestrator,catalog,scheduler,events,requests,hostEngine,tasks};
};
afterEach(()=>{db?.close();db=undefined;});

describe('Phase 3 AutonomousOrchestrator',()=>{
 it('starts a serializable live session and emits lifecycle events',()=>{let now=100;const h=harness([fixture()],{now:()=>now});const s=h.orchestrator.start(7);expect(s).toMatchObject({sessionId:7,running:true,paused:false,startedAt:100,productsDiscussed:[],audience:{kind:'UNKNOWN'}});expect(h.events.map(e=>e.type)).toEqual(['LIVE_STARTED','AUTONOMY_ENABLED']);});
 it('stops and cleans its scheduled timer',()=>{const h=harness();h.orchestrator.start(1);expect(h.scheduler.jobs.size).toBe(1);h.orchestrator.stop();expect(h.scheduler.jobs.size).toBe(0);expect(h.orchestrator.getState()?.running).toBe(false);});
 it('pauses without decisions and resumes with a delayed tick',async()=>{let now=100;const h=harness([fixture()],{now:()=>now,cooldowns:{globalSpeechMs:50}});h.orchestrator.start(1);await h.orchestrator.tick();h.orchestrator.pause();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledOnce();expect(h.orchestrator.getState()?.paused).toBe(true);h.orchestrator.resume();expect(h.scheduler.runNext()).toBeGreaterThanOrEqual(50);});
 it('produces an initial greeting decision and calls HostEngine',async()=>{const h=harness();h.orchestrator.start(2);await h.orchestrator.tick();expect(h.requests[0]?.trigger).toBe('MANUAL');expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='GREETING')).toBe(true);expect(h.orchestrator.getState()?.greeted).toBe(true);});
 it('OutputJudge gates autonomous greeting speech before HOST_RESPONSE_READY',async()=>{const h=harness([],{answer:{...successful,response:{...successful.response,speech:'Pesanan sudah berhasil dibeli.'}}});h.orchestrator.start(2);await h.orchestrator.tick();expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY')).toBe(false);expect(h.events.some(e=>e.type==='ORCHESTRATOR_ERROR'&&e.message.includes('validation'))).toBe(true);expect(h.orchestrator.getState()?.greeted).toBe(false);});
 it('OutputJudge gates Show Director speech and reports failed plan completion',async()=>{const showRuntime:ShowRuntimePort={advance:async()=>({kind:'HOST',plan:{token:'plan-1',action:'SHOW_TRANSITION',instruction:'Berikan transisi'}}),complete:vi.fn(),start:vi.fn(),pause:vi.fn(),resume:vi.fn(),stop:vi.fn(),nextWakeDelay:()=>null,speechStarted:vi.fn(),speechFinished:vi.fn()};const h=harness([],{answer:{...successful,response:{...successful.response,speech:'Pesanan sudah berhasil dibeli.'}},showRuntime});h.orchestrator.start(3);await h.orchestrator.tick();expect(showRuntime.complete).toHaveBeenCalledWith(expect.objectContaining({token:'plan-1'}),false);expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY')).toBe(false);expect(h.events.some(e=>e.type==='ORCHESTRATOR_ERROR'&&e.message.includes('validation'))).toBe(true);});
 it('does not decide or speak while paused',async()=>{const h=harness();h.orchestrator.start(1);h.orchestrator.pause();await h.orchestrator.tick();expect(h.hostEngine.generate).not.toHaveBeenCalled();});
 it('waits during global speech cooldown',async()=>{let now=0;const h=harness([fixture()],{now:()=>now,cooldowns:{globalSpeechMs:100}});h.orchestrator.start(1);await h.orchestrator.tick();now=50;await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledOnce();expect(h.orchestrator.getState()?.currentIntent).toBe('WAIT');});
 it('enforces product intro cooldown after finishing a product sequence',async()=>{let now=0;const h=harness([fixture()],{now:()=>now,cooldowns:{productIntroMs:500}});h.orchestrator.start(1);await h.orchestrator.tick();now+=1;await h.orchestrator.tick();now+=1;await h.orchestrator.tick();now+=1;await h.orchestrator.tick();now+=1;await h.orchestrator.tick();now+=1;await h.orchestrator.tick();expect(h.orchestrator.getState()?.currentProductId).toBe(null);const n=h.hostEngine.generate.mock.calls.length;now=100;await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledTimes(n);now=501;await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledTimes(n+1);});
 it('autonomously selects a verified product and supplies catalog context to HostEngine',async()=>{const h=harness([fixture()]);h.orchestrator.start(1);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.requests[1]?.trigger).toBe('PRODUCT_INTRO');expect(h.requests[1]?.context.currentProduct?.id).toBe('A');expect(h.orchestrator.getState()?.productsDiscussed).toContain('A');});
 it('rotates to another product and avoids unnecessary repeats',async()=>{let now=0;const h=harness([fixture(),fixture({id:'B',name:'Product B',priority:40})],{now:()=>now});h.orchestrator.start(1);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.orchestrator.getState()?.currentProductId).toBe('A');for(let i=0;i<4;i++){now+=1;await h.orchestrator.tick();}expect(h.orchestrator.getState()?.currentProductId).toBe(null);now+=1;await h.orchestrator.tick();expect(h.orchestrator.getState()?.currentProductId).toBe('B');});
 it('excludes out-of-stock and inactive products',async()=>{const h=harness([fixture({stock:0}),fixture({id:'B',status:'INACTIVE'})]);h.orchestrator.start(1);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledOnce();expect(h.orchestrator.getState()?.currentIntent).toBe('WAIT');});
 it('rejects invalid product-engine state safely without product speech',async()=>{const broken={active:()=>{throw new Error('invalid catalog record');}} as unknown as ProductCatalog;const h=harness([],{catalog:broken});h.orchestrator.start(1);await h.orchestrator.tick();expect(h.hostEngine.generate).not.toHaveBeenCalled();expect(h.events.some(e=>e.type==='ORCHESTRATOR_ERROR')).toBe(true);});
 it('routes every autonomous speech through HostEngine and respects its policy failure',async()=>{const h=harness([fixture()],{answerFor:r=>r.context.currentProduct?{ok:false,code:'INVALID_AI_RESPONSE',message:'policy rejected'}:successful});h.orchestrator.start(1);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledTimes(2);expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='PRODUCT_INTRO')).toBe(false);expect(h.events.some(e=>e.type==='ORCHESTRATOR_ERROR')).toBe(true);});
 it('does not invent audience state or emit audience-comment actions',async()=>{const h=harness();h.orchestrator.start(1);await h.orchestrator.tick();expect(h.orchestrator.getState()?.audience).toEqual({kind:'UNKNOWN'});expect(h.requests[0]?.context.audienceCount).toBeUndefined();expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toBe(false);});
 it('human pause override prevents subsequent autonomous speech',async()=>{const h=harness();h.orchestrator.start(1);await h.orchestrator.tick();h.orchestrator.pause();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledOnce();expect(h.events.some(e=>e.type==='AI_PAUSED')).toBe(true);});
 it('drops a generated response if human takeover pauses during provider generation',async()=>{const h=harness();let resolve!:(result:HostGenerationResult)=>void;h.hostEngine.generate.mockImplementation(async()=>new Promise<HostGenerationResult>(r=>{resolve=r;}));h.orchestrator.start(1);const pending=h.orchestrator.tick();h.orchestrator.pause();resolve(successful);await pending;expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY')).toBe(false);});
 it('resumes safely without immediately bypassing speech cooldown',async()=>{let now=0;const h=harness([fixture()],{now:()=>now,cooldowns:{globalSpeechMs:100}});h.orchestrator.start(1);await h.orchestrator.tick();h.orchestrator.pause();now=10;h.orchestrator.resume();expect(h.scheduler.runNext()).toBeGreaterThanOrEqual(90);});
 it('clears scheduled timers on stop and prevents multiple start timers',()=>{const h=harness();h.orchestrator.start(1);h.orchestrator.start(1);expect(h.scheduler.jobs.size).toBe(1);h.orchestrator.stop();expect(h.scheduler.jobs.size).toBe(0);});
 it('backs off after HostEngine failure instead of retrying rapidly',async()=>{let now=0;const h=harness([],{now:()=>now,answer:{ok:false,code:'AI_OFFLINE',message:'offline'}});h.orchestrator.start(1);await h.orchestrator.tick();expect(h.orchestrator.getState()?.retryAfter).toBe(20);const delay=[...h.scheduler.jobs.values()][0]?.delay;expect(delay).toBeGreaterThanOrEqual(20);});
 it('repeats the only available product only after its repeat cooldown',async()=>{let now=0;const h=harness([fixture()],{now:()=>now,cooldowns:{repeatedProductMs:100}});h.orchestrator.start(1);await h.orchestrator.tick();await h.orchestrator.tick();for(let i=0;i<4;i++)await h.orchestrator.tick();expect(h.orchestrator.getState()?.currentProductId).toBe(null);await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledTimes(6);now=101;await h.orchestrator.tick();expect(h.orchestrator.getState()?.currentProductId).toBe('A');expect(h.hostEngine.generate).toHaveBeenCalledTimes(7);});
 it('updates product, action, and speech timestamps after validated responses',async()=>{let now=100;const h=harness([fixture()],{now:()=>now});h.orchestrator.start(9);await h.orchestrator.tick();expect(h.orchestrator.getState()).toMatchObject({lastActionAt:100,lastSpeechAt:100,greeted:true,currentIntent:'GREETING'});now+=1;await h.orchestrator.tick();expect(h.orchestrator.getState()).toMatchObject({lastProductId:'A',currentProductId:'A',currentIntent:'PRODUCT_INTRO',productsDiscussed:['A']});});
});

describe('Phase 12 audience decision end-to-end routing',()=>{
 it('answers a named verified product price from Product Engine without an extra LLM call',async()=>{const h=harness([fixture()],{audienceTask:{text:'berapa harga Product A?',intent:'PRICE_QUESTION'}});h.orchestrator.start(90);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledOnce();expect(h.events.find(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toMatchObject({result:{ok:true,response:{speech:expect.stringContaining('250')}}})});
 it('routes product recommendations through fast LLM and the output judge',async()=>{const h=harness([fixture()],{audienceTask:{text:'produk ini cocok buat perjalanan?',intent:'PRODUCT_RECOMMENDATION'}});h.orchestrator.start(91);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledTimes(2);expect(h.requests[1]?.instruction).toContain('Decision route: LLM_FAST');expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toBe(true)});
 it('routes product comparisons to the strong conceptual LLM route',async()=>{const h=harness([fixture()],{audienceTask:{text:'bandingkan Product A dan B',intent:'COMPARISON'}});h.orchestrator.start(92);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.requests[1]?.instruction).toContain('Decision route: LLM_STRONG')});
 it('ignores spam without requesting an LLM response',async()=>{const h=harness([fixture()],{audienceTask:{text:'spam message',intent:'SPAM'}});h.orchestrator.start(93);await h.orchestrator.tick();const before=h.hostEngine.generate.mock.calls.length;await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledTimes(before);expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toBe(false)});
 it('rejects an invented stock answer and emits no host response for TTS',async()=>{const h=harness([fixture()],{audienceTask:{text:'berapa stok Product A?',intent:'PRODUCT_QUESTION'},answerFor:r=>r.trigger==='COMMENT'?{...successful,response:{...successful.response,speech:'Stok tinggal 3 unit.'}}:successful});h.orchestrator.start(94);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toBe(false);expect(h.events.some(e=>e.type==='ORCHESTRATOR_ERROR'&&e.message.includes('validation'))).toBe(true)});
 it('never lets an unknown stock question enter LLM when no product can be resolved',async()=>{const h=harness([],{audienceTask:{text:'berapa stok?',intent:'STOCK_QUESTION'}});h.orchestrator.start(95);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledOnce();expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toBe(false)});
 it('does not let a JEv deterministic claim bypass Product Engine resolution',async()=>{const jev:DecisionProvider={id:'jev',isAvailable:async()=>true,decide:async()=>({decision:'DETERMINISTIC',intent:'PRICE_QUESTION',confidence:.99,reasonCode:'JEv_CLAIM',requiresLlm:false,requiresHuman:false,toolAllowed:false,provider:'jev'})};const h=harness([],{audienceTask:{text:'unknown product fact',intent:'UNKNOWN'},decisionProvider:jev});h.orchestrator.start(97);await h.orchestrator.tick();await h.orchestrator.tick();expect(h.hostEngine.generate).toHaveBeenCalledOnce();expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toBe(false)});
 it('cancels pending provider work and drops the result during human takeover',async()=>{let started=false;const slow:DecisionProvider={id:'slow',isAvailable:async()=>true,decide:async(_request,signal)=>new Promise<DecisionResult>((_resolve,reject)=>{started=true;signal?.addEventListener('abort',()=>reject(new Error('aborted')),{once:true})})};const h=harness([fixture()],{audienceTask:{text:'please say hello',intent:'UNKNOWN'},decisionProvider:slow});h.orchestrator.start(96);await h.orchestrator.tick();const pending=h.orchestrator.tick();await vi.waitFor(()=>expect(started).toBe(true));h.orchestrator.pause();await pending;expect(h.events.some(e=>e.type==='HOST_RESPONSE_READY'&&e.action==='AUDIENCE_COMMENT')).toBe(false)});
});

describe('DecisionEngine',()=>{
 const state=(values:Partial<LiveSessionState>={})=>({sessionId:1,running:true,paused:false,startedAt:0,lastActionAt:null,lastSpeechAt:null,lastProductId:null,currentProductId:null,productsDiscussed:[],lastProductIntroAt:null,currentIntent:null,currentProductStage:null,nextProductStageIndex:0,greeted:true,humanPresence:'UNKNOWN',audience:{kind:'UNKNOWN'},failureCount:0,retryAfter:null,...values}) as LiveSessionState;
 const engine=new DecisionEngine();
 it('returns WAIT for pause, cooldown, backoff, and no products',()=>{const p=fixture();expect(engine.decide(state({paused:true}),{now:0,productAvailable:true,product:p,globalCooldown:false,productCooldown:false,backoff:false}).action).toBe('WAIT');expect(engine.decide(state(),{now:0,productAvailable:true,product:p,globalCooldown:true,productCooldown:false,backoff:false}).action).toBe('WAIT');expect(engine.decide(state(),{now:0,productAvailable:false,product:null,globalCooldown:false,productCooldown:false,backoff:false}).action).toBe('WAIT');});
 it('returns PRODUCT_INTRO and then sales-stage decisions including CTA',()=>{const p=fixture();expect(engine.decide(state(),{now:0,productAvailable:true,product:null,globalCooldown:false,productCooldown:false,backoff:false}).action).toBe('PRODUCT_INTRO');expect(engine.decide(state({currentProductId:'A'}),{now:0,productAvailable:true,product:p,globalCooldown:false,productCooldown:false,backoff:false}).action).toBe('PRODUCT_BENEFIT');expect(engine.decide(state({currentProductId:'A',nextProductStageIndex:3}),{now:0,productAvailable:true,product:p,globalCooldown:false,productCooldown:false,backoff:false}).action).toBe('CTA');});
});
