import {describe,expect,it,vi} from 'vitest';
import {classifyAudienceIntent} from '../packages/audience-engine/src/index.js';
import {DecisionCache,DecisionIntelligence,DecisionMetricsCollector,DeterministicDecisionProvider,JevDecisionProvider,LLMRouter,OutputJudge,ToolGate,applyConfidence,confidenceBand,deterministicRule,estimateComplexity,verifiedProductAnswer,type DecisionProvider,type DecisionRequest,type DecisionResult} from '../packages/decision-intelligence/src/index.js';
import type {TypeSafeClient} from '@typesafe-ai/sdk';

const base:DecisionRequest={eventType:'COMMENT',source:'simulator',text:'pertanyaan sederhana',intent:'PRODUCT_QUESTION',timestamp:100};
const known={id:'p-1',name:'Produk Uji',price:15000,currency:'IDR',promoPrice:null,stock:8,benefits:[],forbiddenClaims:[]};
function provider(result:DecisionResult|(()=>Promise<DecisionResult>),available=true):DecisionProvider{return{id:'mock-jev',isAvailable:async()=>available,decide:async()=>typeof result==='function'?result():structuredClone(result)}}
const jevResult=(patch:Partial<DecisionResult>={}):DecisionResult=>({decision:'LLM_FAST',intent:'PRODUCT_QUESTION',confidence:.95,reasonCode:'JEV_STRUCTURED_DECISION',requiresLlm:true,requiresHuman:false,toolAllowed:false,provider:'jev',...patch});

describe('Phase 12 deterministic intent routing',()=>{
  const routes:[string,DecisionRequest['intent'],DecisionResult['decision'],boolean][]=[['GREETING','GREETING','LLM_FAST',false],['PRODUCT_QUESTION','PRODUCT_QUESTION','LLM_FAST',false],['PRICE_QUESTION','PRICE_QUESTION','DETERMINISTIC',true],['STOCK_QUESTION','STOCK_QUESTION','DETERMINISTIC',true],['VARIANT_QUESTION','VARIANT_QUESTION','LLM_FAST',false],['PRODUCT_RECOMMENDATION','PRODUCT_RECOMMENDATION','LLM_FAST',false],['COMPARISON','COMPARISON','LLM_STRONG',false],['PURCHASE_INTENT','PURCHASE_INTENT','LLM_FAST',false],['COMPLAINT','COMPLAINT','ESCALATE',false],['JOKE','JOKE','LLM_FAST',false],['REACTION','REACTION','IGNORE',false],['SPAM','SPAM','IGNORE',false],['ABUSE','ABUSE','IGNORE',false],['OFF_TOPIC','OFF_TOPIC','IGNORE',false],['GENERAL_QUESTION','GENERAL_QUESTION','LLM_FAST',false],['REQUEST_DEMO','REQUEST_DEMO','LLM_FAST',false],['UNKNOWN','UNKNOWN','ESCALATE',false],['PRICE_UNVERIFIED','PRICE_QUESTION','DETERMINISTIC',false],['STOCK_UNVERIFIED','STOCK_QUESTION','DETERMINISTIC',false],['PRICE_NO_CONTEXT','PRICE_QUESTION','DETERMINISTIC',false]];
  it.each(Array.from({length:200},(_,i)=>{const route=routes[i%routes.length]!;return{caseId:i,route}}))('classifies and routes normalized intent case $caseId',({route})=>{const request:DecisionRequest={...base,intent:route[1],productContext:route[3]?{productId:'p-1',verified:true}:undefined};const decision=deterministicRule(request);if(route[2]==='ESCALATE'&&route[1]==='UNKNOWN')expect(decision).toBeNull();else if(!route[3]&&(route[1]==='PRICE_QUESTION'||route[1]==='STOCK_QUESTION'))expect(decision?.decision).toBe(route[2]);else expect(decision?.decision).toBe(route[2])});
  it.each([
    ['berapa harga produk uji?', 'PRICE_QUESTION'],['stok tersedia berapa?', 'STOCK_QUESTION'],['tolong bandingkan produk A dan B','COMPARISON'],['produk ini cocok untuk mahasiswa?','PRODUCT_RECOMMENDATION'],['saya mau checkout sekarang','PURCHASE_INTENT'],['wkwkwkwkw','JOKE'],['halo kak','GREETING'],['keren sekali','REACTION'],['pesan saya rusak','COMPLAINT'],['bagaimana cara pakai produk ini?','REQUEST_DEMO']
  ] as const)('reuses Audience Engine intent classification for %s', (text,intent)=>expect(classifyAudienceIntent(text)).toBe(intent));
  it('answers verified current facts from Product Engine fields only',()=>{expect(verifiedProductAnswer('PRICE_QUESTION',known)).toContain('15.000');expect(verifiedProductAnswer('STOCK_QUESTION',known)).toContain('8 unit')});
  it('does not invent unavailable price or stock',()=>{const unknown={...known,price:null,stock:null};expect(verifiedProductAnswer('PRICE_QUESTION',unknown)).toContain('belum tersedia');expect(verifiedProductAnswer('STOCK_QUESTION',unknown)).toContain('belum tersedia')});
  it('detects question complexity deterministically',()=>{expect(estimateComplexity('Halo kak')).toBe('SIMPLE');expect(estimateComplexity('Apakah ini cocok untuk saya?')).toBe('MODERATE');expect(estimateComplexity('Bandingkan A dan B untuk perjalanan jauh, jelaskan kompromi utama?')).toBe('COMPLEX');expect(estimateComplexity('')).toBe('UNKNOWN')});
  it('lets an unknown but nonempty audience event reach the strong fallback route',async()=>{const audience=new (await import('../packages/audience-engine/src/index.js')).AudienceEngine();const event=audience.ingest({text:'ok',type:'COMMENT'});expect(event.accepted).toBe(true);expect(event.intent).toBe('UNKNOWN');const di=new DecisionIntelligence({primary:provider(jevResult(),false)});expect(await di.decide({eventType:'COMMENT',source:'simulator',text:'ok',intent:event.intent,timestamp:100})).toMatchObject({decision:'LLM_STRONG',reasonCode:'JEV_UNAVAILABLE_FALLBACK'})});
  it('classifies emergency and takeover before any provider call',async()=>{let calls=0;const di=new DecisionIntelligence({primary:provider(jevResult()),now:()=>100});di.jevProvider.decide=async()=>{calls++;return jevResult()};expect((await di.decide({...base,eventType:'EMERGENCY_STOP'})).reasonCode).toBe('EMERGENCY_PRIORITY');expect((await di.decide({...base,liveState:'HUMAN_TAKEOVER'})).reasonCode).toBe('HUMAN_TAKEOVER_ACTIVE');expect(calls).toBe(0)});
});

describe('Phase 12 provider fallback, timeout, and confidence',()=>{
  it('uses deterministic fallback when Jev is not configured',async()=>{const di=new DecisionIntelligence({primary:provider(jevResult(),false)});const result=await di.decide({...base,intent:'UNKNOWN'});expect(result).toMatchObject({provider:'fallback',decision:'LLM_STRONG',reasonCode:'JEV_UNAVAILABLE_FALLBACK'})});
  it('rejects malformed provider output instead of trusting it',async()=>{const di=new DecisionIntelligence({primary:provider({} as DecisionResult)});expect(await di.decide({...base,intent:'UNKNOWN'})).toMatchObject({decision:'REJECT',reasonCode:'MALFORMED_JEV_RESPONSE',requiresHuman:true})});
  it('rejects invalid confidence rather than clamping it',async()=>{const di=new DecisionIntelligence({primary:provider(jevResult({confidence:1.5}))});expect(await di.decide({...base,intent:'UNKNOWN'})).toMatchObject({decision:'REJECT',reasonCode:'MALFORMED_JEV_RESPONSE'})});
  it.each([[.95,'ACCEPT','LLM_FAST'],[.9,'ACCEPT','LLM_FAST'],[.89,'VALIDATE','QUEUE'],[.7,'VALIDATE','QUEUE'],[.69,'ESCALATE','ESCALATE'],[0,'ESCALATE','ESCALATE'],[-.1,'INVALID','REJECT'],[1.1,'INVALID','REJECT'],[NaN,'INVALID','REJECT']] as const)('applies confidence boundary %s', (value,band,decision)=>{expect(confidenceBand(value)).toBe(band);expect(applyConfidence(jevResult({confidence:value})).decision).toBe(decision)});
  it('falls back immediately after the configured decision timeout',async()=>{vi.useFakeTimers();try{const slow=provider(()=>new Promise<DecisionResult>(()=>{}));const di=new DecisionIntelligence({primary:slow,timeoutMs:500,now:()=>100});const pending=di.decide({...base,intent:'UNKNOWN'});await vi.advanceTimersByTimeAsync(500);expect(await pending).toMatchObject({provider:'fallback',reasonCode:'JEV_TIMEOUT_FALLBACK',decision:'LLM_STRONG'})}finally{vi.useRealTimers()}});
  it('uses the official SDK provider contract only when an API key exists',async()=>{const absent=new JevDecisionProvider('');expect(await absent.isAvailable()).toBe(false);const answers={intent:{choice:'COMPARISON',confidence:.94},route:{choice:'LLM_STRONG',confidence:.92}};const client={systemOne:vi.fn(async()=>({answers}))} as unknown as TypeSafeClient;const configured=new JevDecisionProvider('test-key',500,client);expect(await configured.isAvailable()).toBe(true);expect(await configured.decide({...base,intent:'UNKNOWN'})).toMatchObject({provider:'jev',intent:'COMPARISON',decision:'LLM_STRONG'});expect(client.systemOne).toHaveBeenCalledOnce()});
  it('sets the official SDK request timeout and disables SDK retries for the live budget',async()=>{const client={systemOne:vi.fn(async()=>({answers:{intent:{choice:'GREETING',confidence:.99},route:{choice:'LLM_FAST',confidence:.99}}}))} as unknown as TypeSafeClient;const configured=new JevDecisionProvider('key',500,client);await configured.decide(base);const mock=client.systemOne as unknown as ReturnType<typeof vi.fn>;expect(mock.mock.calls[0]?.[1]).toMatchObject({timeout:500,retry:{maxRetries:0}})});
  it('cancels pending decisions when disabled and clears cached results',async()=>{const pending:DecisionProvider={id:'pending',isAvailable:async()=>true,decide:(_request,signal)=>new Promise((_resolve,reject)=>signal?.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}))};const di=new DecisionIntelligence({primary:pending});const work=di.decide({...base,intent:'UNKNOWN'});di.setEnabled(false);await expect(work).resolves.toMatchObject({decision:'QUEUE',reasonCode:'DECISION_CANCELLED'});expect(di.isEnabled).toBe(false);expect(di.cache.size).toBe(0)});
  it('keeps local fallback operating with intelligence switched off',async()=>{const di=new DecisionIntelligence({primary:provider(jevResult())});di.setEnabled(false);expect(await di.decide({...base,intent:'GREETING'})).toMatchObject({decision:'LLM_FAST',provider:'deterministic'})});
});

describe('Phase 12 tool gate, output judge, cache, and metrics',()=>{
  const gateCases:Array<[string,Parameters<ToolGate['evaluate']>[0],string]>=[['allowed product',{action:'SHOW_PRODUCT',productId:'p1',productExists:true,productValid:true,actionAllowed:true,liveState:'RUNNING',emergencyStopped:false,humanTakeover:false,policyAllowed:true},'ALLOWED'],['missing product',{action:'SHOW_PRODUCT',productId:'missing',productExists:false,productValid:false,actionAllowed:true,liveState:'RUNNING',emergencyStopped:false,humanTakeover:false,policyAllowed:true},'PRODUCT_NOT_FOUND'],['invalid product',{action:'SHOW_PRODUCT',productId:'p1',productExists:true,productValid:false,actionAllowed:true,liveState:'RUNNING',emergencyStopped:false,humanTakeover:false,policyAllowed:true},'INVALID_PRODUCT'],['emergency latch',{action:'SHOW_PRODUCT',productId:'p1',productExists:true,productValid:true,actionAllowed:true,liveState:'EMERGENCY_STOPPED',emergencyStopped:true,humanTakeover:false,policyAllowed:true},'EMERGENCY_STOPPED'],['takeover',{action:'SHOW_PRODUCT',productId:'p1',productExists:true,productValid:true,actionAllowed:true,liveState:'HUMAN_TAKEOVER',emergencyStopped:false,humanTakeover:true,policyAllowed:true},'HUMAN_TAKEOVER'],['policy',{action:'SHOW_PRODUCT',productId:'p1',productExists:true,productValid:true,actionAllowed:true,liveState:'RUNNING',emergencyStopped:false,humanTakeover:false,policyAllowed:false},'POLICY_REJECTED'],['not allowlisted',{action:'DELETE_PRODUCT',productId:'p1',productExists:true,productValid:true,actionAllowed:true,liveState:'RUNNING',emergencyStopped:false,humanTakeover:false,policyAllowed:true},'UNKNOWN_ACTION'],['action disabled',{action:'SHOW_PRODUCT',productId:'p1',productExists:true,productValid:true,actionAllowed:false,liveState:'RUNNING',emergencyStopped:false,humanTakeover:false,policyAllowed:true},'ACTION_NOT_ALLOWED'],['not live',{action:'SHOW_PRODUCT',productId:'p1',productExists:true,productValid:true,actionAllowed:true,liveState:'STOPPED',emergencyStopped:false,humanTakeover:false,policyAllowed:true},'RUNTIME_BLOCKED']];
  it.each(Array.from({length:63},(_,i)=>({id:i,case:gateCases[i%gateCases.length]!})))('gates tool proposal case $id',({case:entry})=>expect(new ToolGate().evaluate(entry[1]).reasonCode).toBe(entry[2]));
  it('rejects unsupported price, stock, and promotion claims before speech',()=>{const judge=new OutputJudge();expect(judge.judge('Harga Rp25.000.',{id:'p1',name:'Produk Uji',price:15000,currency:'IDR',benefits:[],specifications:[],variants:[],sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[]})).toMatchObject({status:'REJECT'});expect(judge.judge('Stok tinggal 3 unit.',{id:'p1',name:'Produk Uji',benefits:[],specifications:[],variants:[],sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[]})).toMatchObject({status:'REJECT'});expect(judge.judge('Harga 15 ribu.')).toMatchObject({status:'REJECT',reasonCode:'UNVERIFIED_COMMERCE_CLAIM'});expect(judge.judge('Diskon besar hari ini.')).toMatchObject({status:'REJECT'})});
  it('rejects unsupported specification and order-status claims',()=>{const judge=new OutputJudge();expect(judge.judge('Botol ini tahan air dan kapasitasnya 2 liter.')).toMatchObject({status:'REJECT',reasonCode:'UNVERIFIED_SPECIFICATION'});expect(judge.judge('Pesanan kamu sudah dikirim.')).toMatchObject({status:'REJECT',reasonCode:'UNVERIFIED_ORDER_CLAIM'})});
  it('accepts verified product answer and rejects empty output',()=>{const judge=new OutputJudge();expect(judge.judge('Harga Produk Uji Rp15.000.',{id:'p1',name:'Produk Uji',price:15000,currency:'IDR',benefits:[],specifications:[],variants:[],sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[]})).toMatchObject({status:'PASS'});expect(judge.judge(' ')).toMatchObject({status:'REJECT',reasonCode:'EMPTY_OUTPUT'})});
  it('does not cache audience text or emergency/takeover decisions',()=>{const cache=new DecisionCache(100,10,()=>1);const result=jevResult();expect(cache.set({...base,text:'private audience text'},result)).toBe(false);expect(cache.set({...base,eventType:'EMERGENCY_STOP',text:undefined},result)).toBe(false);expect(cache.set({...base,eventType:'HUMAN_TAKEOVER',text:undefined},result)).toBe(false);expect(cache.size).toBe(0)});
  it('expires safe structured decision entries using the fake clock',()=>{let now=10;const cache=new DecisionCache(50,10,()=>now);const request={...base,text:undefined};expect(cache.set(request,jevResult())).toBe(true);expect(cache.get(request)?.decision).toBe('LLM_FAST');now=60;expect(cache.get(request)).toBeUndefined()});
  it('invalidates decisions during emergency and human takeover',async()=>{const di=new DecisionIntelligence({primary:provider(jevResult())});di.cache.set({...base,text:undefined},jevResult());await di.decide({...base,eventType:'HUMAN_TAKEOVER',text:undefined});expect(di.cache.size).toBe(0);di.cache.set({...base,text:undefined},jevResult());await di.decide({...base,eventType:'EMERGENCY_STOP',text:undefined});expect(di.cache.size).toBe(0)});
  it('computes bounded safe latency metrics and percentiles',()=>{const metrics=new DecisionMetricsCollector();[5,20,10,30,15].forEach((latency,index)=>metrics.record(index===0?'jev':'deterministic',index===0?'LLM_FAST':'DETERMINISTIC',latency));const snapshot=metrics.snapshot();expect(snapshot).toMatchObject({decisionCount:5,jevDecisionCount:1,fallbackDecisionCount:4,llmFastCount:1,deterministicCount:4,p95DecisionLatency:30});expect(snapshot.averageDecisionLatency).toBe(16)});
  it('never includes decision input or credentials in metrics',async()=>{const secret='access_token=very-secret';const di=new DecisionIntelligence({primary:provider(jevResult())});await di.decide({...base,text:`${secret} question`,intent:'UNKNOWN'});expect(JSON.stringify(di.metrics.snapshot())).not.toContain('very-secret')});
  it('never exposes the JEv key through renderer-facing status snapshots',async()=>{const secret='renderer-must-not-see-this';const di=new DecisionIntelligence({primary:new JevDecisionProvider(secret)});await Promise.resolve();expect(JSON.stringify(di.snapshot())).not.toContain(secret)});
  it('routes fast and strong through the same configured provider when only one model exists',()=>{const router=new LLMRouter('pipip:live');expect(router.resolve('LLM_FAST')).toMatchObject({route:'LLM_FAST',model:'pipip:live'});expect(router.resolve('LLM_STRONG')).toMatchObject({route:'LLM_STRONG',model:'pipip:live'});expect(router.resolve('TOOL')).toBeNull()});
});
