import {describe,it,expect,vi} from 'vitest';
import {AudienceEngine,classifyAudienceIntent,normalizeAudienceEvent,selectResponseMode,AudienceQueue} from '../packages/audience-engine/src/index.js';
import {DEFAULT_PERSONALITIES,PersonalityManager} from '../packages/personality-engine/src/index.js';
import {KnowledgeCache,KnowledgeRouter,PolicyKnowledgeProvider,LearningPipeline,GeminiExpertProvider,OpenAIExpertProvider,validateSources,scrubExpertQuery} from '../packages/knowledge-engine/src/index.js';

describe('Phase 4 audience intelligence',()=>{
 it.each([
  ['harga berapa','PRICE_QUESTION'],['diskon promo berapa','PRICE_QUESTION'],['stok ready?','STOCK_QUESTION'],['apakah tersedia','STOCK_QUESTION'],['warna apa saja','VARIANT_QUESTION'],['ukuran size berapa','VARIANT_QUESTION'],['tolong demo produk','REQUEST_DEMO'],['cara pakai bagaimana','REQUEST_DEMO'],['barang rusak','COMPLAINT'],['saya kecewa','COMPLAINT'],['halo kak','GREETING'],['selamat pagi','GREETING'],['bagus keren','REACTION'],['wkwk lucu','REACTION'],['bodoh sekali','ABUSE'],['anjing','ABUSE'],['lihat https://x.test','SPAM'],['www.example.com','SPAM'],['produk ini bagaimana','PRODUCT_QUESTION'],['manfaat barang apa','PRODUCT_QUESTION'],['ceritakan sesuatu','GENERAL_QUESTION'],['?', 'UNKNOWN'],['','UNKNOWN']
 ] as const)('intent classification case %s', (text,intent)=>expect(classifyAudienceIntent(text)).toBe(intent));
 it.each([['simulator','simulator'],['tiktok','tiktok'],['youtube','youtube'],['website','website'],['bad','unknown']] as const)('source normalization %s', (source,expected)=>expect(normalizeAudienceEvent({source,text:' Halo ',type:'COMMENT'},10).source).toBe(expected));
 it.each([['COMMENT','COMMENT'],['FOLLOW','FOLLOW'],['LIKE','LIKE'],['GIFT','GIFT'],['NEW_VIEWER','NEW_VIEWER'],['SYSTEM','SYSTEM'],['bad','UNKNOWN']] as const)('event type normalization %s',(type,expected)=>expect(normalizeAudienceEvent({type,text:'ok'},12).type).toBe(expected));
 it.each([['ABUSE','IGNORE'],['SPAM','IGNORE'],['OFF_TOPIC','IGNORE'],['UNKNOWN','SHORT_RESPONSE'],['REACTION','VISUAL_REACTION'],['GREETING','SHORT_RESPONSE'],['GENERAL_QUESTION','SHORT_RESPONSE'],['PRICE_QUESTION','FULL_RESPONSE'],['STOCK_QUESTION','FULL_RESPONSE'],['VARIANT_QUESTION','FULL_RESPONSE'],['PRODUCT_QUESTION','FULL_RESPONSE'],['COMPLAINT','FULL_RESPONSE'],['REQUEST_DEMO','FULL_RESPONSE']] as const)('response mode for %s',(intent,mode)=>expect(selectResponseMode(intent)).toBe(mode));
 it('trims, truncates, and uses a valid timestamp',()=>{const e=normalizeAudienceEvent({text:` ${'x'.repeat(600)} `,timestamp:'invalid'},42);expect(e.text).toHaveLength(500);expect(e.timestamp).toBe(42)});
 it('rejects blank audience input',()=>expect(new AudienceEngine().ingest({text:'  ',type:'COMMENT'}).reason).toBe('empty'));
 it('ignores non-comment social events for speech',()=>expect(new AudienceEngine().ingest({text:'hello',type:'FOLLOW'}).reason).toBe('unsupported_event'));
 it('deduplicates equivalent comments',()=>{const e=new AudienceEngine();expect(e.ingest({text:'Harga berapa?',type:'COMMENT'}).accepted).toBe(true);expect(e.ingest({text:'harga berapa',type:'COMMENT'}).reason).toBe('duplicate')});
 it('drops repeated-character spam',()=>expect(new AudienceEngine().ingest({text:'aaaaaaaaa',type:'COMMENT'}).reason).toBe('spam'));
 it('queues accepted comments',()=>{const e=new AudienceEngine();e.ingest({text:'Ada pertanyaan umum',type:'COMMENT'});expect(e.size).toBe(1);expect(e.next()?.event.text).toBe('Ada pertanyaan umum')});
 it('clears queue and privacy memory on stop',()=>{const e=new AudienceEngine();e.ingest({text:'Harga berapa',type:'COMMENT'});e.clear();expect(e.size).toBe(0);expect(e.ingest({text:'harga berapa',type:'COMMENT'}).accepted).toBe(true)});
 it('prefers high priority tasks and preserves FIFO at equal priority',()=>{let now=100;const q=new AudienceQueue(10,500,()=>now);const task=(text:string,priority:number,enqueuedAt:number)=>({event:{source:'simulator' as const,type:'COMMENT' as const,text,timestamp:now},intent:'GENERAL_QUESTION' as const,mode:'SHORT_RESPONSE' as const,priority,enqueuedAt});q.enqueue(task('low',10,1));q.enqueue(task('first high',90,2));q.enqueue(task('second high',90,3));expect(q.pop()?.event.text).toBe('first high');expect(q.pop()?.event.text).toBe('second high')});
 it('expires stale queued items',()=>{let now=1;const q=new AudienceQueue(10,10,()=>now);q.enqueue({event:{source:'simulator',type:'COMMENT',text:'x',timestamp:1},intent:'UNKNOWN',mode:'SHORT_RESPONSE',priority:1,enqueuedAt:1});now=12;expect(q.size()).toBe(0)});
 it('bounds queue capacity',()=>{const q=new AudienceQueue(1);const task=(text:string)=>({event:{source:'simulator' as const,type:'COMMENT' as const,text,timestamp:Date.now()},intent:'UNKNOWN' as const,mode:'SHORT_RESPONSE' as const,priority:1,enqueuedAt:Date.now()});expect(q.enqueue(task('one'))).toBe(true);expect(q.enqueue(task('two'))).toBe(false)});
 it('freezes new accepted work into queue mode during pause',()=>{const d=new AudienceEngine().ingest({text:'halo kak',type:'COMMENT'},{paused:true});expect(d.accepted).toBe(true);expect(d.mode).toBe('QUEUE')});
 it('human override suppresses response',()=>{const d=new AudienceEngine().ingest({text:'halo kak',type:'COMMENT'},{humanOverride:true});expect(d.accepted).toBe(false);expect(d.mode).toBe('IGNORE')});
 it('does not include user identity in normalized event',()=>{const e=normalizeAudienceEvent({text:'halo',userId:'secret-id',displayName:'Secret'});expect(JSON.stringify(e)).not.toContain('secret')});
});

describe('Phase 4 personality constitution',()=>{
 it.each(DEFAULT_PERSONALITIES.map(x=>[x.id,x.name]))('defines personality %s',(id,name)=>expect(DEFAULT_PERSONALITIES.find(x=>x.id===id)?.name).toBe(name));
 it('defaults safely to balanced persona',()=>expect(new PersonalityManager().getActive().id).toBe('default-personality'));
 it('changes active style without restart',()=>{const m=new PersonalityManager();m.setActive('funny');expect(m.getActive().id).toBe('funny')});
 it('rejects unknown persona keys',()=>expect(()=>new PersonalityManager().setActive('custom-prompt')).toThrow());
 it('exposes only id and display name to selector UI',()=>expect(new PersonalityManager().list()[0]).toEqual({id:'friendly',name:'Ramah'}));
});

describe('Phase 4 knowledge and policy routing',()=>{
 it.each(['https://example.com','https://platform.example/policy'])('accepts HTTPS source %s',url=>expect(validateSources([{url}])).toHaveLength(1));
 it.each(['http://example.com','javascript:alert(1)','not a URL'])('rejects unsafe source %s',url=>expect(validateSources([{url}])).toHaveLength(0));
 it('routes product facts only to verified catalog context',async()=>{const r=new KnowledgeRouter();expect((await r.route({query:'harga?',topic:'PRODUCT',hasVerifiedProduct:false})).status).toBe('NEEDS_PRODUCT_DATA');expect((await r.route({query:'harga?',topic:'PRODUCT',hasVerifiedProduct:true})).status).toBe('CAN_ANSWER')});
 it('never sends policy questions to external experts',async()=>{const spy=vi.fn();const r=new KnowledgeRouter([{id:'fake',available:true,answer:spy}]);expect((await r.route({query:'rules',topic:'PLATFORM_POLICY',hasVerifiedProduct:false})).status).toBe('NEEDS_PLATFORM_POLICY');expect(spy).not.toHaveBeenCalled()});
 it('returns unknown for empty policy records',()=>expect(new PolicyKnowledgeProvider().getApplicableRules({platform:'tiktok',market:'ID',contentType:'live',commerceType:'commerce'}).status).toBe('UNKNOWN'));
 it('matches only exact policy platform and market',()=>{const p=new PolicyKnowledgeProvider([{platform:'tiktok',market:'ID',contentType:'live',commerceType:'commerce',text:'rule',sourceUrl:'https://official.example/rule',verifiedAt:new Date().toISOString()}]);expect(p.getApplicableRules({platform:'tiktok',market:'ID',contentType:'live',commerceType:'commerce'}).status).toBe('VERIFIED_SOURCES');expect(p.getApplicableRules({platform:'tiktok',market:'US',contentType:'live',commerceType:'commerce'}).status).toBe('UNKNOWN')});
 it('ignores expired policy sources',()=>{const p=new PolicyKnowledgeProvider([{platform:'tiktok',market:'ID',contentType:'live',commerceType:'commerce',text:'rule',sourceUrl:'https://official.example/rule',verifiedAt:'2020-01-01',expiresAt:'2021-01-01'}]);expect(p.getApplicableRules({platform:'tiktok',market:'ID',contentType:'live',commerceType:'commerce'}).status).toBe('UNKNOWN')});
 it('returns unknown for unavailable general advisor',async()=>expect((await new KnowledgeRouter().route({query:'science',topic:'GENERAL',hasVerifiedProduct:false})).status).toBe('UNKNOWN'));
 it('passes generic query only to expert and preserves low confidence as advisory',async()=>{const answer=vi.fn(async(req:{query:string})=>({provider:'fake',text:'advice',sources:[],confidence:.2,retrievedAt:new Date().toISOString()}));const r=new KnowledgeRouter([{id:'fake',available:true,answer}]);const result=await r.route({query:'generic question',topic:'GENERAL',hasVerifiedProduct:false});expect(result.status).toBe('NEEDS_EXTERNAL_EXPERT');expect(result.advice?.text).toBe('advice');expect(answer.mock.calls[0]?.[0].query).toBe('generic question')});
 it('routes high confidence generic advice for host review',async()=>{const answer=async()=>({provider:'fake',text:'brief background',sources:[],confidence:.9,retrievedAt:new Date().toISOString()});const r=new KnowledgeRouter([{id:'fake',available:true,answer}]);expect((await r.route({query:'generic question',topic:'GENERAL',hasVerifiedProduct:false})).advice?.text).toBe('brief background')});
 it('caches external answer with a bounded cache',()=>{let now=1;const c=new KnowledgeCache(5,1,()=>now);const a={provider:'x',text:'a',sources:[],confidence:1,retrievedAt:''};c.set('one',a);expect(c.get('one')?.text).toBe('a');c.set('two',{...a,text:'b'});expect(c.get('one')).toBeUndefined();now=10;expect(c.get('two')).toBeUndefined()});
 it('uses Gemini API key header and parses official interaction output',async()=>{const f=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>new Response(JSON.stringify({output_text:'safe advice'}),{status:200}));const p=new GeminiExpertProvider('key','model',f as typeof fetch);const out=await p.answer({query:'query',topic:'GENERAL'});expect(out.text).toBe('safe advice');expect((f.mock.calls[0]?.[1]?.headers as Record<string,string>)['x-goog-api-key']).toBe('key')});
 it('uses OpenAI Responses endpoint with storage disabled',async()=>{const f=vi.fn(async(_url:RequestInfo|URL,init?:RequestInit)=>new Response(JSON.stringify({output_text:'safe advice'}),{status:200}));const p=new OpenAIExpertProvider('key','model',f as typeof fetch);expect((await p.answer({query:'query',topic:'GENERAL'})).text).toBe('safe advice');expect(JSON.parse(String(f.mock.calls[0]?.[1]?.body)).store).toBe(false)});
 it('does not call external provider without key',async()=>{const f=vi.fn();const p=new OpenAIExpertProvider(undefined,'model',f as typeof fetch);await expect(p.answer({query:'q',topic:'GENERAL'})).rejects.toThrow();expect(f).not.toHaveBeenCalled()});
 it('removes email, phone, and handle before expert routing',async()=>{const answer=vi.fn(async(req:{query:string})=>({provider:'fake',text:'advice',sources:[],confidence:.8,retrievedAt:''}));const router=new KnowledgeRouter([{id:'fake',available:true,answer}]);await router.route({query:'contact me@example.com or +62 812-3456-7890 @alice',topic:'GENERAL',hasVerifiedProduct:false});expect(answer.mock.calls[0]?.[0].query).not.toMatch(/me@example|812-3456|@alice/);expect(scrubExpertQuery('me@example.com')).toBe('[email]')});
 it('does not return non-HTTPS sources',()=>expect(validateSources([{url:'http://unsafe'},{url:'https://safe'}])).toEqual([{url:'https://safe'}]));
});

describe('Phase 4 learning feedback records',()=>{
 it('records pending human evaluation only',()=>{const p=new LearningPipeline();expect(p.record({id:'1',topic:'general',intent:'question',label:'PENDING'}).label).toBe('PENDING')});
 it.each(['GOOD','BAD','NEEDS_REVIEW','PENDING'] as const)('allows explicit evaluation label %s',label=>{const p=new LearningPipeline();p.record({id:'1',topic:'t',intent:'i',label:'PENDING'});expect(p.label('1',label)).toBe(true);expect(p.list()[0]?.label).toBe(label)});
 it('does not mutate unknown record IDs',()=>expect(new LearningPipeline().label('missing','GOOD')).toBe(false));
 it('bounds notes and stored record count',()=>{const p=new LearningPipeline(1);p.record({id:'a',topic:'t',intent:'i',label:'PENDING',note:'x'.repeat(500)});p.record({id:'b',topic:'t',intent:'i',label:'PENDING'});expect(p.list()).toHaveLength(1);expect(p.list()[0]?.id).toBe('b')});
 it('retains no account identity fields by record schema',()=>{const record=new LearningPipeline().record({id:'1',topic:'general',intent:'question',label:'PENDING'});expect(JSON.stringify(record)).not.toContain('userId')});
});
