import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import {readdir,readFile,stat} from 'node:fs/promises';
import path from 'node:path';
import {describe,expect,it} from 'vitest';
import {AvatarCommandQueue,AvatarEngine,AVATAR_STATES,EmotionEngine,GestureEngine,MockAvatarRuntimeAdapter,MockSpeechTimingProvider,assertAvatarTransition,canTransitionAvatar,createAvatarCommand,initialAvatarState,validateRuntimeCommand} from '../packages/avatar-engine/src/index.js';
import type {AvatarCommand,AvatarStateName} from '../packages/avatar-engine/src/index.js';
import type {HostResponse} from '../packages/shared-types/src/index.js';

const response=(overrides:Partial<HostResponse>={}):HostResponse=>({speech:'Nah, produk ini menarik banget.',emotion:'excited',gesture:'point_product',intent:'product_intro',...overrides});
const cmd=(overrides:Partial<AvatarCommand>={}):AvatarCommand=>createAvatarCommand({id:'cmd-1',source:'host',timestamp:1000,durationMs:3000,...overrides},1000);

describe('Phase 7 avatar semantic engine',()=>{
 it.each(AVATAR_STATES.flatMap(from=>AVATAR_STATES.map(to=>[from,to] as const)))('validates state transition matrix %s -> %s',(from,to)=>{const allowed=canTransitionAvatar(from,to);if(allowed)expect(()=>assertAvatarTransition(from,to)).not.toThrow();else expect(()=>assertAvatarTransition(from,to)).toThrow()});
 it('starts from a neutral deterministic state',()=>expect(initialAvatarState()).toMatchObject({state:'IDLE',emotion:'neutral',expression:'neutral',gesture:'none',queueLength:0,connected:false}));
 it.each([
  ['friendly','friendly','smile'],['funny','happy','big_smile'],['energetic','excited','big_smile'],['expert','friendly','smile'],['default-personality','excited','big_smile'],
 ] as const)('maps %s personality to semantic emotion and expression', (personality,emotion,expression)=>expect(new EmotionEngine().map(response(),personality)).toMatchObject({emotion,expression}));
 it('does not change speech facts when mapping emotion',()=>{const host=response({speech:'Rp89.000 dan SKU X1 tetap.',emotion:'happy'});expect(new EmotionEngine().map(host,'funny')).toMatchObject({emotion:'happy'});expect(host.speech).toBe('Rp89.000 dan SKU X1 tetap.')});
 it.each([
  ['greeting',{intent:'greeting',gesture:'idle'},'wave'],['product intro',{intent:'product_intro',gesture:'idle'},'point_product'],['product detail',{intent:'product_explanation',gesture:'idle'},'point_product'],['positive answer',{intent:'answer',gesture:'idle'},'nod'],['think',{intent:'general_chat',gesture:'think'},'thinking'],['surprise',{intent:'general_chat',gesture:'surprised'},'open_hands'],['comedy',{intent:'comedy',gesture:'laugh'},'nod'],['energetic comedy',{intent:'comedy',gesture:'laugh'},'celebrate'],['presentation',{intent:'general_chat',gesture:'present'},'open_hands'],['human point suppression',{intent:'general_chat',gesture:'point_human'},'none'],
 ] as const)('maps gesture intent: %s',(_label,patch,expected)=>expect(new GestureEngine(3000,()=>10000).select(response(patch as Partial<HostResponse>),'MANUAL',_label==='energetic comedy'?'energetic':'default-personality')).toBe(expected));
 it('suppresses same gesture before the configured cooldown',()=>{let now=0;const mapper=new GestureEngine(3000,()=>now);expect(mapper.select(response({intent:'greeting',gesture:'wave'}),'MANUAL')).toBe('wave');now=2999;expect(mapper.select(response({intent:'greeting',gesture:'wave'}),'MANUAL')).toBe('none');now=3000;expect(mapper.select(response({intent:'greeting',gesture:'wave'}),'MANUAL')).toBe('wave')});
 it.each([1999,5001])('rejects out-of-range gesture cooldown %i',cooldown=>expect(()=>new GestureEngine(cooldown)).toThrow());
 it('allows a different gesture immediately',()=>{const mapper=new GestureEngine(3000,()=>5000);expect(mapper.select(response({intent:'greeting',gesture:'wave'}),'MANUAL')).toBe('wave');expect(mapper.select(response({intent:'answer',gesture:'idle'}),'MANUAL')).toBe('nod')});
 it('creates bounded commands without renderer-specific transforms',()=>{const value=cmd({metadata:{intent:'greeting'}});expect(value.id).toBe('cmd-1');expect('boneName'in value).toBe(false);expect('coordinates'in value).toBe(false)});
 it.each([
  ['emotion',{emotion:'blender_pose'}],['gesture',{gesture:'walk_to_xyz'}],['expression',{expression:'faceMesh'}],['source',{source:'renderer'}],['negative intensity',{intensity:-.1}],['high intensity',{intensity:1.01}],['negative duration',{durationMs:-1}],['oversized duration',{durationMs:120001}],['long speech',{speechText:'x'.repeat(4001)}],['empty command id',{id:''}],
 ] as const)('rejects invalid command: %s',(_label,patch)=>expect(()=>createAvatarCommand({source:'host',...patch} as never,1)).toThrow());
 it('clones metadata so caller mutations cannot change queued commands',()=>{const meta={tags:['product']};const value=cmd({metadata:meta});meta.tags.push('mutated');expect(value.metadata).toEqual({tags:['product']})});
 it('validates commands again at the runtime boundary',()=>expect(()=>validateRuntimeCommand({...cmd(),gesture:'wrong' as never})).toThrow());
 it('rejects an injected Blender field at the runtime boundary',()=>expect(()=>validateRuntimeCommand({...cmd(),boneName:'Spine'} as never)).toThrow());
 it('sorts command priorities and preserves FIFO inside a priority',()=>{const q=new AvatarCommandQueue(8,()=>1000);q.enqueue(cmd({id:'low',priority:'LOW',gesture:'none'}));q.enqueue(cmd({id:'high-a',priority:'HIGH',expression:'smile'}));q.enqueue(cmd({id:'high-b',priority:'HIGH',gesture:'wave'}));expect([q.takeNext()?.id,q.takeNext()?.id,q.takeNext()?.id]).toEqual(['high-a','high-b','low'])});
 it('suppresses duplicate pending semantic work',()=>{const q=new AvatarCommandQueue(32,()=>1000);expect(q.enqueue(cmd({id:'1'}))).toBe(true);expect(q.enqueue(cmd({id:'2'}))).toBe(false)});
 it('bounds queue capacity',()=>{const q=new AvatarCommandQueue(1,()=>1000);expect(q.enqueue(cmd({id:'1',gesture:'none'}))).toBe(true);expect(q.enqueue(cmd({id:'2',gesture:'wave'}))).toBe(false)});
 it('expires stale commands when dequeued',()=>{let now=1000;const q=new AvatarCommandQueue(3,()=>now);q.enqueue(cmd({durationMs:500}));now=1501;expect(q.takeNext()).toBeUndefined()});
 it('cancels a queued command by id',()=>{const q=new AvatarCommandQueue(32,()=>1000);q.enqueue(cmd({id:'a'}));expect(q.cancel('a')).toBe(true);expect(q.size).toBe(0)});
 it('supports clear and emergencyClear latching',()=>{const q=new AvatarCommandQueue(32,()=>1000);q.enqueue(cmd());q.emergencyClear();expect(q.size).toBe(0);expect(q.enqueue(cmd({id:'b'}))).toBe(false);q.resume();expect(q.enqueue(cmd({id:'b'}))).toBe(true)});
 it('connects to the mock runtime',async()=>{const runtime=new MockAvatarRuntimeAdapter();const engine=new AvatarEngine(runtime);await engine.connect();expect(engine.snapshot()).toMatchObject({connected:true,state:'IDLE'})});
 it('rejects connect when runtime is unavailable',async()=>{const runtime=new MockAvatarRuntimeAdapter();runtime.setAvailable(false);const engine=new AvatarEngine(runtime);await expect(engine.connect()).rejects.toThrow(/unavailable/);expect(engine.snapshot().state).toBe('ERROR')});
 it('dispatches host response as semantic avatar command before audio starts',async()=>{const runtime=new MockAvatarRuntimeAdapter();const engine=new AvatarEngine(runtime,{now:()=>1000});await engine.connect();expect(await engine.handleHostResponse(response(),'PRODUCT_INTRO','energetic')).toBe(true);expect(engine.snapshot()).toMatchObject({state:'REACTING',emotion:'excited',expression:'big_smile',gesture:'point_product'});await engine.speechStarted(response().speech);expect(engine.snapshot().state).toBe('SPEAKING')});
 it('does not let host response send commands to a disconnected runtime',async()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());expect(await engine.handleHostResponse(response(),'MANUAL')).toBe(false)});
 it('does not let host response send commands during takeover',async()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());await engine.connect();engine.humanTakeover(true);expect(await engine.handleHostResponse(response(),'MANUAL')).toBe(false);expect(engine.snapshot().state).toBe('HUMAN_TAKEOVER')});
 it('speech start, pause, resume and completion recover state',async()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());await engine.connect();await engine.speechStarted('Halo');expect(engine.snapshot().state).toBe('SPEAKING');engine.speechPaused();expect(engine.snapshot().speechPaused).toBe(true);engine.speechResumed();engine.speechEnded();expect(engine.snapshot()).toMatchObject({state:'IDLE',speechPaused:false})});
 it('speech completion does not stick in speaking while disconnected',()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());engine.speechStarted('Halo');engine.speechEnded();expect(engine.snapshot().state).toBe('STOPPED')});
 it('maps speech failure through safe recovery',async()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());await engine.connect();await engine.speechStarted('Halo');engine.speechEnded(true);expect(engine.snapshot()).toMatchObject({state:'IDLE',lastError:'Speech playback failed'})});
 it('enters and exits full-song music mode only when requested',async()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());await engine.connect();engine.musicStarted(false);expect(engine.snapshot().state).toBe('IDLE');engine.musicStarted(true);expect(engine.snapshot().state).toBe('MUSIC_MODE');engine.musicFinished();expect(engine.snapshot().state).toBe('IDLE')});
 it('human takeover neutralizes semantic controls and blocks commands',async()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());await engine.connect();await engine.testCommand({emotion:'excited',expression:'big_smile',gesture:'celebrate'});engine.humanTakeover(true);expect(engine.snapshot()).toMatchObject({state:'HUMAN_TAKEOVER',emotion:'neutral',expression:'neutral',gesture:'none',humanTakeover:true});expect(await engine.testCommand({gesture:'wave'})).toBe(false)});
 it('return to AI resumes in neutral without an animation command',async()=>{const runtime=new MockAvatarRuntimeAdapter();const engine=new AvatarEngine(runtime);await engine.connect();engine.humanTakeover(true);engine.humanTakeover(false);expect(engine.snapshot()).toMatchObject({state:'IDLE',humanTakeover:false,gesture:'none'})});
 it('emergency stop clears queue and stays stopped until resume',async()=>{const engine=new AvatarEngine(new MockAvatarRuntimeAdapter());await engine.connect();await engine.emergencyStop();expect(engine.snapshot()).toMatchObject({state:'STOPPED',emergencyStopped:true,gesture:'none',queueLength:0});expect(await engine.testCommand({gesture:'wave'})).toBe(false);expect(await engine.resume()).toBe(true);expect(engine.snapshot().state).toBe('IDLE')});
 it('runtime failure reports ERROR and bounded last error',async()=>{const runtime=new MockAvatarRuntimeAdapter();runtime.failWith(new Error('runtime broke'));const engine=new AvatarEngine(runtime);await engine.connect();await engine.testCommand({gesture:'wave'});expect(engine.snapshot().state).toBe('ERROR');expect(engine.snapshot().lastError).toContain('runtime broke')});
 it('emits semantic command and state events',async()=>{const events:string[]=[];const engine=new AvatarEngine(new MockAvatarRuntimeAdapter(),{emit:e=>events.push(e.type)});await engine.connect();await engine.testCommand({gesture:'wave'});expect(events).toContain('AVATAR_COMMAND');expect(events).toContain('AVATAR_STATE_CHANGED')});
 it('disconnects the mock adapter without deleting semantic capabilities',async()=>{const runtime=new MockAvatarRuntimeAdapter();const engine=new AvatarEngine(runtime);await engine.connect();await engine.disconnect();expect(engine.snapshot()).toMatchObject({connected:false,state:'IDLE'})});
 it('produces only coarse speech activity timing, not phoneme guesses',()=>expect(new MockSpeechTimingProvider().getSpeechTiming('testing words',1200,40)).toEqual([{timestampMs:40,durationMs:1200,viseme:'speech',weight:1}]));
 it('returns no timing for empty or invalid duration',()=>{const p=new MockSpeechTimingProvider();expect(p.getSpeechTiming(' ',500)).toEqual([]);expect(p.getSpeechTiming('text',0)).toEqual([])});
 it('inventory lists source assets without writing into the folder',async()=>{const root=process.cwd();const avatar=path.join(root,'Avatar');const before=await Promise.all((await readdir(avatar)).sort().map(async name=>({name,hash:createHash('sha256').update(await readFile(path.join(avatar,name))).digest('hex')})));const text=execFileSync(process.execPath,['scripts/inventory-avatar-assets.mjs'],{cwd:root,encoding:'utf8'});const result=JSON.parse(text) as {assetCount:number;assets:Array<{location:string;possibleRig:string}>};expect(result.assetCount).toBe(7);expect(result.assets.every(x=>x.location.startsWith('Avatar/'))).toBe(true);expect(result.assets.every(x=>x.possibleRig==='NO SUPPORTED MODEL FORMAT')).toBe(true);const after=await Promise.all((await readdir(avatar)).sort().map(async name=>({name,hash:createHash('sha256').update(await readFile(path.join(avatar,name))).digest('hex')})));expect(after).toEqual(before)});
 it('reports unsupported files as unknown rather than claiming compatibility',async()=>{const result=JSON.parse(execFileSync(process.execPath,['scripts/inventory-avatar-assets.mjs'],{cwd:process.cwd(),encoding:'utf8'}));expect(result.assets.every((x:{possibleAnimation:string;possibleBlendshape:string;materialPresence:string})=>x.possibleAnimation==='NO SUPPORTED MODEL FORMAT'&&x.possibleBlendshape==='NO SUPPORTED MODEL FORMAT'&&x.materialPresence==='UNKNOWN')).toBe(true)});
 it('retains explicit source, working, and export boundary labels in inventory output',()=>{const script=execFileSync(process.execPath,['scripts/inventory-avatar-assets.mjs'],{cwd:process.cwd(),encoding:'utf8'});expect(script).toContain('Avatar/WORKING (not created)');expect(script).toContain('Avatar/EXPORT (not created)')});
});
