import {describe,expect,it} from 'vitest';
import {ValidationSessionManager,VALIDATION_CATEGORIES,type ValidationCategory,type ValidationStatus} from '../packages/validation-engine/src/index.js';
import {LiveRuntime,type LiveRuntimePorts,type RuntimeEventName} from '../packages/live-runtime/src/index.js';
import {AvatarEngine,MockAvatarRuntimeAdapter} from '../packages/avatar-engine/src/index.js';
import {BroadcastEngine,MockBroadcastOutputAdapter,renderProduct} from '../packages/broadcast-engine/src/index.js';
import {ProductSchema} from '../packages/product-engine/src/index.js';

function readyFixture(tiktokConfigured=false){const m=new ValidationSessionManager(()=>1700000000000,()=>`validation-${Math.random()}`);m.start();const required:[ValidationCategory,string,ValidationStatus][]=[['suite','AUTOMATED_SUITE','AUTOMATED_PASS'],['typecheck','TYPECHECK','AUTOMATED_PASS'],['build','BUILD','AUTOMATED_PASS'],['audit','NPM_AUDIT','AUTOMATED_PASS'],['audio','AUDIO_SOFTWARE','AUTOMATED_PASS'],['audio','AUDIO_HUMAN','HUMAN_VERIFIED'],['emergency','EMERGENCY_HUMAN','HUMAN_VERIFIED'],['runtime','RUNTIME_E2E','AUTOMATED_PASS'],['broadcast','BROADCAST_PREVIEW','AUTOMATED_PASS']];if(tiktokConfigured)required.push(['tiktok','TIKTOK_OAUTH','HUMAN_VERIFIED']);for(const [category,testId,status]of required)m.record({category,testId,status});return m}

describe('Phase 11 validation session records and false-readiness prevention',()=>{
  let seed=0;const ids=Array.from({length:180},(_,i)=>({i,category:VALIDATION_CATEGORIES[i%VALIDATION_CATEGORIES.length]!,status:(['NOT_TESTED','AUTOMATED_PASS','HUMAN_VERIFIED','FAILED','NOT_AVAILABLE','NOT_CONFIGURED'] as ValidationStatus[])[i%6]!}));
  it.each(ids)('records and restores deterministic category/status case $i',({i,category,status})=>{let now=1000+i;const m=new ValidationSessionManager(()=>now,()=>`id-${++seed}`);const session=m.start();m.record({category,testId:`CASE_${i}`,status,operatorConfirmed:status==='FAILED'});const restored=new ValidationSessionManager(()=>now,()=>`restore-${++seed}`,m.state());expect(restored.active()?.validationSessionId).toBe(session.validationSessionId);expect(restored.latest(category)?.status).toBe(status);expect(restored.active()?.tests.at(-1)?.timestamp).toBe(now)});
  it('starts and completes distinct sessions with stable boundaries',()=>{let t=10;const m=new ValidationSessionManager(()=>t++,()=>`session-${t}`);const first=m.start();m.record({category:'voice',testId:'VOICE_SOFTWARE',status:'AUTOMATED_PASS'});const completed=m.complete();const second=m.start();expect(completed?.completedAt).toBe(12);expect(second.validationSessionId).not.toBe(first.validationSessionId);expect(second.tests).toEqual([])});
  it('auto-starts a session if an observation arrives first',()=>{const m=new ValidationSessionManager(()=>20,()=>`auto-${++seed}`);m.record({category:'audio',testId:'AUDIO_SOFTWARE',status:'AUTOMATED_PASS'});expect(m.active()?.tests).toHaveLength(1)});
  it('keeps operator confirmation separate from automated playback success',()=>{const m=new ValidationSessionManager();m.start();m.record({category:'voice',testId:'VOICE_SOFTWARE',status:'AUTOMATED_PASS'});expect(m.dashboard({tiktokConfigured:false,safeStorage:'UNKNOWN'}).matrix.find(r=>r.subsystem==='Voice')).toMatchObject({automated:'AUTOMATED_PASS',physical:'NOT_TESTED',status:'AUTOMATED_PASS'})});
  it('does not call a human result from NOT_TESTED',()=>{const m=new ValidationSessionManager();m.start();const record=m.record({category:'music',testId:'MUSIC_AUDIBILITY',status:'NOT_TESTED'});expect(record.operatorConfirmed).toBe(false)});
  it('redacts secrets from notes and operator metadata',()=>{const m=new ValidationSessionManager(()=>1,()=>`id-${++seed}`);m.start('Bearer abc access_token=def');m.record({category:'tiktok',testId:'TIKTOK_OAUTH',status:'FAILED',notes:'refresh_token=secret-value client_secret:other-value'});const data=JSON.stringify(m.state());expect(data).not.toContain('abc');expect(data).not.toContain('def');expect(data).not.toContain('secret-value');expect(data).not.toContain('other-value')});
  it('does not persist evidence or credentials unless a safe identifier is supplied',()=>{const m=new ValidationSessionManager();m.record({category:'tiktok',testId:'OAUTH',status:'NOT_TESTED'});const json=JSON.stringify(m.state());expect(json).not.toMatch(/accessToken|refreshToken|clientSecret|authorizationCode|codeVerifier/i)});
  it('marks TikTok OAuth NOT_CONFIGURED when environment credentials are absent',()=>{const m=new ValidationSessionManager();expect(m.dashboard({tiktokConfigured:false,safeStorage:'UNKNOWN'})).toMatchObject({overall:'NOT_READY',tiktokPendingConfiguration:true});expect(m.dashboard({tiktokConfigured:false,safeStorage:'UNKNOWN'}).matrix.find(r=>r.subsystem==='TikTok OAuth')?.status).toBe('NOT_CONFIGURED')});
  it('marks TikTok product capability and sync NOT_AVAILABLE without verified APIs',()=>{const m=new ValidationSessionManager();const d=m.dashboard({tiktokConfigured:false,productCapabilityAvailable:false,safeStorage:'UNKNOWN'});expect(d.matrix.find(r=>r.subsystem==='TikTok Product Capability')?.status).toBe('NOT_AVAILABLE');expect(d.matrix.find(r=>r.subsystem==='Product Sync')?.status).toBe('NOT_AVAILABLE');expect(d.overall).not.toBe('READY_FOR_NEXT_PHASE')});
  it('requires verified TikTok OAuth only when developer credentials are configured',()=>{const m=readyFixture(false);expect(m.dashboard({tiktokConfigured:false,safeStorage:'AVAILABLE'}).overall).toBe('READY_FOR_NEXT_PHASE');expect(readyFixture(true).dashboard({tiktokConfigured:true,safeStorage:'AVAILABLE'}).overall).toBe('READY_FOR_NEXT_PHASE')});
  it('prevents readiness when any required proof is missing',()=>{const m=new ValidationSessionManager();m.start();for(const [category,testId]of [['suite','AUTOMATED_SUITE'],['typecheck','TYPECHECK'],['build','BUILD'],['audit','NPM_AUDIT'],['audio','AUDIO_SOFTWARE'],['audio','AUDIO_HUMAN'],['emergency','EMERGENCY_HUMAN'],['runtime','RUNTIME_E2E']] as const)m.record({category,testId,status:category==='audio'&&testId==='AUDIO_HUMAN'||category==='emergency'?'HUMAN_VERIFIED':'AUTOMATED_PASS'});expect(m.dashboard({tiktokConfigured:false,safeStorage:'AVAILABLE'}).overall).toBe('NOT_READY')});
  it('blocks overall readiness on a critical failed result',()=>{const m=readyFixture();m.record({category:'emergency',testId:'EMERGENCY_HUMAN',status:'FAILED',operatorConfirmed:true});expect(m.dashboard({tiktokConfigured:false,safeStorage:'AVAILABLE'}).overall).toBe('BLOCKED')});
  it('requires human audio confirmation even after software playback passes',()=>{const m=new ValidationSessionManager();m.start();for(const x of [['suite','AUTOMATED_SUITE'],['typecheck','TYPECHECK'],['build','BUILD'],['audit','NPM_AUDIT'],['audio','AUDIO_SOFTWARE'],['emergency','EMERGENCY_HUMAN'],['runtime','RUNTIME_E2E'],['broadcast','BROADCAST_PREVIEW']] as const)m.record({category:x[0],testId:x[1],status:x[0]==='emergency'?'HUMAN_VERIFIED':'AUTOMATED_PASS'});expect(m.dashboard({tiktokConfigured:false,safeStorage:'AVAILABLE'}).overall).toBe('NOT_READY')});
  it('does not treat NOT_AVAILABLE as a pass',()=>{const m=readyFixture();m.record({category:'product',testId:'PRODUCT_SYNC',status:'NOT_AVAILABLE'});expect(m.dashboard({tiktokConfigured:false,safeStorage:'AVAILABLE'}).overall).toBe('READY_FOR_NEXT_PHASE');expect(m.dashboard({tiktokConfigured:false,safeStorage:'AVAILABLE'}).matrix.find(r=>r.subsystem==='Product Sync')?.status).toBe('NOT_AVAILABLE')});
  it('retains device availability without implying physical success',()=>{const m=new ValidationSessionManager();const d=m.dashboard({tiktokConfigured:false,safeStorage:'UNKNOWN',deviceInfo:[{name:'System default',default:true,available:true}]});expect(d.deviceInfo[0]).toMatchObject({available:true,default:true});expect(d.matrix.find(r=>r.subsystem==='Audio')?.physical).toBe('NOT_TESTED')});
  it('preserves UNKNOWN safeStorage and cannot report encrypted storage as available',()=>{const m=new ValidationSessionManager();expect(m.dashboard({tiktokConfigured:false,safeStorage:'UNKNOWN'}).safeStorage).toBe('UNKNOWN');expect(m.dashboard({tiktokConfigured:false,safeStorage:'UNAVAILABLE'}).safeStorage).toBe('UNAVAILABLE')});
  it('bounds persisted history and current-session records',()=>{const m=new ValidationSessionManager(()=>1,()=>`bound-${++seed}`);m.start();for(let i=0;i<520;i++)m.record({category:'ui',testId:'DESKTOP_UI',status:'NOT_TESTED'});expect(m.active()?.tests).toHaveLength(500)});
  it('ignores malformed persisted validation records',()=>{const m=new ValidationSessionManager(()=>1,()=>`valid`,{activeSessionId:'bad',sessions:[{validationSessionId:'bad',startedAt:'now',tests:[{status:'HUMAN_VERIFIED'}]}]});expect(m.active()).toBeNull();expect(m.state().sessions).toEqual([])});
  it('limits returned session history to recent sessions',()=>{let n=0;const m=new ValidationSessionManager(()=>++n,()=>`session-${n}`);for(let i=0;i<12;i++)m.start();expect(m.dashboard({tiktokConfigured:false,safeStorage:'UNKNOWN'}).sessions).toHaveLength(8)});
  it('surfaces all required subsystems in the integration matrix',()=>{const m=new ValidationSessionManager();const names=m.dashboard({tiktokConfigured:false,safeStorage:'UNKNOWN'}).matrix.map(r=>r.subsystem);for(const name of ['Voice','Music','Ducking','Emergency Audio','Desktop UI','Broadcast Preview','Avatar Semantic','Live Runtime','Human Takeover','TikTok OAuth','TikTok Account','TikTok Product Capability','Product Sync'])expect(names).toContain(name)});
  it('stores deterministic NOT_TESTED observations without notes or evidence by default',()=>{const m=new ValidationSessionManager(()=>50,()=>`record-${++seed}`);const record=m.record({category:'broadcast',testId:'BROADCAST_PREVIEW',status:'NOT_TESTED'});expect(record).toMatchObject({status:'NOT_TESTED',timestamp:50,operatorConfirmed:false});expect(record).not.toHaveProperty('evidence');expect(record).not.toHaveProperty('notes')});
});



describe('Phase 11 mocked subsystem integration scenarios',()=>{
  const fixture=()=>ProductSchema.parse({id:'validation-product-001',name:'Produk Uji Pipip',category:'Validation',price:15000,currency:'IDR',promoPrice:null,description:'',benefits:[],specifications:[],variants:[],stock:10,images:[],status:'ACTIVE',sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[],priority:50});
  it('renders the isolated Rp15.000 fixture and preserves UNKNOWN values',()=>{const visual=renderProduct(fixture());expect(visual.formattedPrice).toContain('15.000');expect(visual.stockState).toBe('IN_STOCK');const unknown=renderProduct(ProductSchema.parse({...fixture(),id:'unknown',price:null,currency:null,stock:null}));expect(unknown.formattedPrice).toBeNull();expect(unknown.stockState).toBe('UNKNOWN')});
  it('runs a deterministic runtime/product/speech/avatar/broadcast/music-restore sequence once and in order',async()=>{const avatar=new AvatarEngine(new MockAvatarRuntimeAdapter());await avatar.connect();let speaks=0,selected=0,musicPlays=0,ducked=0,restored=0,now=100;let runtime!:LiveRuntime;const broadcast=new BroadcastEngine(new MockBroadcastOutputAdapter(),id=>id==='validation-product-001'?fixture():null,{now:()=>now++});const ports:LiveRuntimePorts={orchestrator:{start(){},stop(){},pause(){},resume(){},getState(){return null}},voice:{speak:async()=>{speaks++;return{accepted:true}},stop(){},getStatus:()=>({state:'IDLE'})},music:{stop(){},getStatus:()=>({playbackState:'STOPPED'})},playMusic:()=>{musicPlays++;return true},duckMusic:()=>{ducked++},restoreMusic:()=>{restored++},avatar:{humanTakeover(active){avatar.humanTakeover(active)},emergencyStop(){return avatar.emergencyStop()},resume(){return avatar.resume()},command:async()=>true,snapshot:()=>avatar.snapshot()},product:{hasProduct:id=>id==='validation-product-001'},selectProduct:id=>{selected++;return id==='validation-product-001'},onEvent:event=>{void broadcast.observeRuntime(runtime.snapshot())}};runtime=new LiveRuntime(ports,{now:()=>now++,sessionId:()=>`phase11-${now}`});await runtime.startSession();await broadcast.command('startPreview');expect(await runtime.routeAction({type:'PLAY_MUSIC',trackId:'validation-track'})).toBe(true);runtime.observeMusicStarted();expect(await runtime.routeAction({type:'SELECT_PRODUCT',productId:'validation-product-001'})).toBe(true);runtime.observeProductSelected('validation-product-001');expect(await runtime.routeAction({type:'DUCK_MUSIC'})).toBe(true);expect(await runtime.routeAction({type:'SPEAK',text:'Pengujian host lokal',language:'id-ID'})).toBe(true);runtime.observeSpeechStarted();runtime.observeSpeech(true);await avatar.testCommand({gesture:'wave'});runtime.observeAvatar(true);expect(await runtime.routeAction({type:'RESTORE_MUSIC'})).toBe(true);await broadcast.observeProduct('validation-product-001');await broadcast.observeHost('SPEAKING','VALIDATION');const visual=await broadcast.detailedSnapshot();const eventTypes=runtime.events.getHistory().map(e=>e.type);const index=(type:RuntimeEventName)=>eventTypes.indexOf(type);expect(speaks).toBe(1);expect(selected).toBe(1);expect(musicPlays).toBe(1);expect(ducked).toBe(1);expect(restored).toBe(1);expect(eventTypes.filter(type=>type==='SPEECH_STARTED')).toHaveLength(1);expect(index('SESSION_STARTED')).toBeLessThan(index('PRODUCT_SELECTED'));expect(index('PRODUCT_SELECTED')).toBeLessThan(index('SPEECH_STARTED'));expect(index('SPEECH_STARTED')).toBeLessThan(index('SPEECH_COMPLETED'));expect(index('SPEECH_COMPLETED')).toBeLessThan(index('AVATAR_COMMAND_READY'));expect(index('AVATAR_COMMAND_READY')).toBeLessThan(eventTypes.lastIndexOf('ACTION_ROUTED'));expect(visual.render.product?.formattedPrice).toContain('15.000');expect(visual.render.host.state).toBe('SPEAKING')});
  it('keeps human takeover ahead of speech, avatar, and broadcast actions',async()=>{const avatar=new AvatarEngine(new MockAvatarRuntimeAdapter());await avatar.connect();let voiceStops=0;const ports:LiveRuntimePorts={orchestrator:{start(){},stop(){},pause(){},resume(){},getState(){return null}},voice:{speak:async()=>({accepted:true}),stop(){voiceStops++},setHumanTakeover(active){if(active)voiceStops++},getStatus:()=>({state:'IDLE'})},music:{stop(){}},avatar:{humanTakeover(active){avatar.humanTakeover(active)},emergencyStop(){return avatar.emergencyStop()},resume(){return avatar.resume()},command:async()=>true,snapshot:()=>avatar.snapshot()}};const runtime=new LiveRuntime(ports);await runtime.startSession();await runtime.requestHumanTakeover();expect(await runtime.routeAction({type:'SPEAK',text:'Must be blocked'})).toBe(false);expect(await avatar.testCommand({gesture:'wave'})).toBe(false);expect(runtime.snapshot()).toMatchObject({state:'HUMAN_TAKEOVER',humanTakeover:true});expect(voiceStops).toBeGreaterThan(0);await runtime.releaseHumanTakeover();expect(runtime.snapshot().activeActivity).toBe('COOLDOWN')});
  it('latches emergency across voice, music, avatar, and broadcast until explicit reset',async()=>{const avatar=new AvatarEngine(new MockAvatarRuntimeAdapter());await avatar.connect();const broadcast=new BroadcastEngine(new MockBroadcastOutputAdapter(),()=>null);await broadcast.command('startPreview');const ports:LiveRuntimePorts={orchestrator:{start(){},stop(){},pause(){},resume(){},getState(){return null}},voice:{speak:async()=>({accepted:true}),stop(){},emergencyStop(){},resetEmergency(){},getStatus:()=>({state:'IDLE'})},music:{stop(){},getStatus:()=>({playbackState:'STOPPED'})},avatar:{humanTakeover(active){avatar.humanTakeover(active)},emergencyStop(){return avatar.emergencyStop()},resume(){return avatar.resume()},command:async()=>true,snapshot:()=>avatar.snapshot()},onEvent:event=>{void broadcast.observeRuntime(runtime.snapshot())}};const runtime=new LiveRuntime(ports);await runtime.startSession();runtime.setQueueDepth(4);await runtime.emergencyStop();await broadcast.observeRuntime(runtime.snapshot());expect(runtime.snapshot()).toMatchObject({emergencyStopped:true,queueDepth:0});expect(avatar.snapshot()).toMatchObject({emergencyStopped:true,queueLength:0});expect(broadcast.snapshot().render).toMatchObject({emergency:true,scene:{sceneId:'EMERGENCY'},overlays:[]});expect((await runtime.resetAfterEmergency()).state).toBe('STOPPED');expect(runtime.snapshot().emergencyStopped).toBe(false);expect(runtime.snapshot().state).not.toBe('RUNNING')});
});

