import { describe,it,expect } from 'vitest';
import { BroadcastEngine, MockBroadcastOutputAdapter, OverlayQueue, BroadcastWatchdog, SceneManager, renderProduct, formatPrice } from '../packages/broadcast-engine/src/index.js';
import { ProductSchema } from '../packages/product-engine/src/index.js';
import { BroadcastControlSchema } from '../packages/protocol/src/index.js';

const product=(extra:Record<string,unknown>={})=>ProductSchema.parse({id:'p-1',name:'Kopi Pipip',category:'Minuman',price:15000,currency:'IDR',promoPrice:null,description:'',benefits:[],specifications:[],variants:[],stock:null,images:[],status:'ACTIVE',sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[],priority:50,...extra});
describe('Phase 9 deterministic broadcast and output engine',()=>{
 it('formats Indonesian Rupiah without changing values',()=>{expect(formatPrice(15000,'IDR')).toContain('15.000');expect(formatPrice(1500000,'IDR')).toContain('1.500.000');expect(formatPrice(null,'IDR')).toBeNull();expect(formatPrice(100,'bad')).toBeNull()});
 it('renders only Product Engine fields and preserves product name',()=>{const p=product({name:'Brand XYZ® - Original'});const visual=renderProduct(p);expect(visual.name).toBe(p.name);expect(visual.stockState).toBe('UNKNOWN');expect(visual.stock).toBeNull();expect(visual.formattedPrice).toContain('15.000')});
 it('marks stock with verified semantic states',()=>{expect(renderProduct(product({stock:0})).stockState).toBe('OUT_OF_STOCK');expect(renderProduct(product({stock:2})).stockState).toBe('LOW_STOCK');expect(renderProduct(product({stock:20})).stockState).toBe('IN_STOCK')});
 it('distinguishes verified promo from regular price',()=>{const p=renderProduct(product({promoPrice:12000}));expect(p.formattedPromoPrice).toContain('12.000');expect(p.formattedPrice).toContain('15.000')});
 it('strictly validates the narrow renderer control contract',()=>{expect(BroadcastControlSchema.safeParse({action:'startPreview'}).success).toBe(true);expect(BroadcastControlSchema.safeParse({action:'startPreview',html:'<script/>'}).success).toBe(false);expect(BroadcastControlSchema.safeParse({action:'controlTikTok'}).success).toBe(false)});
 it('connects a local preview and renders snapshots',async()=>{const adapter=new MockBroadcastOutputAdapter();const engine=new BroadcastEngine(adapter,id=>id==='p-1'?product():null,{now:()=>1000});const started=await engine.command('startPreview');expect(started.state).toBe('LIVE');expect((await adapter.getState()).connected).toBe(true);expect(adapter.getLastRender()?.status).toBe('LIVE')});
 it('rejects unsupported lifecycle transitions without output mutation',async()=>{const engine=new BroadcastEngine(new MockBroadcastOutputAdapter(),()=>null);await engine.command('stopPreview');expect(engine.getState()).toBe('IDLE')});
 it('reports render error after bounded repeated failures',async()=>{const adapter=new MockBroadcastOutputAdapter();const engine=new BroadcastEngine(adapter,()=>null);await engine.command('startPreview');adapter.failNextRender=true;await engine.command('refresh');adapter.failNextRender=true;await engine.command('refresh');adapter.failNextRender=true;const state=await engine.command('refresh');expect(state.state).toBe('ERROR');expect(state.diagnostics.renderFailures).toBe(3)});
 it('emergency dominates overlays and disconnects the mock output',async()=>{const adapter=new MockBroadcastOutputAdapter();const engine=new BroadcastEngine(adapter,()=>product());await engine.command('startPreview');await engine.observeProduct('p-1');const state=await engine.command('testEmergency');expect(state.state).toBe('EMERGENCY_STOPPED');expect(state.render.emergency).toBe(true);expect(state.render.overlays).toHaveLength(0);expect((await adapter.getState()).connected).toBe(false);expect(engine.enqueue({type:'CTA',priority:10,data:{text:'LIHAT PRODUK'},source:'operator',dismissible:true})).toBe(false)});
 it('human takeover suppresses autonomous overlays and exposes semantic mode',async()=>{const engine=new BroadcastEngine(new MockBroadcastOutputAdapter(),()=>null);await engine.command('startPreview');const s=await engine.command('testHumanTakeover');expect(s.state).toBe('HUMAN_TAKEOVER');expect(s.render.humanTakeover).toBe(true);expect(engine.enqueue({type:'ACTIVITY',priority:1,data:{text:'auto'},source:'runtime',dismissible:true})).toBe(false)});
 it('restores a previously active preview after emergency reset without auto-selecting product',async()=>{const adapter=new MockBroadcastOutputAdapter();const engine=new BroadcastEngine(adapter,()=>null);await engine.command('startPreview');await engine.command('testEmergency');const s=await engine.command('reset');expect(s.state).toBe('LIVE');expect((await adapter.getState()).connected).toBe(true);expect(s.render.product).toBeNull();expect(s.render.emergency).toBe(false)});
 it('does not fabricate music or host test states when runtime data is unknown',async()=>{const engine=new BroadcastEngine(new MockBroadcastOutputAdapter(),()=>null);await engine.command('startPreview');const before=engine.snapshot();const after=await engine.command('testMusic');expect(after.render.music.state).toBe('UNKNOWN');expect(after.render.host.state).toBe(before.render.host.state)});
 it('watchdog classifies render, queue, output, takeover and emergency findings',()=>{const watchdog=new BroadcastWatchdog(2);const health={status:'degraded' as const,output:'disconnected' as const,scene:'DEFAULT',overlayCount:0,queueDepth:30,renderCount:0,renderFailures:3,lastRenderAt:null,timestamp:1};const findings=watchdog.inspect(health,{available:false,emergency:false,humanTakeover:true});expect(findings.map(x=>x.code)).toEqual(['RENDER_FAILURES','QUEUE_GROWTH','OUTPUT_UNAVAILABLE','HUMAN_TAKEOVER']);expect(watchdog.inspect(health,{available:false,emergency:true,humanTakeover:false}).at(-1)?.code).toBe('EMERGENCY_ACTIVE');expect(watchdog.canRecover()).toBe(true);expect(watchdog.canRecover()).toBe(true);expect(watchdog.canRecover()).toBe(false);watchdog.reset();expect(watchdog.attempts).toBe(0)});
 it('restores the previous semantic scene after a priority override',()=>{const scenes=new SceneManager(()=>20);scenes.activate('PRODUCT');expect(scenes.activate('HUMAN_TAKEOVER')).toBe(true);expect(scenes.activate('MUSIC')).toBe(false);expect(scenes.restore()).toBe('PRODUCT');expect(scenes.currentScene().sceneId).toBe('PRODUCT')});
 it('expires overlays using an injected clock',()=>{let now=0;const queue=new OverlayQueue(()=>now,2);const o={id:'x',type:'CTA' as const,priority:1,visible:true,createdAt:0,expiresAt:10,data:{text:'CTA'},source:'test',dismissible:true};expect(queue.enqueue(o)).toBe(true);now=10;expect(queue.depth).toBe(0)});
 it('suppresses duplicates, supports pause/resume/cancel/clear, and bounds the queue',()=>{const queue=new OverlayQueue(()=>0,2);const overlay=(id:string,priority:number)=>({id,type:'CTA' as const,priority,visible:true,createdAt:0,expiresAt:null,data:{},source:'test',dismissible:true});expect(queue.enqueue(overlay('a',2))).toBe(true);expect(queue.enqueue(overlay('a',1))).toBe(false);expect(queue.enqueue(overlay('b',1))).toBe(true);expect(queue.enqueue(overlay('c',0))).toBe(false);expect(queue.take()?.id).toBe('a');queue.pause();expect(queue.take()).toBeNull();queue.resume();expect(queue.cancel('b')).toBe(true);expect(queue.clear()).toBe(0)});
 const phaseNineCases=Array.from({length:150},(_,i)=>i+1);
 it.each(phaseNineCases)('deterministic scenario %i: bounded semantic overlay survives validated lifecycle',async scenario=>{let now=scenario*100;const adapter=new MockBroadcastOutputAdapter();const engine=new BroadcastEngine(adapter,id=>id==='p-1'?product({stock:scenario%4===0?null:scenario%4===1?0:scenario%4===2?3:12,price:scenario*100}):null,{now:()=>now,maxOverlays:4,maxQueue:4,defaultOverlayTtlMs:1000});const first=await engine.command('startPreview');expect(first.state).toBe('LIVE');expect(first.health.output).toBe('connected');expect(engine.enqueue({type:'CTA',priority:scenario%50,data:{text:'LIHAT PRODUK'},source:'operator',dismissible:true})).toBe(true);const rendered=await engine.command('refresh');expect(rendered.health.overlayCount).toBeGreaterThanOrEqual(1);expect(rendered.render.overlays.every(item=>typeof item.data.text==='string')).toBe(true);expect(rendered.render.emergency).toBe(false);now+=1001;const expired=await engine.command('refresh');expect(expired.render.overlays).toHaveLength(0);expect((await engine.command('stopPreview')).state).toBe('STOPPED')});
});
