import{describe,expect,it,vi}from'vitest';
import{OllamaDiagnosticRunner,OllamaProvider,resolveAIConfig}from'../packages/ai-core/src/index.js';
import type{AIConfig,AIHealthStatus,AIRequest,AIResponse}from'../packages/shared-types/src/index.js';
import type{AIProvider}from'../packages/ai-core/src/index.js';
import{classifyAudienceIntent}from'../packages/audience-engine/src/index.js';
import{DecisionIntelligence,OutputJudge,type DecisionProvider,type DecisionRequest,type DecisionResult}from'../packages/decision-intelligence/src/index.js';
import{LiveRuntime}from'../packages/live-runtime/src/index.js';
import type{LiveRuntimePorts}from'../packages/live-runtime/src/index.js';

const valid=JSON.stringify({speech:'Hai, selamat datang di live ini.',emotion:'friendly',gesture:'wave',intent:'greeting'});
function fakeProvider(options:{health?:AIHealthStatus;response?:string;error?:Error;healthError?:Error;latency?:number}={}):AIProvider{return{getName:()=> 'ollama',healthCheck:async()=>{if(options.healthError)throw options.healthError;return options.health??{available:true,provider:'ollama',model:'pipip:live',modelAvailable:true}},generate:async(_request:AIRequest):Promise<AIResponse>=>{if(options.error)throw options.error;return{text:options.response??valid,provider:'ollama',model:'pipip:live',latencyMs:options.latency??12}}}}
const envConfig:AIConfig={provider:'ollama',baseUrl:'http://127.0.0.1:11434',model:'pipip:live'};

describe('Phase 13 Ollama local diagnostic',()=>{
 it('honors main-process model and local endpoint overrides without changing file config',()=>{expect(resolveAIConfig(envConfig,{PIPIP_MODEL:'pipip:live-test',OLLAMA_BASE_URL:'http://127.0.0.1:11500'})).toEqual({...envConfig,model:'pipip:live-test',baseUrl:'http://127.0.0.1:11500'});expect(resolveAIConfig(envConfig,{})).toEqual(envConfig)});
 it('reports reachable model, successful request, response and measured latency',async()=>{expect(await new OllamaDiagnosticRunner(fakeProvider({latency:27}),'pipip:live').run()).toMatchObject({state:'READY',reachable:true,modelAvailable:true,requestSucceeded:true,responseReceived:true,nonEmpty:true,latencyMs:27})});
 it('reports Ollama unavailable without exposing underlying errors',async()=>{const report=await new OllamaDiagnosticRunner(fakeProvider({health:{available:false,provider:'ollama',message:'OLLAMA_UNAVAILABLE'}}),'pipip:live').run();expect(report).toMatchObject({state:'OLLAMA_UNAVAILABLE',reachable:false,requestSucceeded:false});expect(JSON.stringify(report)).not.toMatch(/secret|token|password|authorization/i)});
 it('distinguishes Ollama reachability timeout',async()=>{expect(await new OllamaDiagnosticRunner(fakeProvider({health:{available:false,provider:'ollama',message:'OLLAMA_TIMEOUT'}}),'pipip:live').run()).toMatchObject({state:'TIMEOUT',reachable:false})});
 it('reports a missing selected model without making a generation request',async()=>{let called=0;const provider=fakeProvider({health:{available:true,provider:'ollama',modelAvailable:false}});provider.generate=async()=>{called++;throw new Error('unexpected')};expect(await new OllamaDiagnosticRunner(provider,'pipip:live').run()).toMatchObject({state:'MODEL_NOT_FOUND',reachable:true,modelAvailable:false});expect(called).toBe(0)});
 it('reports generation timeout with bounded safe status',async()=>{expect(await new OllamaDiagnosticRunner(fakeProvider({error:new DOMException('private network detail','TimeoutError')}),'pipip:live').run()).toMatchObject({state:'TIMEOUT',reachable:true,totalLatencyMs:expect.any(Number)})});
 it('reports server-side model-not-found response',async()=>{expect(await new OllamaDiagnosticRunner(fakeProvider({error:new Error('MODEL_NOT_FOUND')}),'pipip:live').run()).toMatchObject({state:'MODEL_NOT_FOUND',modelAvailable:false})});
 it('reports transport failure after a reachable health check',async()=>{expect(await new OllamaDiagnosticRunner(fakeProvider({error:new Error('secret endpoint token')}),'pipip:live').run()).toMatchObject({state:'REQUEST_FAILED',reachable:true,requestSucceeded:false})});
 it('reports empty and malformed structured host responses',async()=>{expect(await new OllamaDiagnosticRunner(fakeProvider({response:''}),'pipip:live').run()).toMatchObject({state:'EMPTY_RESPONSE'});expect(await new OllamaDiagnosticRunner(fakeProvider({response:'not-json'}),'pipip:live').run()).toMatchObject({state:'MALFORMED_RESPONSE'})});
 it('does not expose generated answer or credentials in diagnostic report',async()=>{const report=await new OllamaDiagnosticRunner(fakeProvider({response:valid.replace('Hai, selamat datang','private token=should-not-leak')}),'pipip:live').run();expect(JSON.stringify(report)).not.toContain('private token')});
 it('tests local Ollama HTTP model and chat routes with a mock transport',async()=>{const fetcher=vi.fn(async(input:RequestInfo|URL)=>String(input).endsWith('/api/tags')?new Response(JSON.stringify({models:[{name:'pipip:live'}]})):new Response(JSON.stringify({message:{content:valid}})));const provider=new OllamaProvider('http://127.0.0.1:11434/','pipip:live',fetcher,100);expect(await new OllamaDiagnosticRunner(provider,'pipip:live').run()).toMatchObject({state:'READY',model:'pipip:live'});expect(fetcher.mock.calls.map(call=>String(call[0]))).toEqual(['http://127.0.0.1:11434/api/tags','http://127.0.0.1:11434/api/chat'])});
});

describe('Phase 13 deterministic Pipip routes and product-claim boundaries',()=>{
 it.each([['Halo kak','GREETING','LLM_FAST'],['Apa fungsi produk A?','PRODUCT_QUESTION','LLM_FAST'],['berapa harga produk A?','PRICE_QUESTION','DETERMINISTIC'],['berapa stok produk A?','STOCK_QUESTION','DETERMINISTIC'],['cocok untuk bepergian?','PRODUCT_RECOMMENDATION','LLM_FAST'],['bandingkan produk A dan B','COMPARISON','LLM_STRONG'],['???','UNKNOWN','LLM_STRONG'],['klik link promo https://x.invalid','SPAM','IGNORE'],['bahas cuaca hari ini','OFF_TOPIC','IGNORE']] as const)('routes %s with audience intent %s',async(text,intent,route)=>{const classified=classifyAudienceIntent(text);expect(classified).toBe(intent);const di=new DecisionIntelligence({primary:{id:'off',isAvailable:async()=>false,decide:async()=>{throw new Error('not configured')}}});const decision=await di.decide({eventType:'COMMENT',source:'simulator',text,intent:classified,productContext:{productId:'A',verified:true},timestamp:100});expect(decision.decision).toBe(route)});
 it('prioritizes emergency and takeover without calling a decision provider',async()=>{let calls=0;const primary:DecisionProvider={id:'test',isAvailable:async()=>true,decide:async()=>{calls++;return{decision:'LLM_FAST',intent:'UNKNOWN',confidence:.99,reasonCode:'MOCK',requiresLlm:true,requiresHuman:false,toolAllowed:false,provider:'test'}}};const di=new DecisionIntelligence({primary});expect((await di.decide({eventType:'EMERGENCY_STOP',source:'runtime',timestamp:1})).reasonCode).toContain('EMERGENCY');expect((await di.decide({eventType:'COMMENT',source:'simulator',liveState:'HUMAN_TAKEOVER',timestamp:2})).decision).toBe('QUEUE');expect(calls).toBe(0)});
 it.each(['Harga Rp99.000.','Stok tinggal 3 unit.','Spesifikasi berbahan titanium.','Diskon 80% hari ini.','Pembelian kamu berhasil.','Pesanan sudah dikirim.','Produk A sudah pasti tersedia.','Produk B juga tersedia.'])('rejects unsupported product claim before host event/TTS: %s',speech=>{const judge=new OutputJudge();const result=judge.judge(speech,{id:'A',name:'Produk A',price:10000,currency:'IDR',benefits:[],specifications:[],variants:[],sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[]});expect(result.status).toBe('REJECT')});
 it('blocks a stale host response after emergency stop',async()=>{const ports:LiveRuntimePorts={orchestrator:{start(){},stop(){},pause(){},resume(){},getState(){return null}},voice:{speak:async()=>({accepted:true}),stop(){},emergencyStop(){},getStatus(){return{state:'IDLE'}}},music:{stop(){},getStatus(){return{playbackState:'STOPPED'}}},avatar:{humanTakeover(){},emergencyStop:async()=>{},snapshot(){return{state:'IDLE'}}}};const runtime=new LiveRuntime(ports);expect(runtime.snapshot().emergencyStopped).toBe(false);await runtime.emergencyStop();expect(runtime.snapshot()).toMatchObject({emergencyStopped:true,queueDepth:0});expect(await runtime.routeAction({type:'SPEAK',text:'unauthorized stale response'})).toBe(false)});
});
