import {describe,expect,it} from 'vitest';
import {LiveRehearsalEngine,REHEARSAL_SCENARIOS,parseRehearsalScenario,type RehearsalFailure,type RehearsalScenario} from '../packages/live-rehearsal/src/index.js';
import {OutputJudge} from '../packages/decision-intelligence/src/index.js';
import {VirtualClock} from '../packages/live-rehearsal/src/index.js';

const adversarialProductClaims=Array.from({length:250},(_,index)=>{const value=101+Math.floor(index/5);const kind=index%5;const speech=kind===0?`Produk Mug berharga Rp${100_000+value}.`:kind===1?`Stok Produk Mug tersedia ${value} unit.`:kind===2?`Produk Mug berkapasitas ${value} ml.`:kind===3?`Diskon Produk Mug sebesar ${value}%.`:`Pembelian Produk Mug berhasil, pesanan nomor ${value}.`;return{index,speech}});

describe('Phase 14 deterministic live rehearsal',()=>{
  it('ships eighteen validated structured scenarios with ordered virtual events',()=>{expect(REHEARSAL_SCENARIOS).toHaveLength(18);for(const scenario of REHEARSAL_SCENARIOS)expect(parseRehearsalScenario(scenario)).toEqual(scenario);expect(REHEARSAL_SCENARIOS.map(x=>x.id)).toContain('long-mixed-session')});
  it('advances, resets, rejects negative time, and reproduces timestamps with the virtual clock',()=>{const clock=new VirtualClock(1000);expect(clock.now()).toBe(1000);expect(clock.advance(250)).toBe(1250);expect(clock.advanceTo(2000)).toBe(2000);expect(()=>clock.advance(-1)).toThrow();expect(()=>clock.advanceTo(1999)).toThrow();clock.reset(5000);expect(clock.now()).toBe(5000);expect(clock.advance(0)).toBe(5000)});
  it('rejects unordered, out-of-range, and untyped scenario data',()=>{expect(()=>parseRehearsalScenario({id:'bad',name:'bad',durationMs:100,events:[{atMs:20,type:'COMMENT',text:'ok'},{atMs:10,type:'SESSION_END'}]})).toThrow();expect(()=>parseRehearsalScenario({id:'bad',name:'bad',durationMs:10,events:[{atMs:11,type:'SESSION_END'}]})).toThrow();expect(()=>parseRehearsalScenario({id:'bad',name:'bad',durationMs:10,events:[{atMs:1,type:'COMMENT'}]})).toThrow()});
  it('runs the basic session reproducibly through audience, decision, knowledge, product, judge, TTS, music, avatar, runtime, and local broadcast',async()=>{const engine=new LiveRehearsalEngine();const first=await engine.run('basic-sales-session');const second=await engine.run('basic-sales-session');expect(first).toEqual(second);expect(first).toMatchObject({simulation:'SIMULATION',audienceSource:'simulator',tiktokState:'NOT_CONFIGURED',finalState:'STOPPED'});expect(first.decisions.length).toBeGreaterThan(4);expect(first.knowledge.length).toBe(first.decisions.length);expect(first.productValidation.some(x=>x.verified)).toBe(true);expect(first.responses.some(x=>/Rp\s*45[.,]?000/iu.test(x.text))).toBe(true);expect(first.responses.some(x=>/12\s*(?:unit|pcs|buah)/iu.test(x.text))).toBe(true);expect(first.outputJudge.every(x=>x.status==='PASS'||!x.speechReachedTts)).toBe(true);expect(first.invariants.every(x=>x.passed)).toBe(true);expect(first.toolExecutions).toBe(0)});
  it('keeps non-comment social events synthetic and routes them through existing engines without counting them as accepted comments',async()=>{const r=await new LiveRehearsalEngine().run('mixed-live-session');for(const type of ['FOLLOW','LIKE','GIFT','SYSTEM']){const eventIndex=r.events.findIndex(e=>e.type===type);expect(eventIndex).toBeGreaterThanOrEqual(0);const eventId=`mixed-live-session-${eventIndex}`;expect(r.decisions.some(d=>d.eventId===eventId)).toBe(true);expect(r.audienceSource).toBe('simulator')}expect(r.toolExecutions).toBe(0)});
  it('ducks virtual music during accepted speech and restores it afterward',async()=>{const r=await new LiveRehearsalEngine().run('music-session');const duck=r.music.find(x=>x.action==='MUSIC_DUCK');const restore=r.music.find(x=>x.action==='MUSIC_RESTORE');expect(duck).toMatchObject({state:'PLAYING',ducked:true});expect(duck!.musicLevel).toBeLessThan(.58);expect(restore).toMatchObject({ducked:false});expect(r.tts.some(x=>x.status==='READY')).toBe(true)});
  it('routes dead-air scheduling to the existing Show Director',async()=>{const r=await new LiveRehearsalEngine().run('dead-air-session');expect(r.showActions).toHaveLength(2);expect(r.showActions.every(x=>x.action.length>0&&x.reason.length>0)).toBe(true)});
  it('runs all eighteen built-in scenarios with passing invariants in deterministic mock mode',async()=>{const reports=await new LiveRehearsalEngine().runAll('MOCK');expect(reports).toHaveLength(18);for(const report of reports){expect(report.simulation,report.scenarioId).toBe('SIMULATION');expect(report.invariants.every(x=>x.passed),`${report.scenarioId}: ${report.invariants.filter(x=>!x.passed).map(x=>x.id).join(', ')}`).toBe(true);expect(report.observations.length).toBe(report.eventCount);expect(report.decisions.every(d=>Boolean(d.reasonCode))).toBe(true)}});
  it('keeps price and stock unknown when the product row is absent or unavailable',async()=>{const engine=new LiveRehearsalEngine();for(const id of ['product-question-session','product-data-failure-session']){const r=await engine.run(id);expect(r.invariants.filter(x=>x.id.startsWith('unknown-')).every(x=>x.passed)).toBe(true);expect(r.responses.some(x=>/Rp\s*\d|\b\d+\s*(?:unit|pcs|buah)\b/iu.test(x.text))).toBe(false)}});
  it('never sends injected rejected or fail-closed outputs to TTS',async()=>{const scenario:RehearsalScenario={id:'reject-before-tts',name:'Reject Before TTS',durationMs:10_000,events:[{atMs:0,type:'LIVE_START'},{atMs:1,type:'FAILURE',failure:'OUTPUT_JUDGE_FAILURE'},{atMs:2,type:'COMMENT',text:'Kak harga Produk Mug berapa?',productId:'fixture-mug'},{atMs:10_000,type:'SESSION_END'}]};const r=await new LiveRehearsalEngine().runDefinition(scenario);expect(r.outputJudge.some(x=>x.status==='FAIL_CLOSED'&&!x.speechReachedTts)).toBe(true);expect(r.tts.every(x=>x.status==='REJECTED')).toBe(true);expect(r.tts.some(x=>x.status==='READY')).toBe(false);expect(r.invariants.find(x=>x.id==='rejected-output-never-reaches-tts')?.passed).toBe(true)});
  it('tests unsupported generated price, stock, specification, promotion, purchase, order, and product claims',()=>{const judge=new OutputJudge();const product={id:'fixture-mug',name:'Produk Mug',price:45000,currency:'IDR',stock:12,benefits:['Mudah dibawa'],specifications:['Kapasitas 350 ml'],variants:['Hitam'],sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[]};for(const speech of ['Harga Rp99.000.','Stok tersedia 99 unit.','Berbahan titanium.','Diskon 90%.','Pembelian berhasil.','Pesanan sudah dikirim.','Produk Fiktif sudah tersedia.'])expect(judge.judge(speech,product).status,speech).toBe('REJECT')});
  it.each(adversarialProductClaims)('rejects adversarial generated product claim %#',({speech})=>{const judge=new OutputJudge();const product={id:'fixture-mug',name:'Produk Mug',price:45000,currency:'IDR',stock:12,benefits:['Mudah dibawa'],specifications:['Kapasitas 350 ml'],variants:['Hitam'],sellingPoints:[],targetAudience:[],preferredTalkingPoints:[],forbiddenClaims:[]};expect(judge.judge(speech,product).status,speech).toBe('REJECT')});
  it('simulates takeover queue cancellation, blocks host actions, resumes in cooldown, and marks every audience event as synthetic',async()=>{const r=await new LiveRehearsalEngine().run('human-takeover-session');expect(r.takeovers.map(x=>x.action)).toEqual(['TAKEOVER','RETURN_WITH_COOLDOWN']);expect(r.invariants.find(x=>x.id==='takeover-clears-queued-actions')?.passed).toBe(true);expect(r.showActions.some(x=>x.reason==='takeover_resume_cooldown')).toBe(true);expect(r.audienceSource).toBe('simulator');expect(r.invariants.every(x=>x.passed)).toBe(true)});
  it('runs emergency stop from all eight requested origins and requires reset',async()=>{const engine=new LiveRehearsalEngine();const sources=['IDLE','PREPARING','SPEAKING','MUSIC','QUEUE','PRODUCT_RESPONSE','AVATAR_COMMAND','HUMAN_TAKEOVER'] as const;for(const fromState of sources){const events=fromState==='IDLE'?[{atMs:1,type:'EMERGENCY_STOP' as const,fromState}]:[{atMs:0,type:'LIVE_START' as const},{atMs:1,type:'EMERGENCY_STOP' as const,fromState}];const r=await engine.runDefinition({id:`emergency-${fromState.toLowerCase()}`,name:`Emergency from ${fromState}`,durationMs:1000,events});expect(r.emergencies[0]).toMatchObject({fromState,stopped:true,resetRequired:true});expect(r.finalState).toBe('EMERGENCY_STOPPED');expect(r.invariants.every(x=>x.passed)).toBe(true)}});
  it('injects each deterministic subsystem failure and returns a safe report',async()=>{const engine=new LiveRehearsalEngine();const cases:Array<{failure:RehearsalFailure;after:RehearsalScenario['events'][number][]}>=[{failure:'OLLAMA_TIMEOUT',after:[{atMs:2,type:'COMMENT',text:'Apa manfaat Produk Mug?',productId:'fixture-mug'}]},{failure:'OLLAMA_UNAVAILABLE',after:[{atMs:2,type:'COMMENT',text:'Apa manfaat Produk Mug?',productId:'fixture-mug'}]},{failure:'MALFORMED_LLM_OUTPUT',after:[{atMs:2,type:'COMMENT',text:'Apa manfaat Produk Mug?',productId:'fixture-mug'}]},{failure:'PRODUCT_ENGINE_FAILURE',after:[{atMs:2,type:'COMMENT',text:'Kak ini harganya berapa?',productId:'fixture-mug'}]},{failure:'TTS_FAILURE',after:[{atMs:2,type:'COMMENT',text:'Hai Pipip.'}]},{failure:'MUSIC_FAILURE',after:[{atMs:2,type:'MUSIC_START'}]},{failure:'AVATAR_FAILURE',after:[{atMs:2,type:'COMMENT',text:'Hai Pipip.'}]},{failure:'JEV_FAILURE',after:[{atMs:2,type:'COMMENT',text:'Apa manfaat Produk Mug?',productId:'fixture-mug'}]},{failure:'OUTPUT_JUDGE_FAILURE',after:[{atMs:2,type:'COMMENT',text:'Kak ini harganya berapa?',productId:'fixture-mug'}]},{failure:'RUNTIME_FAILURE',after:[{atMs:2,type:'COMMENT',text:'Hai Pipip.'}]}];for(const [i,item] of cases.entries()){const r=await engine.runDefinition({id:`failure-${i}`,name:item.failure,durationMs:1000,events:[{atMs:0,type:'LIVE_START'},{atMs:1,type:'FAILURE',failure:item.failure},...item.after,{atMs:1000,type:'SESSION_END'}]},'REAL_OLLAMA');expect(r.errors.some(x=>x.code===item.failure),item.failure).toBe(true);expect(r.simulation).toBe('SIMULATION');expect(r.toolExecutions).toBe(0);expect(r.invariants.every(x=>x.passed),item.failure).toBe(true)}});
  it('runs 31 simulated minutes and 1,000+ events without real waiting or unbounded logs',async()=>{const r=await new LiveRehearsalEngine({maxRecords:1100}).run('long-mixed-session');expect(r.durationMs).toBe(1_860_000);expect(r.eventCount).toBeGreaterThan(1000);expect(r.events.length).toBe(r.eventCount);expect(r.decisions.length).toBeGreaterThan(500);expect(r.responses.length).toBeLessThanOrEqual(1000);expect(r.ignoredEvents).toBeGreaterThan(0);expect(r.finalState).toBe('STOPPED');expect(r.invariants.every(x=>x.passed)).toBe(true)});
  it('supports deterministic mock host output without an external request',async()=>{const r=await new LiveRehearsalEngine({mode:'MOCK_LLM'}).run('basic-sales-session');expect(r.mode).toBe('MOCK_LLM');expect(r.llmCalls).toBeGreaterThan(0);expect(r.decisions.every(d=>d.latencyMs===0)).toBe(true)});
  it('clears a completed report without changing the rehearsal controls',async()=>{const engine=new LiveRehearsalEngine();await engine.run('basic-sales-session');expect(engine.snapshot().report).not.toBeNull();expect(engine.clearReport()).toMatchObject({running:false,scenarioId:'basic-sales-session',report:null,errors:0,invariantFailures:0})});
});
