import {describe,expect,it,vi} from 'vitest';
import {createHash} from 'node:crypto';
import {TikTokConnectorConfigSchema,readTikTokConfig,buildAuthorizationUrl,createPkce,AuthorizationStateManager,PermissionManager,EncryptedCredentialStore,validStoredCredentials,TikTokApiClient,apiError,redactSecrets,RequestPolicy,TikTokConnector,LoopbackCallbackServer} from '../packages/tiktok-connector/src/index.js';
import type {StoredTikTokCredentials} from '../packages/tiktok-connector/src/index.js';

const validConfig={clientKey:'client-key',clientSecret:'secret-do-not-print',redirectUri:'http://127.0.0.1:43219/callback/',scopes:['user.info.basic'],authorizationTimeoutMs:30_000,requestTimeoutMs:2_000};
const credential:StoredTikTokCredentials={connectionId:'connection-1',accessToken:'access-secret',refreshToken:'refresh-secret',accessExpiresAt:1_900_000_000_000,refreshExpiresAt:1_900_000_000_000,openId:'open-id-1',grantedScopes:['user.info.basic'],connectedAt:1_700_000_000_000,displayName:'Pipip',avatarUrl:null};

// 200 deterministic cases exercise independent encoded client keys and scope values.
describe('Phase 10 deterministic authorization URL cases',()=>{
  const cases=Array.from({length:200},(_,i)=>({i,key:`client ${i}&x`,scope:`scope_${i}`}));
  it.each(cases)('encodes OAuth values and includes only documented parameters (#$i)',({i,key,scope})=>{
    const url=new URL(buildAuthorizationUrl({clientKey:key,redirectUri:validConfig.redirectUri!,scopes:['user.info.basic',scope],state:`state-${i}`,codeChallenge:`challenge-${i}`}));
    expect(url.origin+url.pathname).toBe('https://www.tiktok.com/v2/auth/authorize/');
    expect([...url.searchParams.keys()].sort()).toEqual(['client_key','code_challenge','code_challenge_method','redirect_uri','response_type','scope','state'].sort());
    expect(url.searchParams.get('client_key')).toBe(key);
    expect(url.searchParams.get('scope')).toBe(`user.info.basic,${scope}`);
    expect(url.searchParams.get('response_type')).toBe('code');
    expect(url.searchParams.get('code_challenge_method')).toBe('S256');
  });
});

describe('Phase 10 validation, PKCE, state, storage, permissions, API and safety',()=>{
  it('accepts configured loopback and minimum profile scope',()=>expect(TikTokConnectorConfigSchema.parse(validConfig).scopes).toEqual(['user.info.basic']));
  it.each(['http://0.0.0.0:80/callback/','http://192.168.1.4:80/callback/','http://127.0.0.1/callback/','http://localhost:22/callback/?x=1','http://localhost:22/other/','https://localhost:443/callback/'])('rejects unsafe or unregistered redirect URI %s',(redirectUri)=>expect(()=>TikTokConnectorConfigSchema.parse({...validConfig,redirectUri})).toThrow());
  it('uses explicit configured scopes and defaults to basic identity only',()=>{expect(readTikTokConfig({TIKTOK_SCOPES:'user.info.basic'}).scopes).toEqual(['user.info.basic']);expect(readTikTokConfig({}).scopes).toEqual(['user.info.basic'])});
  it('generates PKCE S256 with documented SHA-256 hexadecimal challenge',()=>{const pkce=createPkce();expect(pkce.verifier).toMatch(/^[A-Za-z0-9_-]{43,128}$/);expect(pkce.challenge).toBe(createHash('sha256').update(pkce.verifier,'ascii').digest('hex'));expect(pkce.method).toBe('S256')});
  it('consumes OAuth state only once and rejects a mismatch',()=>{const m=new AuthorizationStateManager(()=>10);const pending=m.create(validConfig.redirectUri!,validConfig.scopes);expect(m.consume(pending.state).consumed).toBe(true);expect(()=>m.consume(pending.state)).toThrow('STATE_MISMATCH')});
  it('rejects missing, wrong and expired OAuth state',()=>{let now=0;const m=new AuthorizationStateManager(()=>now,50);const p=m.create(validConfig.redirectUri!,validConfig.scopes);expect(()=>m.consume('')).toThrow();expect(()=>m.consume('wrong')).toThrow();now=51;expect(()=>m.consume(p.state)).toThrow()});
  it('deduplicates explicitly granted scopes and reports missing scopes',()=>{const p=new PermissionManager(['user.info.basic','video.list']);p.setGranted(['user.info.basic','user.info.basic']);expect(p.getGrantedScopes()).toEqual(['user.info.basic']);expect(p.getMissingScopes()).toEqual(['video.list']);expect(p.getState()).toBe('PARTIALLY_AUTHORIZED')});
  it('distinguishes an empty grant from a full grant',()=>{const p=new PermissionManager(['user.info.basic']);p.setGranted([]);expect(p.getState()).toBe('USER_NOT_AUTHORIZED');p.setGranted(['user.info.basic']);expect(p.getState()).toBe('AUTHORIZED')});
  it('validates credential records before secure persistence',()=>{expect(validStoredCredentials(credential)).toBe(true);expect(validStoredCredentials({...credential,refreshToken:''})).toBe(false)});
  it('encrypts credentials and never writes a plaintext JSON token file',async()=>{let bytes=new Uint8Array();const encryption={available:()=>true,encrypt:(s:string)=>new TextEncoder().encode(Buffer.from(s).toString('base64')),decrypt:(b:Uint8Array)=>Buffer.from(new TextDecoder().decode(b),'base64').toString('utf8')};const file={read:async()=>bytes,writeAtomic:async(b:Uint8Array)=>{bytes=b},remove:async()=>{bytes=new Uint8Array()}};const store=new EncryptedCredentialStore(encryption,file);await store.write(credential);expect(new TextDecoder().decode(bytes)).not.toContain('refresh-secret');expect(new TextDecoder().decode(bytes)).not.toContain('refresh-secret');expect(await store.read()).toEqual(credential);await store.clear();expect(await store.read()).toBeNull()});
  it('refuses secure writes when platform encryption is unavailable',async()=>{const store=new EncryptedCredentialStore({available:()=>false,encrypt:()=>new Uint8Array(),decrypt:()=>''},{read:async()=>null,writeAtomic:async()=>{},remove:async()=>{}});expect(store.isAvailable()).toBe(false);await expect(store.write(credential)).rejects.toThrow('SECURE_STORAGE_UNAVAILABLE')});
  it('maps safe API errors without including secret inputs',()=>{const e=apiError('RATE_LIMITED','user-info',1200);expect(e.detail).toMatchObject({code:'RATE_LIMITED',retryAfterMs:1200,recoverable:true});expect(e.message).not.toContain('secret')});
  it('redacts OAuth credentials and normalizes callback error codes',()=>{const value=redactSecrets({access_token:'abc',refresh_token:'def',client_secret:'ghi',code_verifier:'xyz'});const text=JSON.stringify(value);expect(text).not.toContain('abc');expect(text).not.toContain('def');expect(text).not.toContain('ghi');expect(text).not.toContain('xyz')});
  it('validates official token response and exchanges through the official v2 endpoint',async()=>{const fetcher=vi.fn(async(url:string,init?:RequestInit)=>{expect(url).toBe('https://open.tiktokapis.com/v2/oauth/token/');expect(init?.method).toBe('POST');return new Response(JSON.stringify({access_token:'a',expires_in:3600,open_id:'o',refresh_token:'r',refresh_expires_in:7200,scope:'user.info.basic',token_type:'Bearer'}),{status:200})});const api=new TikTokApiClient({clientKey:'k',clientSecret:'s',redirectUri:validConfig.redirectUri!,requestTimeoutMs:1000},fetcher as typeof fetch);const result=await api.exchangeCode('code','v'.repeat(43));expect(result.open_id).toBe('o');expect(String(fetcher.mock.calls[0]?.[1]?.body)).toContain('code_verifier=')});
  it('rejects malformed token responses',async()=>{const api=new TikTokApiClient({clientKey:'k',clientSecret:'s',redirectUri:validConfig.redirectUri!,requestTimeoutMs:1000},(async()=>new Response('{"access_token":"only"}',{status:200})) as typeof fetch);await expect(api.refresh('r')).rejects.toMatchObject({detail:{code:'INVALID_RESPONSE'}})});
  it('validates profile response and only requests approved identity fields',async()=>{const f=vi.fn(async(url:string,init?:RequestInit)=>{expect(url).toContain('/v2/user/info/?fields=open_id%2Cdisplay_name%2Cavatar_url');expect(new Headers(init?.headers).get('authorization')).toBe('Bearer safe-token');return new Response(JSON.stringify({data:{user:{open_id:'o',display_name:'Pipip'}},error:{code:'ok'}}),{status:200})});const api=new TikTokApiClient({clientKey:'k',clientSecret:'s',redirectUri:validConfig.redirectUri!,requestTimeoutMs:1000},f as typeof fetch);expect(await api.getUserProfile('safe-token')).toEqual({open_id:'o',display_name:'Pipip'})});
  it('maps rate limits and honors Retry-After seconds',async()=>{const api=new TikTokApiClient({clientKey:'k',clientSecret:'s',redirectUri:validConfig.redirectUri!,requestTimeoutMs:1000},(async()=>new Response('',{status:429,headers:{'retry-after':'3'}})) as typeof fetch,new RequestPolicy({maxRetries:0}));await expect(api.getUserProfile('token')).rejects.toMatchObject({detail:{code:'RATE_LIMITED',retryAfterMs:3000}})});
  it('keeps retry policy bounded and exponential',async()=>{const waits:number[]=[];let calls=0;const policy=new RequestPolicy({maxRetries:2,sleep:async(ms)=>{waits.push(ms)}});const result=await policy.run(async()=>({attempt:++calls}),x=>({retry:x.attempt<5}));expect(calls).toBe(3);expect(waits).toEqual([250,500]);expect(result.attempt).toBe(3)});

  it('accepts loopback callback, returns no code in HTML, then closes',async()=>{const {createServer}=await import('node:net');const port=await new Promise<number>((resolve,reject)=>{const probe=createServer();probe.once('error',reject);probe.listen(0,'127.0.0.1',()=>{const address=probe.address();if(!address||typeof address==='string'){reject(new Error('No test port'));return}const selected=address.port;probe.close(error=>error?reject(error):resolve(selected))})});const callback=new LoopbackCallbackServer(port);await callback.start(5000);const pending=callback.wait();const response=await fetch(`http://127.0.0.1:${port}/callback/?code=one-time-code&state=state-ok`);const html=await response.text();const result=await pending;expect(response.status).toBe(200);expect(html).not.toContain('one-time-code');expect(result).toMatchObject({code:'one-time-code',state:'state-ok'});await callback.shutdown()});
  it('performs at most two retries for safe profile GET 429 responses',async()=>{let calls=0;const waits:number[]=[];const request=async()=>{calls++;return calls<3?new Response('',{status:429}):new Response(JSON.stringify({data:{user:{open_id:'ok'}},error:{code:'ok'}}),{status:200})};const api=new TikTokApiClient({clientKey:'k',clientSecret:'s',redirectUri:validConfig.redirectUri!,requestTimeoutMs:1000},request as typeof fetch,new RequestPolicy({maxRetries:2,sleep:async ms=>{waits.push(ms)}}));expect(await api.getUserProfile('token')).toEqual({open_id:'ok'});expect(calls).toBe(3);expect(waits).toEqual([250,500])});
  it('reports unsupported product synchronization without modifying local catalog',async()=>{const store={read:async()=>null,write:async()=>{},clear:async()=>{},isAvailable:()=>true};const connector=new TikTokConnector(validConfig,{store,openExternal:async()=>{}});const result=await connector.syncProducts();expect(result.status).toBe('NOT_VERIFIED');expect(connector.status().itemsSynced).toBe(0);expect(connector.status().syncStatus).toBe('NOT_VERIFIED')});
  it('exposes QR as unavailable and does not claim commerce capabilities',()=>{const store={read:async()=>null,write:async()=>{},clear:async()=>{},isAvailable:()=>true};const c=new TikTokConnector(validConfig,{store,openExternal:async()=>{}});expect(c.status().qrAuthorization).toBe('QR_AUTH_UNAVAILABLE');expect(c.getCapabilities().SHOWCASE_PRODUCTS.status).toBe('NOT_VERIFIED');expect(c.getCapabilities().LIVE_PRODUCT_ACCESS.status).toBe('NOT_VERIFIED')});
  it('does not expose token-shaped values in the status DTO',async()=>{const store={read:async()=>credential,write:async()=>{},clear:async()=>{},isAvailable:()=>true};const c=new TikTokConnector(validConfig,{store,openExternal:async()=>{}});const json=JSON.stringify(await c.initialize());expect(json).not.toContain('access-secret');expect(json).not.toContain('refresh-secret');expect(json).not.toContain('secret-do-not-print')});
  it('local disconnect clears credentials and returns to DISCONNECTED',async()=>{const clear=vi.fn(async()=>{});const store={read:async()=>credential,write:async()=>{},clear,isAvailable:()=>true};const c=new TikTokConnector(validConfig,{store,openExternal:async()=>{}});await c.initialize();const status=await c.disconnect();expect(status.state).toBe('DISCONNECTED');expect(status.account).toBeNull();expect(clear).toHaveBeenCalledOnce()});
  it('does not send tokens or status actions through runtime observation',()=>{const c=new TikTokConnector(validConfig,{store:{read:async()=>null,write:async()=>{},clear:async()=>{},isAvailable:()=>true},openExternal:async()=>{}});expect(c.status().account).toBeNull()});
});

