import { describe, expect, it } from 'vitest';
import { AudioDeviceManager, AudioDiagnosticSession, AudioEngine, AudioMixer, AudioWatchdog, DefaultAudioDeviceProvider, FadeController, ReportedAudioDeviceProvider, SimulatedAudioBackend } from '../packages/audio-engine/src/index.js';
import { SpeechController, TTSProviderManager, VoiceQueue, createVoiceRequest, DEFAULT_VOICE_CONFIG, normalizeIndonesianSpeech, numberToIndonesian, INDONESIAN_PRONUNCIATION_PHRASES, WindowsOneCoreTtsProvider } from '../packages/voice-engine/src/index.js';
import type { TTSProvider, TTSRequest, TTSResult, VoiceConfig } from '../packages/voice-engine/src/index.js';

const voiceConfig: VoiceConfig = { ...DEFAULT_VOICE_CONFIG, cacheEnabled: false };
const req = (id: string, priority: TTSRequest['priority']='NORMAL', createdAt=1, expiresAt=Number.MAX_SAFE_INTEGER, text=id): TTSRequest => ({id,text,language:'en-US',voice:'default',speed:1,pitch:0,format:'wav',priority,createdAt,expiresAt,cacheable:false});
const result = (overrides: Partial<TTSResult> = {}): TTSResult => ({ success:true, providerId:'fake', audioRef:'memory.wav', durationMs:1000, format:'wav', sampleRate:22050, channels:1, createdAt:1, ...overrides });
const provider = (overrides: Partial<TTSProvider> = {}): TTSProvider => ({ id:'fake', isAvailable:async()=>true,listVoices:async()=>[{id:'fake-en',name:'Fake English',language:'en-US'}], synthesize:async()=>result(), ...overrides });

describe('Phase 6 voice and audio behavior', () => {
  it.each([
    ['blank text',{text:' '}], ['too long text',{text:'a'.repeat(4001)}], ['speed too slow',{text:'hello',speed:.49}], ['speed too fast',{text:'hello',speed:2.01}],
    ['pitch too low',{text:'hello',pitch:-12.1}], ['pitch too high',{text:'hello',pitch:12.1}], ['short TTL',{text:'hello',ttlMs:99}], ['long TTL',{text:'hello',ttlMs:3_600_001}],
    ['non-integer TTL',{text:'hello',ttlMs:100.5}], ['oversized voice',{text:'hello',voice:'v'.repeat(101)}], ['oversized language',{text:'hello',language:'l'.repeat(36)}],
  ])('rejects invalid TTS request: %s', (_label, input) => expect(()=>createVoiceRequest(input,voiceConfig,10)).toThrow());
  it.each([
    ['trims speech',{text:'  hello  '},'hello'], ['uses configured language',{text:'hi'},'en-US'], ['uses configured voice',{text:'hi'},'default'],
  ])('normalizes valid TTS request: %s',(_label,input,expected)=>{const r=createVoiceRequest(input,voiceConfig,100);expect([r.text,r.language,r.voice]).toContain(expected);expect(r.createdAt).toBe(100);expect(r.format).toBe('wav')});

  it.each([
    ['EMERGENCY','HIGH'], ['HIGH','NORMAL'], ['NORMAL','LOW'], ['LOW','LOW'],
  ] as const)('orders queue priority %s before lower work', (top, lower) => {const q=new VoiceQueue(4,()=>5);q.enqueue(req('lower',lower,1));q.enqueue(req('top',top,2));expect(q.pop()?.id).toBe(top==='LOW'?'lower':'top')});
  it('keeps FIFO order for equal priority',()=>{const q=new VoiceQueue(4);q.enqueue(req('b','NORMAL',2));q.enqueue(req('a','NORMAL',1));expect(q.pop()?.id).toBe('a')});
  it('rejects case-insensitive duplicate text with same voice and language',()=>{const q=new VoiceQueue(4);q.enqueue(req('1','NORMAL',1,100,'Hello'));expect(q.enqueue(req('2','NORMAL',2,100,'hello'))).toBe(false)});
  it('expires queued work against its clock',()=>{let now=0;const q=new VoiceQueue(4,()=>now);q.enqueue(req('stale','NORMAL',0,10));now=10;expect(q.size).toBe(0)});
  it('enforces bounded queue capacity',()=>{const q=new VoiceQueue(1);expect(q.enqueue(req('1'))).toBe(true);expect(q.enqueue(req('2'))).toBe(false)});
  it('supports queued cancellation',()=>{const q=new VoiceQueue(4);q.enqueue(req('x'));expect(q.cancel('x')).toBe(true);expect(q.size).toBe(0)});
  it('clears all queued work',()=>{const q=new VoiceQueue(4);q.enqueue(req('x'));q.enqueue(req('y'));q.clear();expect(q.list()).toEqual([])});
  it('blocks queued work during pause',()=>{const q=new VoiceQueue(4);q.setPaused(true);expect(q.enqueue(req('x'))).toBe(false)});
  it('blocks queued work during human takeover',()=>{const q=new VoiceQueue(4);q.setHumanTakeover(true);expect(q.pop()).toBeUndefined();expect(q.enqueue(req('x'))).toBe(false)});
  it('clears and latches on emergency queue stop',()=>{const q=new VoiceQueue(4);q.enqueue(req('x'));q.stop();expect(q.size).toBe(0);expect(q.enqueue(req('y'))).toBe(false)});

  it.each(Array.from({length:11},(_,i)=>i/10))('clamps mixer music level safely at %s',value=>{const mix=new AudioMixer({enabled:true,musicLevelDuringVoice:.2,attackMs:20,releaseMs:50,fadeDurationMs:30,minimumMusicLevel:0},1,.5);expect(mix.setMusicLevel(value).music).toBeCloseTo(value)});
  it.each([0,.1,.2,.4,.7,1])('ducks speech music beneath configured maximum for voice level %s',value=>{const mix=new AudioMixer({enabled:true,musicLevelDuringVoice:.2,attackMs:20,releaseMs:50,fadeDurationMs:30,minimumMusicLevel:0},1,value);expect(mix.duckForVoice().music).toBeLessThanOrEqual(.2)});
  it('restores the selected base music level after speech',()=>{const mix=new AudioMixer({enabled:true,musicLevelDuringVoice:.2,attackMs:20,releaseMs:50,fadeDurationMs:30,minimumMusicLevel:0},1,.75);mix.duckForVoice();expect(mix.restoreMusic().music).toBe(.75)});
  it('disables ducking when configured off',()=>{const mix=new AudioMixer({enabled:false,musicLevelDuringVoice:.2,attackMs:20,releaseMs:50,fadeDurationMs:30,minimumMusicLevel:0},1,.75);expect(mix.duckForVoice().music).toBe(.75)});
  it('scales voice and music with master volume',()=>{const mix=new AudioMixer({enabled:true,musicLevelDuringVoice:.2,attackMs:20,releaseMs:50,fadeDurationMs:30,minimumMusicLevel:0},.8,.6);expect(mix.setMasterLevel(.5)).toMatchObject({voice:.4,music:.3})});
  it('mutes both mixer channels',()=>{const mix=new AudioMixer({enabled:true,musicLevelDuringVoice:.2,attackMs:20,releaseMs:50,fadeDurationMs:30,minimumMusicLevel:0});expect(mix.setMuted(true)).toMatchObject({voice:0,music:0,muted:true})});

  it.each([0,1,5,10,25,50,75,99,100])('interpolates fade at ratio %s%%',ratio=>{const fade=new FadeController(()=>100);const f=fade.transition(0,1,100);expect(f.valueAt(100+ratio)).toBeCloseTo(ratio/100)});
  it.each([-1,30_001,Number.NaN])('rejects invalid fade duration %s',duration=>expect(()=>new FadeController(()=>0).transition(0,1,duration)).toThrow());
  it('finishes zero duration fade immediately',()=>expect(new FadeController(()=>0).transition(.2,.8,0).valueAt(0)).toBe(.8));

  it('plays a simulated voice clip',async()=>{let now=0;const backend=new SimulatedAudioBackend(()=>now);await backend.play('VOICE','v','voice.wav',100,false);expect(backend.getState('VOICE').state).toBe('PLAYING')});
  it('tracks simulated playback position',async()=>{let now=0;const backend=new SimulatedAudioBackend(()=>now);await backend.play('VOICE','v','voice.wav',1000,false);now=400;expect(backend.getState('VOICE').positionMs).toBe(400)});
  it('pauses and resumes voice playback',async()=>{let now=0;const backend=new SimulatedAudioBackend(()=>now);await backend.play('VOICE','v','voice.wav',1000,false);now=200;expect(backend.pause('VOICE')).toBe(true);expect(backend.resume('VOICE')).toBe(true)});
  it('rejects resume when not paused',()=>expect(new SimulatedAudioBackend().resume('VOICE')).toBe(false));
  it('stops one channel without stopping the other',async()=>{const backend=new SimulatedAudioBackend();await backend.play('VOICE','v','v.wav',1000,false);await backend.play('MUSIC','m','m.wav',1000,true);backend.stop('VOICE');expect(backend.getState('VOICE').state).toBe('STOPPED');expect(backend.getState('MUSIC').state).toBe('PLAYING')});
  it('stops both channels on global stop',async()=>{const backend=new SimulatedAudioBackend();await backend.play('VOICE','v','v.wav',1000,false);await backend.play('MUSIC','m','m.wav',1000,true);backend.stop();expect(backend.getState('VOICE').state).toBe('STOPPED');expect(backend.getState('MUSIC').state).toBe('STOPPED')});
  it('seeks within a clip',async()=>{let now=0;const backend=new SimulatedAudioBackend(()=>now);await backend.play('MUSIC','m','m.wav',1000,false);expect(backend.seek('MUSIC',700)).toBe(true);expect(backend.getState('MUSIC').positionMs).toBe(700)});
  it('rejects negative seek',async()=>{const backend=new SimulatedAudioBackend();await backend.play('MUSIC','m','m.wav',1000,false);expect(backend.seek('MUSIC',-1)).toBe(false)});
  it('rejects zero duration clips',async()=>await expect(new SimulatedAudioBackend().play('VOICE','v','v.wav',0,false)).rejects.toThrow());
  it('rejects unavailable output devices',async()=>await expect(new SimulatedAudioBackend(()=>0,()=>{},false).play('MUSIC','m','m.wav',1000,false)).rejects.toThrow());
  it('ticks a completed simulated clip once',async()=>{let now=0;let ended=0;const backend=new SimulatedAudioBackend(()=>now,()=>ended++);await backend.play('VOICE','v','v.wav',100,false);now=100;expect(await backend.tick('VOICE')).toBe(true);expect(await backend.tick('VOICE')).toBe(false);expect(ended).toBe(1)});
  it('does not finish looping simulated music',async()=>{let now=1000;const backend=new SimulatedAudioBackend(()=>now);await backend.play('MUSIC','m','m.wav',10,true);expect(await backend.tick('MUSIC')).toBe(false)});
  it('applies master and channel volume',()=>{const backend=new SimulatedAudioBackend();backend.setMasterVolume(.5);backend.setVolume('MUSIC',.4);expect(backend.getEffectiveVolume('MUSIC')).toBe(.2)});
  it('mutes simulated output without losing levels',()=>{const backend=new SimulatedAudioBackend();backend.setVolume('VOICE',.7);backend.mute(true);expect(backend.getEffectiveVolume('VOICE')).toBe(0);backend.mute(false);expect(backend.getEffectiveVolume('VOICE')).toBe(.7)});
  it('reports playback failure through a bounded error',async()=>{const backend=new SimulatedAudioBackend();await backend.play('VOICE','v','v.wav',100,false);backend.fail('VOICE','e'.repeat(300));expect(backend.getState('VOICE').error).toHaveLength(180)});
  it('emits playback errors to listeners',async()=>{let type='';const backend=new SimulatedAudioBackend(()=>0,e=>{type=e.type});await backend.play('MUSIC','m','m.wav',100,false);backend.fail('MUSIC','broken');expect(type).toBe('PLAYBACK_ERROR')});

  it('emergency audio stop latches and mutes',async()=>{const backend=new SimulatedAudioBackend();const engine=new AudioEngine(backend,{enabled:true,outputDevice:'default',masterVolume:1,voiceVolume:1,musicVolume:.6,maxAssetBytes:1000,ducking:{enabled:true,musicLevelDuringVoice:.2,attackMs:10,releaseMs:20,fadeDurationMs:10,minimumMusicLevel:0}});await engine.play('MUSIC','m','m.wav',1000,true);engine.emergencyStop();expect(engine.isEmergencyStopped()).toBe(true);expect(backend.getEffectiveVolume('MUSIC')).toBe(0)});
  it('blocks playback until emergency reset',async()=>{const engine=new AudioEngine(new SimulatedAudioBackend(),{enabled:true,outputDevice:'default',masterVolume:1,voiceVolume:1,musicVolume:.6,maxAssetBytes:1000,ducking:{enabled:true,musicLevelDuringVoice:.2,attackMs:10,releaseMs:20,fadeDurationMs:10,minimumMusicLevel:0}});engine.emergencyStop();expect(await engine.play('VOICE','v','v.wav',100,false)).toBe(false)});
  it('resets emergency audio state',()=>{const engine=new AudioEngine(new SimulatedAudioBackend(),{enabled:true,outputDevice:'default',masterVolume:1,voiceVolume:1,musicVolume:.6,maxAssetBytes:1000,ducking:{enabled:true,musicLevelDuringVoice:.2,attackMs:10,releaseMs:20,fadeDurationMs:10,minimumMusicLevel:0}});engine.emergencyStop();engine.resetEmergency();expect(engine.isEmergencyStopped()).toBe(false)});

  it('lists and selects the default output device',async()=>{const manager=new AudioDeviceManager(new DefaultAudioDeviceProvider());expect((await manager.list())[0]?.id).toBe('default');expect(await manager.select('default')).toBe(true)});
  it('rejects an unknown output device',async()=>{const manager=new AudioDeviceManager(new DefaultAudioDeviceProvider());expect(await manager.select('missing')).toBe(false)});
  it('rejects an unavailable listed output device',async()=>{const manager=new AudioDeviceManager({list:async()=>[{id:'off',label:'Offline',isDefault:false,available:false}],set:async()=>true});expect(await manager.select('off')).toBe(false)});
  it('updates selected device only after provider accepts it',async()=>{const manager=new AudioDeviceManager({list:async()=>[{id:'x',label:'X',isDefault:false,available:true}],set:async()=>false});expect(await manager.select('x')).toBe(false);expect(manager.getSelected()).toBe('default')});
  it('reports only enumerated audio outputs and retains a safe default',async()=>{const p=new ReportedAudioDeviceProvider();p.update([{id:'out-1',label:'USB Speakers',isDefault:false,available:true}]);expect(await p.list()).toEqual(expect.arrayContaining([{id:'default',label:'System default output',isDefault:true,available:true},{id:'out-1',label:'USB Speakers',isDefault:false,available:true}]))});
  it('does not select an output absent from renderer enumeration',async()=>{const p=new ReportedAudioDeviceProvider();p.update([{id:'one',label:'One',isDefault:false,available:true}]);expect(await p.set('arbitrary-command')).toBe(false)});
  it('filters malformed renderer output identifiers',async()=>{const p=new ReportedAudioDeviceProvider();p.update([{id:'x;format',label:'bad',isDefault:false,available:true},{id:'good_1',label:'ok',isDefault:false,available:true}]);expect((await p.list()).map(x=>x.id)).toEqual(['good_1','default'])});

  it('builds a diagnostic report without claiming human audibility',()=>{const d=new AudioDiagnosticSession('System default output',true,()=> '2026-09-25T00:00:00.000Z');d.markPlayback('tone',true);d.markPlayback('voice',true);expect(d.report()).toMatchObject({timestamp:'2026-09-25T00:00:00.000Z',deviceDetected:true,softwarePlayback:true,voicePlayback:true,humanConfirmed:null,status:{speaker:'UNKNOWN',voice:'READY'}})});
  it('requires explicit confirmation before reporting speaker ready',()=>{const d=new AudioDiagnosticSession('Speakers',true);d.confirmSpeaker(true);expect(d.report()).toMatchObject({humanConfirmed:true,status:{speaker:'READY'}})});
  it('records a failed human listening check separately from software playback',()=>{const d=new AudioDiagnosticSession('Speakers',true);d.markPlayback('tone',true);d.confirmSpeaker(false);expect(d.report()).toMatchObject({softwarePlayback:true,humanConfirmed:false,status:{speaker:'FAILED'}})});
  it.each([['voice','voicePlayback','status.voice'],['music','musicPlayback','status.music'],['ducking','duckingPlayback','status.ducking']] as const)('records diagnostic %s success and failure', (step,field,path)=>{const d=new AudioDiagnosticSession('default',true);d.markPlayback(step,true);expect(d.report()[field]).toBe(true);expect(path.split('.').reduce((x,k)=>(x as any)[k],d.report())).toBe('READY');d.markPlayback(step,false);expect(d.report()[field]).toBe(false)});

  it.each([
    ['Rp89.000','delapan puluh sembilan ribu rupiah'],['500 g','lima ratus gram'],['2 kg','dua kilogram'],['30%','tiga puluh persen'],
    ['Rp 89.000','delapan puluh sembilan ribu rupiah'],
  ])('normalizes Indonesian pronunciation: %s', (input,expected)=>expect(normalizeIndonesianSpeech(input)).toBe(expected));
  it.each([['BrandX500','BrandX500'],['SKU-2409','SKU-2409'],['https://pipip.id/500g','https://pipip.id/500g'],['Model 500G Pro','Model 500G Pro']])('preserves product identifiers: %s',(input,expected)=>expect(normalizeIndonesianSpeech(input)).toBe(expected));
  it('preserves caller-supplied product names while normalizing adjacent facts',()=>expect(normalizeIndonesianSpeech('Pipip 500 g tersedia dengan diskon 30%.',['Pipip 500 g'])).toBe('Pipip 500 g tersedia dengan diskon tiga puluh persen.'));
  it.each([[0,'nol'],[1,'satu'],[11,'sebelas'],[89,'delapan puluh sembilan'],[100,'seratus'],[500,'lima ratus'],[1000,'seribu'],[89000,'delapan puluh sembilan ribu']])('spells Indonesian integer %s', (value,expected)=>expect(numberToIndonesian(value)).toBe(expected));
  it('keeps the required pronunciation suite limited to Indonesian phrases',()=>expect(INDONESIAN_PRONUNCIATION_PHRASES).toHaveLength(7));

  it.each([
    ['missing file',{fileAvailable:false},'MISSING_AUDIO_FILE'], ['device lost',{deviceAvailable:false},'DEVICE_UNAVAILABLE'], ['bad format',{supportedFormat:false},'UNSUPPORTED_FORMAT'],
    ['failed player',{state:'FAILED'},'PLAYBACK_FAILURE'], ['slow synthesis',{state:'SYNTHESIZING',now:30000,stateSince:0},'SYNTHESIS_TIMEOUT'],
    ['zero audio',{state:'PLAYING',durationMs:0},'ZERO_DURATION'], ['stuck audio',{state:'PLAYING',durationMs:1000,now:7000,stateSince:0,positionMs:0},'STUCK_PLAYBACK'],
    ['wedged queue',{state:'IDLE',queueLength:1,activeRequest:false},'QUEUE_DEADLOCK'],
  ] as const)('detects watchdog fault: %s',(_name,overrides,expected)=>{const base={state:'IDLE',now:0,stateSince:0,durationMs:null,positionMs:0,queueLength:0,activeRequest:false};expect(new AudioWatchdog().inspect({...base,...overrides})).toBe(expected)});
  it('does not report healthy playback as a fault',()=>expect(new AudioWatchdog().inspect({state:'PLAYING',now:100,stateSince:0,durationMs:10000,positionMs:100,queueLength:0,activeRequest:true})).toBeNull());

  it('selects the first healthy TTS provider',async()=>{const manager=new TTSProviderManager([provider({id:'off',isAvailable:async()=>false}),provider({id:'on'})]);expect(await manager.listAvailable()).toEqual(['on'])});
  it('falls through to healthy TTS provider after provider exception',async()=>{const manager=new TTSProviderManager([provider({id:'bad',isAvailable:async()=>{throw Error('offline')}}),provider({id:'good'})]);expect(await manager.listAvailable()).toEqual(['good'])});
  it('does not let an English voice satisfy an Indonesian request',async()=>{const manager=new TTSProviderManager([provider({id:'english'})]);expect(await manager.isIndonesianVoiceAvailable()).toBe(false);const r=await manager.synthesize(createVoiceRequest({text:'Halo',language:'id-ID'},voiceConfig));expect(r.errorCode).toBe('NO_ID_ID_VOICE')});
  it('selects only the matching Indonesian provider when both languages exist',async()=>{const manager=new TTSProviderManager([provider({id:'english'}),provider({id:'indo',listVoices:async()=>[{id:'andi',name:'Andika',language:'id-ID'}],synthesize:async req=>result({providerId:'indo',actualLanguage:req.language,actualVoice:'Andika'})})]);const r=await manager.synthesize(createVoiceRequest({text:'Halo',language:'id-ID'},voiceConfig));expect(r.providerId).toBe('indo');expect(r.actualLanguage).toBe('id-ID')});
  it('enumerates voices and provider language capabilities across installed providers',async()=>{const manager=new TTSProviderManager([provider({id:'en'}),provider({id:'id',listVoices:async()=>[{id:'andi',name:'Andika',language:'id-ID'}]})]);expect((await manager.listVoices()).map(x=>x.provider)).toEqual(['en','id']);expect((await manager.getCapabilities()).map(x=>x.languages)).toEqual([['en-US'],['id-ID']])});
  it('does not fall back from an unavailable explicitly selected voice',async()=>{const manager=new TTSProviderManager([provider({id:'first',listVoices:async()=>[{id:'a',name:'A',language:'en-US'}]}),provider({id:'second',listVoices:async()=>[{id:'b',name:'B',language:'en-US'}]})]);const r=await manager.synthesize(createVoiceRequest({text:'hello',language:'en-US',voice:'missing'},voiceConfig));expect(r.success).toBe(false)});
  it('returns explicit text fallback when no TTS provider is available',async()=>{const manager=new TTSProviderManager([provider({isAvailable:async()=>false})]);expect((await manager.synthesize(createVoiceRequest({text:'hello'},voiceConfig))).success).toBe(false)});
  it('uses available TTS provider synthesis result',async()=>{const manager=new TTSProviderManager([provider()]);expect((await manager.synthesize(createVoiceRequest({text:'hello'},voiceConfig))).audioRef).toBe('memory.wav')});
  it('falls through when a provider returns malformed success',async()=>{const manager=new TTSProviderManager([provider({synthesize:async()=>result({audioRef:'',durationMs:0})}),provider({id:'backup',synthesize:async()=>result({providerId:'backup'})})]);expect((await manager.synthesize(createVoiceRequest({text:'hello'},voiceConfig))).providerId).toBe('backup')});
  it('stops a timed-out TTS provider',async()=>{let stopped=0;const manager=new TTSProviderManager([provider({synthesize:()=>new Promise<TTSResult>(()=>{}),stop:async()=>{stopped++}})],5);await manager.synthesize(createVoiceRequest({text:'hello'},voiceConfig));expect(stopped).toBe(1)});

  it('sends a synthesized request to the ready state',async()=>{const events:any[]=[];const c=new SpeechController(voiceConfig,new TTSProviderManager([provider()]),undefined,e=>events.push(e));const accepted=await c.speak({text:'hello'});await new Promise(r=>setTimeout(r,0));expect(accepted.accepted).toBe(true);expect(events.some(e=>e.type==='VOICE_READY')).toBe(true);expect(c.getStatus().state).toBe('READY')});
  it('does not emit synthesized audio while paused',async()=>{let release!: (x:TTSResult)=>void;const events:any[]=[];const c=new SpeechController(voiceConfig,new TTSProviderManager([provider({synthesize:()=>new Promise<TTSResult>(r=>release=r)})]),undefined,e=>events.push(e));await c.speak({text:'hello'});await new Promise(r=>setTimeout(r,0));c.pause();release(result());await new Promise(r=>setTimeout(r,0));expect(events.some(e=>e.type==='VOICE_READY')).toBe(false);c.resume();expect(events.some(e=>e.type==='VOICE_READY')).toBe(true)});
  it('supports playback lifecycle acknowledgements',async()=>{const c=new SpeechController(voiceConfig,new TTSProviderManager([provider()]));const a=await c.speak({text:'hello'});await new Promise(r=>setTimeout(r,0));expect(c.markPlaybackStarted(a.requestId!)).toBe(true);expect(c.markPlaybackComplete(a.requestId!,true)).toBe(true);expect(c.getStatus().state).toBe('IDLE')});
  it('uses text-only fallback when local synthesis is unavailable',async()=>{const events:any[]=[];const c=new SpeechController(voiceConfig,new TTSProviderManager([provider({isAvailable:async()=>false})]),undefined,e=>events.push(e));await c.speak({text:'keep visible'});await new Promise(r=>setTimeout(r,0));expect(events.some(e=>e.type==='VOICE_TEXT_ONLY'&&e.text==='keep visible')).toBe(true)});
  it('human takeover cancels synthesis and blocks new speech',async()=>{const c=new SpeechController(voiceConfig,new TTSProviderManager([provider()]));c.setHumanTakeover(true);expect((await c.speak({text:'hello'})).accepted).toBe(false);expect(c.getStatus().humanTakeover).toBe(true)});
  it('emergency stop blocks voice until reset',async()=>{const c=new SpeechController(voiceConfig,new TTSProviderManager([provider()]));c.emergencyStop();expect((await c.speak({text:'hello'})).accepted).toBe(false);c.resetEmergency();expect((await c.speak({text:'hello'})).accepted).toBe(true)});
  it('rejects completion for a non-current speech request',()=>{const c=new SpeechController(voiceConfig,new TTSProviderManager([provider()]));expect(c.markPlaybackComplete('wrong')).toBe(false)});
  it('cancels active speech and rejects late completion',async()=>{let release!: (x:TTSResult)=>void;const c=new SpeechController(voiceConfig,new TTSProviderManager([provider({synthesize:()=>new Promise<TTSResult>(r=>release=r)})]));const a=await c.speak({text:'hello'});await new Promise(r=>setTimeout(r,0));c.cancel(a.requestId!);release(result());await new Promise(r=>setTimeout(r,0));expect(c.getStatus().state).toBe('IDLE')});
  it('returns false when cancelling unknown speech',()=>expect(new SpeechController(voiceConfig,new TTSProviderManager([])).cancel('absent')).toBe(false));

  it('enumerates the installed Windows OneCore Indonesian voice through its provider adapter',async()=>{const p=new WindowsOneCoreTtsProvider({platform:'win32',outputDirectory:'C:/temp',run:async()=>({code:0,stderr:'',stdout:JSON.stringify({voices:[{id:'onecore-id',name:'Microsoft Andika',language:'id-ID'}]})})});expect(await p.listVoices()).toMatchObject([{name:'Microsoft Andika',language:'id-ID',available:true}]);expect(await p.isAvailable()).toBe(true)});
  it('rejects Windows OneCore synthesis for the wrong language',async()=>{const p=new WindowsOneCoreTtsProvider({platform:'win32',outputDirectory:'C:/temp',run:async()=>({code:0,stderr:'',stdout:JSON.stringify({voices:[{id:'onecore-id',name:'Microsoft Andika',language:'id-ID'}]})})});const r=await p.synthesize(createVoiceRequest({text:'Hello',language:'en-US'},voiceConfig));expect(r.success).toBe(false)});
});
