import {z} from 'zod';
import {deterministicRule,applyConfidence} from './decision-policy.js';
import {DecisionCache} from './decision-cache.js';
import {DecisionMetricsCollector} from './metrics.js';
import {DeterministicDecisionProvider} from './providers/deterministic-provider.js';
import {InvalidJevResponseError,JevDecisionProvider} from './providers/jev-provider.js';
import type {DecisionAction,DecisionProvider,DecisionRequest,DecisionResult,JevAvailability} from './types.js';

const resultSchema=z.object({decision:z.enum(['RESPOND','IGNORE','QUEUE','ESCALATE','DETERMINISTIC','LLM_FAST','LLM_STRONG','TOOL','REJECT']),intent:z.string().min(1).max(60),confidence:z.number().finite().min(0).max(1),reasonCode:z.string().regex(/^[A-Z0-9_:-]{1,80}$/),requiresLlm:z.boolean(),requiresHuman:z.boolean(),toolAllowed:z.boolean(),provider:z.string().regex(/^[a-z0-9_-]{1,40}$/),latencyMs:z.number().finite().nonnegative().optional(),metadata:z.record(z.unknown()).optional()}).strict();
function safeRequest(request:DecisionRequest):DecisionRequest {const text=request.text?.replace(/Bearer\s+\S+/gi,'Bearer [REDACTED]').replace(/(access.?token|refresh.?token|api.?key|client.?secret|password|authorization.?code)\s*[:=]\s*\S+/gi,'$1=[REDACTED]').slice(0,500);return{...request,...(text===undefined?{}:{text}),allowedActions:request.allowedActions?.filter(x=>/^[A-Z_]{1,40}$/.test(x)).slice(0,24),...(request.productContext?{productContext:{...(request.productContext.productId?{productId:request.productContext.productId.slice(0,120)}:{}),...(request.productContext.verified===undefined?{}:{verified:request.productContext.verified})}}:{}),timestamp:Number.isFinite(request.timestamp)?request.timestamp:Date.now()}}
export interface DecisionIntelligenceOptions {primary?:DecisionProvider;fallback?:DecisionProvider;timeoutMs?:number;cache?:DecisionCache;now?:()=>number}
export class DecisionIntelligence {
  readonly metrics=new DecisionMetricsCollector();readonly jevProvider:DecisionProvider;readonly fallback:DecisionProvider;readonly cache:DecisionCache;private enabled=true;private readonly timeoutMs:number;private readonly now:()=>number;private controllers=new Set<AbortController>();private availability:JevAvailability='NOT_CONFIGURED';
  constructor(options:DecisionIntelligenceOptions={}){this.jevProvider=options.primary??new JevDecisionProvider();this.fallback=options.fallback??new DeterministicDecisionProvider();this.timeoutMs=Math.max(50,Math.min(5000,options.timeoutMs??500));this.now=options.now??Date.now;this.cache=options.cache??new DecisionCache(5000,100,this.now);void this.jevProvider.isAvailable().then(available=>{this.availability=available?'AVAILABLE':'NOT_CONFIGURED'}).catch(()=>{this.availability='ERROR'})}
  setEnabled(value:boolean){this.enabled=value;if(!value)this.cancelPending();return this.enabled}
  get isEnabled(){return this.enabled}
  get jevAvailability(){return this.availability}
  cancelPending(){for(const controller of this.controllers)controller.abort();this.controllers.clear();this.cache.invalidate()}
  async decide(input:DecisionRequest):Promise<DecisionResult>{const start=this.now();const request=safeRequest(input);if(!Number.isFinite(input.timestamp))return this.finish({decision:'REJECT',intent:input.intent??'UNKNOWN',confidence:0,reasonCode:'INVALID_REQUEST',requiresLlm:false,requiresHuman:true,toolAllowed:false,provider:'deterministic'},start);
    if(request.liveState==='EMERGENCY_STOPPED'||request.eventType==='EMERGENCY_STOP'){this.cancelPending();return this.finish({decision:'DETERMINISTIC',intent:'SYSTEM',confidence:1,reasonCode:'EMERGENCY_PRIORITY',requiresLlm:false,requiresHuman:false,toolAllowed:false,provider:'deterministic'},start)}
    if(request.liveState==='HUMAN_TAKEOVER'||request.hostState==='HUMAN_TAKEOVER'){this.cancelPending();return this.finish({decision:'QUEUE',intent:'SYSTEM',confidence:1,reasonCode:'HUMAN_TAKEOVER_ACTIVE',requiresLlm:false,requiresHuman:true,toolAllowed:false,provider:'deterministic'},start)}
    if(request.eventType==='HUMAN_TAKEOVER'){this.cancelPending();return this.finish({decision:'DETERMINISTIC',intent:'SYSTEM',confidence:1,reasonCode:'HUMAN_TAKEOVER_PRIORITY',requiresLlm:false,requiresHuman:true,toolAllowed:false,provider:'deterministic'},start)}
    const rule=deterministicRule(request);if(rule)return this.finish(rule,start);
    if(!this.enabled)return this.finish(await this.fallback.decide(request),start);
    const cached=this.cache.get(request);if(cached)return this.finish({...cached,provider:'cache'},start);
    let available=false;try{available=await this.jevProvider.isAvailable()}catch{available=false}
    if(!available){this.availability='NOT_CONFIGURED';return this.finish({...await this.fallback.decide(request),provider:'fallback',reasonCode:'JEV_UNAVAILABLE_FALLBACK'},start)}this.availability='AVAILABLE';
    const controller=new AbortController();this.controllers.add(controller);let timer:ReturnType<typeof setTimeout>|undefined;
    try{const response=await Promise.race([this.jevProvider.decide(request,controller.signal),new Promise<never>((_,reject)=>{timer=setTimeout(()=>{controller.abort();const error=new Error('JEv decision timed out');error.name='TimeoutError';reject(error)},this.timeoutMs)})]);const checked=resultSchema.safeParse(response);if(!checked.success)throw new InvalidJevResponseError();const accepted=applyConfidence({...checked.data,provider:'jev',toolAllowed:false});if(accepted.reasonCode==='INVALID_CONFIDENCE')throw new InvalidJevResponseError();if(!request.text&&accepted.decision==='DETERMINISTIC')this.cache.set(request,accepted);return this.finish(accepted,start)}
    catch(error){if(error instanceof InvalidJevResponseError){this.availability='ERROR';this.metrics.failure();return this.finish({decision:'REJECT',intent:request.intent??'UNKNOWN',confidence:0,reasonCode:'MALFORMED_JEV_RESPONSE',requiresLlm:false,requiresHuman:true,toolAllowed:false,provider:'jev'},start)}if(controller.signal.aborted&&(!(error instanceof Error)||error.name!=='TimeoutError')){return this.finish({decision:'QUEUE',intent:request.intent??'UNKNOWN',confidence:1,reasonCode:'DECISION_CANCELLED',requiresLlm:false,requiresHuman:false,toolAllowed:false,provider:'deterministic'},start)}this.availability='ERROR';this.metrics.failure();return this.finish({...await this.fallback.decide(request),provider:'fallback',reasonCode:error instanceof Error&&error.name==='TimeoutError'?'JEV_TIMEOUT_FALLBACK':'JEV_UNAVAILABLE_FALLBACK'},start)}
    finally{if(timer)clearTimeout(timer);this.controllers.delete(controller)}
  }
  snapshot(){return{enabled:this.enabled,jevAvailability:this.availability,jevConfigured:this.availability==='AVAILABLE'||this.availability==='ERROR',metrics:this.metrics.snapshot()}}
  private finish(result:DecisionResult,start:number){const checked=resultSchema.safeParse(result);const valid=checked.success?checked.data:{decision:'REJECT' as DecisionAction,intent:'UNKNOWN',confidence:0,reasonCode:'INVALID_PROVIDER_RESULT',requiresLlm:false,requiresHuman:true,toolAllowed:false,provider:'deterministic'};this.metrics.record(valid.provider,valid.decision,Math.max(0,this.now()-start),valid.confidence);return valid}
}
