import { randomUUID } from 'node:crypto';

export const VALIDATION_CATEGORIES = ['audio','voice','music','ducking','broadcast','avatar','runtime','takeover','emergency','tiktok','account','capability','product','ui','suite','typecheck','build','audit'] as const;
export type ValidationCategory = typeof VALIDATION_CATEGORIES[number];
export type ValidationStatus = 'NOT_TESTED'|'AUTOMATED_PASS'|'HUMAN_VERIFIED'|'FAILED'|'NOT_AVAILABLE'|'NOT_CONFIGURED';
export interface ValidationRecord {id:string;category:ValidationCategory;testId:string;status:ValidationStatus;timestamp:number;operatorConfirmed:boolean;notes?:string;evidence?:string;errorCode?:string}
export interface ValidationSession {validationSessionId:string;startedAt:number;completedAt:number|null;operator:string|null;tests:ValidationRecord[]}
export interface ValidationMatrixRow {subsystem:string;automated:ValidationStatus;physical:ValidationStatus;status:ValidationStatus;notes:string}
export type OverallReadiness='NOT_READY'|'READY_FOR_NEXT_PHASE'|'BLOCKED';
export interface ValidationSnapshot {activeSession:ValidationSession|null;sessions:ValidationSession[];matrix:ValidationMatrixRow[];overall:OverallReadiness;tiktokConfigured:boolean;tiktokPendingConfiguration:boolean;productCapabilityAvailable:boolean;safeStorage:'AVAILABLE'|'UNAVAILABLE'|'UNKNOWN';deviceInfo:Array<{name:string;default:boolean;available:boolean}>;runtimeState:string;broadcastState:string}
export interface ValidationRecordInput {category:ValidationCategory;testId:string;status:ValidationStatus;operatorConfirmed?:boolean;notes?:string;errorCode?:string}
export interface ValidationPersistedState {sessions:ValidationSession[];activeSessionId:string|null}

const allowedStatuses=new Set<ValidationStatus>(['NOT_TESTED','AUTOMATED_PASS','HUMAN_VERIFIED','FAILED','NOT_AVAILABLE','NOT_CONFIGURED']);
const safeCode=(value:string)=>/^[A-Z0-9_:-]{1,60}$/.test(value)?value:'INVALID_VALIDATION_CODE';
const sanitizeText=(value:string)=>value.replace(/Bearer\s+\S+/gi,'Bearer [REDACTED]').replace(/(access.?token|refresh.?token|client.?secret|code.?verifier|authorization.?code|password|cookie)\s*[:=]\s*\S+/gi,'$1=[REDACTED]').slice(0,160);
function cleanSession(value:unknown):ValidationSession|null {
  if(!value||typeof value!=='object')return null;const x=value as Record<string,unknown>;
  if(typeof x.validationSessionId!=='string'||typeof x.startedAt!=='number'||!Number.isFinite(x.startedAt)||!(x.completedAt===null||typeof x.completedAt==='number')||!(x.operator===null||typeof x.operator==='string')||!Array.isArray(x.tests))return null;
  const tests:ValidationRecord[]=[];
  for(const item of x.tests){if(!item||typeof item!=='object')continue;const r=item as Record<string,unknown>;if(typeof r.id!=='string'||typeof r.category!=='string'||!VALIDATION_CATEGORIES.includes(r.category as ValidationCategory)||typeof r.testId!=='string'||typeof r.status!=='string'||!allowedStatuses.has(r.status as ValidationStatus)||typeof r.timestamp!=='number'||typeof r.operatorConfirmed!=='boolean')continue;tests.push({id:/^[A-Za-z0-9_-]{1,80}$/.test(r.id)?r.id:'INVALID_RECORD_ID',category:r.category as ValidationCategory,testId:safeCode(r.testId),status:r.status as ValidationStatus,timestamp:r.timestamp,operatorConfirmed:r.operatorConfirmed,...(typeof r.notes==='string'?{notes:sanitizeText(r.notes)}:{}),...(typeof r.errorCode==='string'?{errorCode:safeCode(r.errorCode)}:{})})}
  return{validationSessionId:x.validationSessionId.slice(0,80),startedAt:x.startedAt,completedAt:x.completedAt as number|null,operator:typeof x.operator==='string'?sanitizeText(x.operator).slice(0,80):null,tests:tests.slice(-500)};
}

export class ValidationSessionManager {
  private sessions:ValidationSession[]=[];private activeSessionId:string|null=null;
  constructor(private readonly now:()=>number=Date.now,private readonly idFactory:()=>string=randomUUID,state?:unknown){if(state&&typeof state==='object'){const x=state as Partial<ValidationPersistedState>;this.sessions=Array.isArray(x.sessions)?x.sessions.map(cleanSession).filter((s):s is ValidationSession=>s!==null).slice(-30):[];this.activeSessionId=typeof x.activeSessionId==='string'&&this.sessions.some(s=>s.validationSessionId===x.activeSessionId&&s.completedAt===null)?x.activeSessionId:null}}
  start(operator?:string|null){if(this.activeSessionId)this.complete();const session:ValidationSession={validationSessionId:this.idFactory(),startedAt:this.now(),completedAt:null,operator:operator?.trim()?sanitizeText(operator.trim()).slice(0,80):null,tests:[]};this.sessions.push(session);this.sessions=this.sessions.slice(-30);this.activeSessionId=session.validationSessionId;return structuredClone(session)}
  complete(){const s=this.active();if(!s)return null;s.completedAt=this.now();this.activeSessionId=null;return structuredClone(s)}
  record(input:ValidationRecordInput){if(!VALIDATION_CATEGORIES.includes(input.category)||!allowedStatuses.has(input.status))throw new Error('Invalid validation record');if(!this.active()){this.start()}const session=this.active()!;const testId=safeCode(input.testId);const record:ValidationRecord={id:this.idFactory(),category:input.category,testId,status:input.status,timestamp:this.now(),operatorConfirmed:input.status==='HUMAN_VERIFIED'||input.status==='FAILED'&&input.operatorConfirmed===true,...(input.notes?{notes:sanitizeText(input.notes)}:{}),...(input.errorCode?{errorCode:safeCode(input.errorCode)}:{})};session.tests.push(record);if(session.tests.length>500)session.tests.splice(0,session.tests.length-500);return structuredClone(record)}
  state():ValidationPersistedState{return{sessions:structuredClone(this.sessions),activeSessionId:this.activeSessionId}}
  active(){return this.sessions.find(s=>s.validationSessionId===this.activeSessionId)??null}
  latest(category:ValidationCategory,testId?:string){const records=this.sessions.flatMap(s=>s.tests).filter(r=>r.category===category&&(!testId||r.testId===testId));return records.at(-1)??null}
  dashboard(input:{tiktokConfigured:boolean;productCapabilityAvailable?:boolean;safeStorage:'AVAILABLE'|'UNAVAILABLE'|'UNKNOWN';deviceInfo?:ValidationSnapshot['deviceInfo'];runtimeState?:string;broadcastState?:string}):ValidationSnapshot {
    const categories:[string,ValidationCategory,ValidationCategory|null,string][]=[['Automated Suite','suite',null,'Current deterministic test suite result'],['Typecheck','typecheck',null,'Strict TypeScript check result'],['Build','build',null,'Desktop production build result'],['Dependency Audit','audit',null,'npm audit result'],['Audio','audio','audio','Output test and operator-confirmed audibility'],['Voice','voice','voice','Indonesian speech playback and operator audibility'],['Music','music','music','Local music engine and operator audibility'],['Ducking','ducking','ducking','Speech/music duck and restore'],['Emergency Audio','emergency','emergency','Latched emergency stop and explicit reset'],['Desktop UI','ui','ui','Guided controls show real engine state'],['Broadcast Preview','broadcast','broadcast','Local semantic preview, not a stream'],['Avatar Semantic','avatar',null,'Mock semantic state only'],['Live Runtime','runtime','runtime','Local session integration'],['Human Takeover','takeover','takeover','Operator takeover and cooldown'],['TikTok OAuth','tiktok','tiktok','Manual consent and account identity'],['TikTok Account','account','account','Open ID and granted scope validation'],['TikTok Product Capability','capability',null,'Official API capability only'],['Product Sync','product','product','Only verified official product API data']];
    const allRecords=this.sessions.flatMap(s=>s.tests);const lastRecord=(records:ValidationRecord[],accept:(record:ValidationRecord)=>boolean)=>{for(let i=records.length-1;i>=0;i--)if(accept(records[i]!))return records[i]!;return undefined};
    const matrix:ValidationMatrixRow[]=categories.map(([subsystem,category,humanCategory,notes])=>{const records=allRecords.filter(r=>r.category===category);let auto:ValidationStatus=lastRecord(records,r=>['AUTOMATED_PASS','FAILED','NOT_AVAILABLE','NOT_CONFIGURED'].includes(r.status))?.status??'NOT_TESTED';if(category==='tiktok'&&!input.tiktokConfigured)auto='NOT_CONFIGURED';if(category==='account'&&!input.tiktokConfigured)auto='NOT_CONFIGURED';if(category==='capability'&&!input.productCapabilityAvailable)auto='NOT_AVAILABLE';if(category==='product'&&!input.productCapabilityAvailable)auto='NOT_AVAILABLE';const human:ValidationStatus=humanCategory?lastRecord(allRecords.filter(r=>r.category===humanCategory),r=>['HUMAN_VERIFIED','FAILED','NOT_TESTED'].includes(r.status))?.status??'NOT_TESTED':'NOT_AVAILABLE';let rowStatus:ValidationStatus='NOT_TESTED';if(auto==='FAILED'||human==='FAILED')rowStatus='FAILED';else if(auto==='NOT_AVAILABLE')rowStatus='NOT_AVAILABLE';else if(auto==='NOT_CONFIGURED')rowStatus='NOT_CONFIGURED';else if(human==='HUMAN_VERIFIED')rowStatus='HUMAN_VERIFIED';else if(auto==='AUTOMATED_PASS')rowStatus='AUTOMATED_PASS';return{subsystem,automated:auto,physical:human,status:rowStatus,notes}});
    const req=(cat:ValidationCategory,id:string,status:ValidationStatus)=>this.latest(cat,id)?.status===status;
    const required=[req('suite','AUTOMATED_SUITE', 'AUTOMATED_PASS'),req('typecheck','TYPECHECK','AUTOMATED_PASS'),req('build','BUILD','AUTOMATED_PASS'),req('audit','NPM_AUDIT','AUTOMATED_PASS'),req('audio','AUDIO_SOFTWARE','AUTOMATED_PASS'),req('audio','AUDIO_HUMAN','HUMAN_VERIFIED'),req('emergency','EMERGENCY_HUMAN','HUMAN_VERIFIED'),req('runtime','RUNTIME_E2E','AUTOMATED_PASS'),req('broadcast','BROADCAST_PREVIEW','AUTOMATED_PASS')];
    if(input.tiktokConfigured)required.push(req('tiktok','TIKTOK_OAUTH','HUMAN_VERIFIED'));
    const failed=this.sessions.flatMap(s=>s.tests).some(r=>r.status==='FAILED'&&['suite','typecheck','build','audit','audio','voice','music','ducking','emergency','ui','runtime','takeover','broadcast','tiktok','account'].includes(r.category));
    return{activeSession:this.active()?structuredClone(this.active()):null,sessions:structuredClone(this.sessions.slice(-8)),matrix,overall:failed?'BLOCKED':required.every(Boolean)?'READY_FOR_NEXT_PHASE':'NOT_READY',tiktokConfigured:input.tiktokConfigured,tiktokPendingConfiguration:!input.tiktokConfigured,productCapabilityAvailable:input.productCapabilityAvailable??false,safeStorage:input.safeStorage,deviceInfo:input.deviceInfo??[],runtimeState:input.runtimeState??'UNKNOWN',broadcastState:input.broadcastState??'UNKNOWN'};
  }
}
