import {choice,TypeSafeClient} from '@typesafe-ai/sdk';
import type {DecisionProvider,DecisionRequest,DecisionResult,JevAvailability} from '../types.js';

const actions=['RESPOND','IGNORE','QUEUE','ESCALATE','DETERMINISTIC','LLM_FAST','LLM_STRONG','TOOL','REJECT'] as const;
const intents=['GREETING','PRODUCT_QUESTION','PRICE_QUESTION','STOCK_QUESTION','VARIANT_QUESTION','PRODUCT_RECOMMENDATION','COMPARISON','PURCHASE_INTENT','COMPLAINT','JOKE','REACTION','SPAM','ABUSE','OFF_TOPIC','UNKNOWN','GENERAL_QUESTION','REQUEST_DEMO'] as const;
export class InvalidJevResponseError extends Error{constructor(){super('Invalid JEv response');this.name='InvalidJevResponseError'}}
export class JevDecisionProvider implements DecisionProvider {
  readonly id='jev';private readonly client:TypeSafeClient|null;
  constructor(apiKey=process.env.TYPESAFE_API_KEY,private readonly timeoutMs=500,client?:TypeSafeClient){this.client=client??(apiKey?.trim()?new TypeSafeClient({apiKey:apiKey.trim(),defaultModel:'jev-latest',timeout:timeoutMs,retry:{maxRetries:0},logLevel:'off'}):null)}
  async isAvailable():Promise<boolean>{return this.client!==null}
  get availability():JevAvailability{return this.client?'AVAILABLE':'NOT_CONFIGURED'}
  async decide(request:DecisionRequest,signal?:AbortSignal):Promise<DecisionResult>{if(!this.client)throw new Error('JEv is not configured');if(signal?.aborted)throw new Error('JEv request cancelled');const cleanText=(request.text??'').replace(/Bearer\s+\S+/gi,'Bearer [REDACTED]').replace(/(access.?token|refresh.?token|api.?key|client.?secret|password)\s*[:=]\s*\S+/gi,'$1=[REDACTED]').slice(0,500);const started=Date.now();let response;try{response=await this.client.systemOne({state:{eventType:request.eventType,source:request.source,text:cleanText,intent:request.intent??'UNKNOWN',productVerified:request.productContext?.verified??false,liveState:request.liveState??'UNKNOWN',hostState:request.hostState??'UNKNOWN',allowedActions:(request.allowedActions??[]).slice(0,24)},questions:{intent:choice('Classify into exactly one allowed audience intent.',Object.fromEntries(intents.map(value=>[value,value]))),route:choice('Choose the safest next software route. Never authorize an external side effect.',Object.fromEntries(actions.map(value=>[value,value])))}},{timeout:this.timeoutMs,...(signal?{signal}:{}),retry:{maxRetries:0}})}catch(error){if(signal?.aborted)throw error;throw error}const answer=response.answers as Record<string,{choice?:string;confidence?:number}>;const route=answer.route?.choice;const intent=answer.intent?.choice;const confidence=Math.min(answer.route?.confidence??NaN,answer.intent?.confidence??NaN);if(!actions.includes(route as typeof actions[number])||!intents.includes(intent as typeof intents[number])||!Number.isFinite(confidence)||confidence<0||confidence>1)throw new InvalidJevResponseError();const decision=route as DecisionResult['decision'];return{decision,intent:answer.intent!.choice!,confidence,reasonCode:'JEV_STRUCTURED_DECISION',requiresLlm:decision==='LLM_FAST'||decision==='LLM_STRONG',requiresHuman:decision==='ESCALATE'||decision==='REJECT',toolAllowed:false,provider:this.id,latencyMs:Date.now()-started}}
}
