export type KnowledgeTopic='PRODUCT'|'PLATFORM_POLICY'|'GENERAL'|'UNKNOWN';
export interface ExpertSource {url:string;title?:string;retrievedAt?:string}
export interface ExpertRequest {query:string;topic:string;market?:string;platform?:string}
export interface ExpertAnswer {provider:string;text:string;sources:ExpertSource[];confidence:number;retrievedAt:string}
export interface ExternalExpertProvider {id:string;available:boolean;answer(request:ExpertRequest):Promise<ExpertAnswer>}
export function scrubExpertQuery(query:string):string{return query.slice(0,500).replace(/[\w.+-]+@[\w.-]+\.[A-Za-z]{2,}/g,'[email]').replace(/(?:\+?\d[\d .()-]{7,}\d)/g,'[phone]').replace(/@[\p{L}\p{N}_.-]{2,}/gu,'[handle]')}
export class GeminiExpertProvider implements ExternalExpertProvider {id='gemini';available:boolean;constructor(private key?:string,private model='gemini-3.8-flash',private fetcher:typeof fetch=fetch,private timeoutMs=12_000){this.available=Boolean(key)}async answer(request:ExpertRequest):Promise<ExpertAnswer>{if(!this.key)throw new Error('Expert provider unavailable');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const response=await this.fetcher('https://generativelanguage.googleapis.com/v1beta/interactions',{method:'POST',headers:{'content-type':'application/json','x-goog-api-key':this.key},body:JSON.stringify({model:this.model,input:`Give concise, cautious background guidance. Cite sources only if returned by the API. This is advisory text for a human-supervised host and is not verified product or platform policy. Query: ${request.query}`}),signal:controller.signal});if(!response.ok)throw new Error(`Expert provider HTTP ${response.status}`);const data=await response.json() as {output_text?:string;steps?:Array<{type?:string;content?:Array<{text?:string}>}>};const text=data.output_text??data.steps?.filter(x=>x.type==='model_output').flatMap(x=>x.content??[]).map(x=>x.text??'').join('\n')??'';return{provider:this.id,text:text.slice(0,4000),sources:[],confidence:0.4,retrievedAt:new Date().toISOString()}}finally{clearTimeout(timer)}}}
export class OpenAIExpertProvider implements ExternalExpertProvider {id='openai';available:boolean;constructor(private key?:string,private model='gpt-5-mini',private fetcher:typeof fetch=fetch,private timeoutMs=12_000){this.available=Boolean(key)}async answer(request:ExpertRequest):Promise<ExpertAnswer>{if(!this.key)throw new Error('Expert provider unavailable');const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),this.timeoutMs);try{const response=await this.fetcher('https://api.openai.com/v1/responses',{method:'POST',headers:{authorization:`Bearer ${this.key}`,'content-type':'application/json'},body:JSON.stringify({model:this.model,input:`Give concise, cautious background guidance. This is advisory material only, not verified product or platform policy. Query: ${request.query}`,store:false}),signal:controller.signal});if(!response.ok)throw new Error(`Expert provider HTTP ${response.status}`);const data=await response.json() as {output_text?:string;output?:Array<{content?:Array<{text?:string}>}>};const text=data.output_text??data.output?.flatMap(x=>x.content??[]).map(x=>x.text??'').join('\n')??'';return{provider:this.id,text:text.slice(0,4000),sources:[],confidence:0.4,retrievedAt:new Date().toISOString()}}finally{clearTimeout(timer)}}}
export interface PolicyRule {platform:string;market:string;contentType:string;commerceType:string;text:string;sourceUrl:string;verifiedAt:string;expiresAt?:string}
export class PolicyKnowledgeProvider {constructor(private rules:PolicyRule[]=[]){}getApplicableRules(input:{platform:string;market:string;contentType:string;commerceType:string},now=Date.now()){const matches=this.rules.filter(r=>r.platform.toLowerCase()===input.platform.toLowerCase()&&r.market.toLowerCase()===input.market.toLowerCase()&&r.contentType===input.contentType&&r.commerceType===input.commerceType&&/^https:\/\//.test(r.sourceUrl)&&(!r.expiresAt||Date.parse(r.expiresAt)>now));return matches.length?{status:'VERIFIED_SOURCES',rules:matches}:{status:'UNKNOWN',rules:[]}}}
export function validateSources(sources:ExpertSource[]):ExpertSource[]{return sources.filter(s=>{try{return new URL(s.url).protocol==='https:'}catch{return false}}).slice(0,10)}
export class KnowledgeCache {private map=new Map<string,{value:ExpertAnswer;until:number}>();constructor(private ttlMs=300_000,private max=100,private now=()=>Date.now()){}get(key:string){const v=this.map.get(key);if(!v||v.until<this.now()){this.map.delete(key);return undefined}this.map.delete(key);this.map.set(key,v);return v.value}set(key:string,value:ExpertAnswer){this.map.delete(key);this.map.set(key,{value,until:this.now()+this.ttlMs});while(this.map.size>this.max)this.map.delete(this.map.keys().next().value!)}clear(){this.map.clear()}}
export type KnowledgeRoute={status:'CAN_ANSWER'|'NEEDS_PRODUCT_DATA'|'NEEDS_PLATFORM_POLICY'|'NEEDS_EXTERNAL_EXPERT'|'UNKNOWN';topic:KnowledgeTopic;advice?:ExpertAnswer};
export class KnowledgeRouter {constructor(private experts:ExternalExpertProvider[]=[],private cache=new KnowledgeCache(),private threshold=0.65){}async route(input:{query:string;topic:KnowledgeTopic;hasVerifiedProduct:boolean;market?:string;platform?:string}):Promise<KnowledgeRoute>{if(input.topic==='PRODUCT')return{status:input.hasVerifiedProduct?'CAN_ANSWER':'NEEDS_PRODUCT_DATA',topic:input.topic};if(input.topic==='PLATFORM_POLICY')return{status:'NEEDS_PLATFORM_POLICY',topic:input.topic};if(input.topic==='UNKNOWN')return{status:'UNKNOWN',topic:input.topic};const query=scrubExpertQuery(input.query);for(const provider of this.experts){if(!provider.available)continue;const key=`${provider.id}|${input.topic}|${input.market??''}|${input.platform??''}|${query.trim().toLowerCase()}`;const cached=this.cache.get(key);if(cached&&cached.confidence>=this.threshold)return{status:'CAN_ANSWER',topic:input.topic,advice:cached};try{const answer=await provider.answer({query,topic:input.topic,...(input.market?{market:input.market}:{}),...(input.platform?{platform:input.platform}:{})});answer.sources=validateSources(answer.sources);if(answer.text){if(answer.confidence>=this.threshold){this.cache.set(key,answer);return{status:'CAN_ANSWER',topic:input.topic,advice:answer}}return{status:'NEEDS_EXTERNAL_EXPERT',topic:input.topic,advice:answer}}}catch{/* optional advisor failures degrade to a safe unknown route */}}return{status:'UNKNOWN',topic:input.topic}}}
export type LearningLabel='PENDING'|'GOOD'|'BAD'|'NEEDS_REVIEW';export interface LearningRecord {id:string;createdAt:string;topic:string;intent:string;label:LearningLabel;note?:string}
export class LearningPipeline {private records:LearningRecord[]=[];constructor(private max=500,private now=()=>new Date()){}record(input:Omit<LearningRecord,'createdAt'>){const record={...input,createdAt:this.now().toISOString(),...(input.note?{note:input.note.slice(0,300)}:{})};this.records.push(record);this.records=this.records.slice(-this.max);return record}list(){return this.records.map(x=>({...x}))}label(id:string,label:LearningLabel){const item=this.records.find(x=>x.id===id);if(!item)return false;item.label=label;return true}}
