import type{AIProvider}from'../../ai-core/src/index.js';import type{HostContext,HostGenerationResult,HostRequest,HostTrigger,StructuredLog}from'../../shared-types/src/index.js';import{HostRequestSchema}from'../../protocol/src/index.js';import{Logger}from'../../logging/src/index.js';import{HostEngineError,classifyProviderError}from'./errors.js';import{parseHostResponseWithDiagnostics}from'./parser.js';import{HostPromptBuilder}from'./prompt-builder.js';import{hostResponseToCommands}from'./commands.js';
export class HostEngine {
 private autonomyEnabled=false;private lastHumanEventAt:number|null=null;
 constructor(private readonly provider:AIProvider,private readonly prompts:HostPromptBuilder,private readonly logger=new Logger(),private readonly now=()=>Date.now(),private readonly humanEventCooldownMs=30000,private readonly validateProductSpeech?:(speech:string,product:NonNullable<HostContext['currentProduct']>)=>boolean){}
 setAutonomy(enabled:boolean){this.autonomyEnabled=enabled;return enabled}
 isAutonomyEnabled(){return this.autonomyEnabled}
 async handleHumanEvent(trigger:'HUMAN_ENTERED'|'HUMAN_LEFT',context:HostContext):Promise<HostGenerationResult>{if(!this.autonomyEnabled){this.logger.log('WARN','host','event_ignored',{trigger,code:'AUTONOMY_OFF'});return{ok:false,code:'AUTONOMY_OFF',message:'Autonomy is OFF'}}const now=this.now();if(this.lastHumanEventAt!==null&&now-this.lastHumanEventAt<this.humanEventCooldownMs){this.logger.log('WARN','host','event_ignored',{trigger,code:'COOLDOWN'});return{ok:false,code:'COOLDOWN',message:'Human event cooldown'}}this.lastHumanEventAt=now;return this.generate({type:'HOST_RESPONSE',trigger,context})}
 async generate(request:HostRequest):Promise<HostGenerationResult>{
  const checked=HostRequestSchema.safeParse(request);if(!checked.success){this.logger.log('WARN','host','request_rejected',{code:'INVALID_AI_RESPONSE'});return{ok:false,code:'INVALID_AI_RESPONSE',message:'Invalid host request'}}const req=checked.data;const started=this.now();
  this.logger.log('INFO','host','request',{trigger:req.trigger,sessionId:req.context.sessionId,humanHostPresent:req.context.humanHostPresent,humanHostState:req.context.humanHostState??''});
  let health;try{health=await this.provider.healthCheck()}catch(error){return this.failure(new HostEngineError('AI_OFFLINE'),req.trigger)}
  if(!health.available)return this.failure(new HostEngineError('AI_OFFLINE'),req.trigger);
  if(!health.model||health.modelAvailable===false)return this.failure(new HostEngineError('MODEL_NOT_FOUND'),req.trigger);
  try{const prompt=await this.prompts.build(req);const ai=await this.provider.generate({...prompt,temperature:0.75,maxTokens:260});const parsed=parseHostResponseWithDiagnostics(ai.text);const response=parsed.response;if(req.context.currentProduct&&this.validateProductSpeech&&!this.validateProductSpeech(response.speech,req.context.currentProduct))throw new HostEngineError('INVALID_AI_RESPONSE','Product response failed factual policy');const commands=hostResponseToCommands(response);const latencyMs=ai.latencyMs||this.now()-started;this.logger.log('INFO','host','response_validated',{trigger:req.trigger,provider:ai.provider,model:ai.model,latencyMs,...(parsed.normalizations.length?{normalizations:parsed.normalizations}:{}),response,commands});return{ok:true,response,commands,provider:ai.provider,model:ai.model,latencyMs}}
  catch(error){const classified=error instanceof HostEngineError?error:classifyProviderError(error);return this.failure(classified,req.trigger,{provider:health.provider,model:health.model??'',latencyMs:this.now()-started})}
 }
 private failure(error:HostEngineError,trigger:HostTrigger,details:Record<string,unknown>={}){this.logger.log('ERROR','host','generation_failed',{trigger,code:error.code,...details});return{ok:false as const,code:error.code,message:error.message}}
}
