import {z} from 'zod';
import {apiError} from './api-error.js';
import type {TokenResponse,UserProfile} from '../types.js';
import {RequestPolicy} from './request-policy.js';
const TokenSchema=z.object({access_token:z.string().min(1),expires_in:z.number().int().positive(),open_id:z.string().min(1),refresh_token:z.string().min(1),refresh_expires_in:z.number().int().positive(),scope:z.string(),token_type:z.literal('Bearer')}).passthrough();
const ProfileSchema=z.object({data:z.object({user:z.object({open_id:z.string().min(1),display_name:z.string().optional(),avatar_url:z.string().url().optional()}).passthrough()}),error:z.object({code:z.string().optional()}).passthrough().optional()}).passthrough();
export interface TikTokApiConfig {clientKey:string;clientSecret:string;redirectUri:string;requestTimeoutMs:number}
export class TikTokApiClient {constructor(private readonly config:TikTokApiConfig,private readonly request:typeof fetch=fetch,private readonly profilePolicy=new RequestPolicy({maxRetries:2})){}
 async exchangeCode(code:string,verifier:string):Promise<TokenResponse>{return this.tokenRequest({client_key:this.config.clientKey,client_secret:this.config.clientSecret,code,grant_type:'authorization_code',redirect_uri:this.config.redirectUri,code_verifier:verifier})}
 async refresh(refreshToken:string):Promise<TokenResponse>{return this.tokenRequest({client_key:this.config.clientKey,client_secret:this.config.clientSecret,grant_type:'refresh_token',refresh_token:refreshToken})}
 async getUserProfile(accessToken:string):Promise<UserProfile>{let response:Response;try{response=await this.profilePolicy.run(()=>this.request('https://open.tiktokapis.com/v2/user/info/?fields=open_id%2Cdisplay_name%2Cavatar_url',{method:'GET',headers:{Authorization:`Bearer ${accessToken}`},signal:AbortSignal.timeout(this.config.requestTimeoutMs)}),r=>{const retry=r.status===429||(r.status>=500&&r.status<=599);const header=r.headers.get('retry-after');const retryAfterMs=header&&/^\d+$/.test(header)?Math.min(4_000,Number(header)*1000):undefined;return{retry,...(retryAfterMs===undefined?{}:{retryAfterMs})}})}catch(error){throw apiError(error instanceof Error&&error.name==='TimeoutError'?'TIMEOUT':'NETWORK_ERROR','user-info')};if(!response.ok)throw httpError(response,'user-info');let raw:unknown;try{raw=await response.json()}catch{throw apiError('INVALID_RESPONSE','user-info')};const parsed=ProfileSchema.safeParse(raw);if(!parsed.success||parsed.data.error&&parsed.data.error.code!=='ok')throw apiError('INVALID_RESPONSE','user-info');const user=parsed.data.data.user;return{open_id:user.open_id,...(user.display_name===undefined?{}:{display_name:user.display_name}),...(user.avatar_url===undefined?{}:{avatar_url:user.avatar_url})}}
 private async tokenRequest(body:Record<string,string>):Promise<TokenResponse>{let response:Response;try{response=await this.request('https://open.tiktokapis.com/v2/oauth/token/',{method:'POST',headers:{'Content-Type':'application/x-www-form-urlencoded','Cache-Control':'no-cache'},body:new URLSearchParams(body),signal:AbortSignal.timeout(this.config.requestTimeoutMs)})}catch(error){throw apiError(error instanceof Error&&error.name==='TimeoutError'?'TIMEOUT':'NETWORK_ERROR','oauth-token')};if(!response.ok)throw httpError(response,'oauth-token');let raw:unknown;try{raw=await response.json()}catch{throw apiError('INVALID_RESPONSE','oauth-token')};const parsed=TokenSchema.safeParse(raw);if(!parsed.success)throw apiError('INVALID_RESPONSE','oauth-token');return parsed.data}
}
function httpError(response:Response,source:string){const retryHeader=response.headers.get('retry-after');const retryAfterMs=retryHeader&&/^\d+$/.test(retryHeader)?Math.min(300_000,Number(retryHeader)*1000):undefined;const code=response.status===401?'UNAUTHORIZED':response.status===403?'FORBIDDEN':response.status===429?'RATE_LIMITED':response.status===400?'INVALID_REQUEST':response.status===404?'NOT_SUPPORTED':'UNKNOWN';return apiError(code,source,retryAfterMs)}
