import {AudienceEngine} from '../../audience-engine/src/index.js';
import {MockAvatarRuntimeAdapter,AvatarEngine} from '../../avatar-engine/src/index.js';
import {BroadcastEngine,MockBroadcastOutputAdapter} from '../../broadcast-engine/src/index.js';
import {LiveShowDirector} from '../../live-continuity/src/index.js';
import {LiveRuntime} from '../../live-runtime/src/index.js';
import {DuckingController,MusicPlayer,type MusicTrack} from '../../music-engine/src/index.js';
import {ToolGate,DecisionIntelligence,DeterministicDecisionProvider,OutputJudge,verifiedProductAnswer,type DecisionProvider} from '../../decision-intelligence/src/index.js';
import {ProductCatalog,ProductContextBuilder,ProductSchema,type Product,type ProductRepository} from '../../product-engine/src/index.js';
import {PersonalityManager} from '../../personality-engine/src/index.js';
import {KnowledgeRouter} from '../../knowledge-engine/src/index.js';
import {VirtualClock} from './virtual-clock.js';
import {hostResponseToCommands} from '../../host-engine/src/index.js';
import type {HostEngine} from '../../host-engine/src/index.js';
import type {HostContext,HostGenerationResult,HostRequest,HostResponse} from '../../shared-types/src/index.js';
import {VoiceEngine,DEFAULT_VOICE_CONFIG,type TTSProvider,type TTSRequest,type TTSResult,type VoiceControllerEvent} from '../../voice-engine/src/index.js';
import {getRehearsalScenario,REHEARSAL_SCENARIOS} from './scenarios.js';
import {parseRehearsalScenario} from './scenario-schema.js';
import type {RehearsalDecisionRecord,RehearsalEvent,RehearsalFailure,RehearsalInvariant,RehearsalMode,RehearsalReport,RehearsalScenario,RehearsalSnapshot,RehearsalTtsRecord} from './types.js';

const FIXTURE_PRODUCTS:Product[]=[
  ProductSchema.parse({id:'fixture-mug',name:'Produk Mug',category:'rumah tangga',price:45000,currency:'IDR',promoPrice:null,description:'Mug untuk minuman sehari-hari.',benefits:['Mudah dibawa','Pegangan nyaman'],specifications:['Kapasitas 350 ml','Bahan stainless steel'],variants:['Hitam','Putih'],stock:12,images:[],status:'ACTIVE',sellingPoints:['Desain ringkas'],targetAudience:[],preferredTalkingPoints:['Mudah digunakan'],forbiddenClaims:[],priority:50}),
  ProductSchema.parse({id:'fixture-bottle',name:'Produk Botol',category:'rumah tangga',price:60000,currency:'IDR',promoPrice:null,description:'Botol untuk penggunaan sehari-hari.',benefits:['Mudah dibersihkan'],specifications:['Kapasitas 500 ml'],variants:['Biru','Hijau'],stock:7,images:[],status:'ACTIVE',sellingPoints:['Mudah dibersihkan'],targetAudience:[],preferredTalkingPoints:['Praktis'],forbiddenClaims:[],priority:45}),
];
class FixtureRepository implements ProductRepository {private values=new Map(FIXTURE_PRODUCTS.map(p=>[p.id,p]));list(){return[...this.values.values()]}get(id:string){return this.values.get(id)??null}save(product:Product){const p=ProductSchema.parse(product);this.values.set(p.id,p);return p}}
class SimulatedTtsProvider implements TTSProvider {
  readonly id='rehearsal-mock';failNext=false;constructor(private readonly now:()=>number){}
  async isAvailable(){return true}async listVoices(){return[{id:'rehearsal-id',name:'Rehearsal Indonesian',language:'id-ID',available:true}]}
  async synthesize(request:TTSRequest):Promise<TTSResult>{const createdAt=this.now();if(this.failNext){this.failNext=false;return{success:false,providerId:this.id,durationMs:null,format:'wav',sampleRate:null,channels:null,createdAt,error:'SIMULATED_TTS_FAILURE',errorCode:'TTS_FAILURE'}}return{success:true,providerId:this.id,audioRef:`simulation://voice/${request.id}`,durationMs:Math.max(650,request.text.length*48),format:'wav',sampleRate:24000,channels:1,createdAt,actualVoice:'rehearsal-id',actualLanguage:'id-ID'}}
}
class RehearsalDecisionProvider implements DecisionProvider {
  readonly id='rehearsal-deterministic';available=true;constructor(private readonly base=new DeterministicDecisionProvider()){}
  async isAvailable(){return this.available}async decide(request:import('../../decision-intelligence/src/index.js').DecisionRequest,_signal?:AbortSignal){return this.base.decide(request)}
}
const success=(response:HostResponse,provider='mock-llm'):HostGenerationResult=>({ok:true,response,commands:hostResponseToCommands(response),provider,model:provider==='mock-llm'?'mock/deterministic':'configured',latencyMs:0});
const makeResponse=(speech:string,intent:HostResponse['intent']='answer'):HostResponse=>({speech,emotion:'friendly',gesture:intent==='greeting'?'wave':'talking',intent});
const judgedStatus=(status:string):'PASS'|'REJECT'|'FAIL_CLOSED'=>status==='PASS'?'PASS':status==='FAIL_CLOSED'?'FAIL_CLOSED':'REJECT';
function mockResponse(request:HostRequest,catalog:ProductCatalog,product:Product|null):HostGenerationResult {
  const intent=request.context.audienceContext?.intent??'UNKNOWN';const text=request.context.audienceContext?.comment??request.instruction??'';
  if(intent==='GREETING')return success(makeResponse('Hai, selamat datang di simulasi live Pipip.','greeting'));
  if(intent==='JOKE')return success(makeResponse('Aku sedang latihan jadi host, semoga punchline-ku ikut lulus rehearsal.','comedy'));
  if(intent==='PRODUCT_RECOMMENDATION'&&product)return success(makeResponse(`Menurut katalog, ${product.name} memiliki manfaat ${product.benefits[0]??'yang tercatat pada katalog'}.`,'product_explanation'));
  if(intent==='PRODUCT_QUESTION'&&product)return success(makeResponse(`${product.name} tercatat sebagai ${product.category||'produk'}; manfaat yang tersedia adalah ${product.benefits[0]??'belum dicatat'}.`,'product_explanation'));
  if(intent==='VARIANT_QUESTION'&&product)return success(makeResponse(product.variants.length?`Varian ${product.name} yang tercatat: ${product.variants.join(' dan ')}.`:`Informasi varian ${product.name} belum tersedia di katalog.`,'answer'));
  if(intent==='COMPARISON'&&product)return success(makeResponse(`Saya memiliki data katalog untuk ${product.name}. Untuk perbandingan yang akurat, produk lain juga perlu dipilih dari katalog.`,'answer'));
  if(intent==='REQUEST_DEMO'&&product)return success(makeResponse(`Kita bisa membahas ${product.name} memakai informasi yang tercatat di katalog.`,'product_explanation'));
  if(/(?:harga|price)/iu.test(text))return success(makeResponse('Maaf, harga belum tersedia pada katalog terverifikasi.'),'answer');
  if(/(?:stok|ready|tersedia)/iu.test(text))return success(makeResponse('Maaf, informasi stok belum tersedia pada katalog terverifikasi.'),'answer');
  return success(makeResponse('Terima kasih sudah ikut dalam simulasi live ini.'),'general_chat');
}

export interface LiveRehearsalOptions {mode?:RehearsalMode;hostEngine?:Pick<HostEngine,'generate'>;decisionProvider?:DecisionProvider;startTime?:number;maxRecords?:number;tiktokConfigured?:boolean;onUpdate?:(snapshot:RehearsalSnapshot)=>void}
export class LiveRehearsalEngine {
  private options:LiveRehearsalOptions;private current:RehearsalSnapshot={simulation:'SIMULATION',running:false,scenarioId:null,scenarioName:null,simulatedTimeMs:0,currentState:'IDLE',currentEvent:null,pipipState:'READY',currentDecision:'—',currentProduct:null,musicState:'STOPPED',ttsState:'IDLE',errors:0,invariantFailures:0,report:null};private cancelRequested=false;private lastReport:RehearsalReport|null=null;
  constructor(options:LiveRehearsalOptions={}){this.options=options}
  snapshot():RehearsalSnapshot{return structuredClone(this.current)}
  stop(){this.cancelRequested=true;this.publish({...this.current,running:false,currentState:'STOPPING'})}
  clearReport(){if(this.current.running)throw new Error('Cannot clear a running rehearsal');this.lastReport=null;this.publish({...this.current,report:null,errors:0,invariantFailures:0});return this.snapshot()}
  reset(){this.cancelRequested=true;this.lastReport=null;this.publish({simulation:'SIMULATION',running:false,scenarioId:null,scenarioName:null,simulatedTimeMs:0,currentState:'IDLE',currentEvent:null,pipipState:'READY',currentDecision:'—',currentProduct:null,musicState:'STOPPED',ttsState:'IDLE',errors:0,invariantFailures:0,report:null});return this.snapshot()}
  async run(id:string,mode:RehearsalMode=this.options.mode??'MOCK_LLM'):Promise<RehearsalReport>{const scenario=getRehearsalScenario(id);if(!scenario)throw new Error('Unknown rehearsal scenario');return this.runScenario(scenario,mode)}
  async runDefinition(value:unknown,mode:RehearsalMode=this.options.mode??'MOCK_LLM'):Promise<RehearsalReport>{return this.runScenario(parseRehearsalScenario(value),mode)}
  async runAll(mode:RehearsalMode=this.options.mode??'MOCK_LLM'):Promise<RehearsalReport[]>{const reports:RehearsalReport[]=[];this.cancelRequested=false;for(const scenario of REHEARSAL_SCENARIOS){if(this.cancelRequested)break;reports.push(await this.runScenario(scenario,mode))}return reports}
  private async runScenario(scenario:RehearsalScenario,mode:RehearsalMode):Promise<RehearsalReport>{
    if(this.current.running)throw new Error('A rehearsal is already running');this.cancelRequested=false;
    const virtualClock=new VirtualClock(this.options.startTime??1_800_000_000_000);const sessionStart=virtualClock.now();let now=sessionStart;const clock=()=>virtualClock.now();const advance=(at:number)=>{virtualClock.advanceTo(sessionStart+at);now=virtualClock.now()};const max=Math.max(100,Math.min(5000,this.options.maxRecords??1200));
    const catalog=new ProductCatalog(new FixtureRepository());const products=new ProductContextBuilder();const audience=new AudienceEngine({maxQueue:100,ttlMs:120_000,now:clock});const decisionProvider=this.options.decisionProvider??new RehearsalDecisionProvider();const decisions=new DecisionIntelligence({primary:decisionProvider,timeoutMs:500,now:clock});const knowledge=new KnowledgeRouter([],undefined,0.65);const outputJudge=new OutputJudge();const toolGate=new ToolGate();const personality=new PersonalityManager();const showDirector=new LiveShowDirector();
    const ttsRecords:RehearsalTtsRecord[]=[],voiceEvents:VoiceControllerEvent[]=[];const ttsProvider=new SimulatedTtsProvider(clock);const voice=new VoiceEngine([ttsProvider],{...DEFAULT_VOICE_CONFIG,language:'id-ID',voice:'auto',cacheEnabled:false},undefined,event=>voiceEvents.push(event),clock);
    let track:MusicTrack={id:'simulation-track',title:'Simulated local track',artist:null,filePath:'simulation://music/track',durationMs:240_000,category:'BACKGROUND',genre:null,mood:[],themes:[],lyricsId:null,enabled:true};let musicFailure=false;const musicEvents:Array<{atMs:number;action:string;state:string;musicLevel:number;ducked:boolean}>=[];const duck=new DuckingController({backgroundMusicLevel:.58,musicDuringSpeech:.12,fadeDurationMs:0,fullSongEnabled:true,loopBackground:false,maxRetries:0,watchdogGraceMs:0,duckingEnabled:true,attackMs:0,releaseMs:0,minimumMusicLevel:0},clock);const music=new MusicPlayer(clock,event=>{musicEvents.push({atMs:Math.max(0,now-sessionStart),action:event.type,state:event.playback.playbackState,musicLevel:duck.getState().musicLevel,ducked:duck.getState().speechActive})});
    const avatarRuntime=new MockAvatarRuntimeAdapter();const avatar=new AvatarEngine(avatarRuntime,{now:clock});await avatar.connect();let currentProductId:string|null='fixture-mug';let avatarFailure=false;let currentHostState='IDLE';let failRuntimeStart=false;
    const runtime=new LiveRuntime({orchestrator:{start(){if(failRuntimeStart)throw new Error('injected runtime failure')},stop(){},pause(){},resume(){},getState(){return null}},voice:{speak:input=>voice.speak(input),stop:clear=>voice.controller.stop(clear),pause:()=>voice.controller.pause(),resume:()=>voice.controller.resume(),setHumanTakeover:value=>voice.controller.setHumanTakeover(value),emergencyStop:()=>voice.controller.emergencyStop(),resetEmergency:()=>voice.controller.resetEmergency(),getStatus:()=>voice.getStatus()},music:{stop:()=>music.stop(),pause:()=>music.pause(),resume:()=>music.resume(),getStatus:()=>({playbackState:music.getState()?.playbackState??'STOPPED',playing:music.getState()?.playbackState==='PLAYING'})},avatar:{humanTakeover:value=>avatar.humanTakeover(value),emergencyStop:()=>avatar.emergencyStop(),resume:()=>avatar.resume(),snapshot:()=>avatar.snapshot()},audience:{getStatus:()=>'ready',getQueueDepth:()=>audience.size},product:{getStatus:()=>'ready',hasProduct:id=>catalog.get(id)!==null},selectProduct:id=>{currentProductId=id;return true},playMusic:()=>music.play(track,'BACKGROUND'),duckMusic:()=>{duck.duckForVoice()},restoreMusic:()=>{duck.restoreMusic()}},{now:clock,sessionId:()=>`rehearsal-${scenario.id}`});
    const broadcastAdapter=new MockBroadcastOutputAdapter();const broadcast=new BroadcastEngine(broadcastAdapter,id=>catalog.get(id),{now:clock});
    const report:RehearsalReport={simulation:'SIMULATION',scenarioId:scenario.id,scenarioName:scenario.name,mode,durationMs:scenario.durationMs,eventCount:0,events:[],responses:[],ignoredEvents:0,queuedEvents:0,llmCalls:0,llmResponses:0,model:null,deterministicDecisions:0,fallbacks:0,decisions:[],knowledge:[],observations:[],outputJudge:[],productValidation:[],tts:ttsRecords,music:musicEvents,takeovers:[],emergencies:[],showActions:[],errors:[],invariants:[],latency:{averageMs:0,p95Ms:0,hostAverageMs:0,hostP95Ms:0,ttsGenerationAverageMs:0,responseAverageMs:0},finalState:'IDLE',audienceSource:'simulator',tiktokState:this.options.tiktokConfigured?'NOT_AVAILABLE':'NOT_CONFIGURED',toolExecutions:0};
    const invariant=(id:string,passed:boolean,detail:string)=>{const prior=report.invariants.find(x=>x.id===id);if(prior){prior.passed=prior.passed&&passed;if(!passed)prior.detail=detail}else report.invariants.push({id,passed,detail});if(!passed)this.current.invariantFailures++};
    let currentFailure:RehearsalFailure|null=null;let productUnavailable=false;let emergencyLatched=false;let queuedSynthetic=0;let resumeCooldownUntil=-1;const latencies:number[]=[];const hostLatencies:number[]=[];
    const emit=()=>this.publish({...this.current,running:true,scenarioId:scenario.id,scenarioName:scenario.name,simulatedTimeMs:Math.max(0,now-sessionStart),currentState:runtime.snapshot().state,currentProduct:currentProductId?catalog.get(currentProductId)?.name??null:null,musicState:music.getState()?.playbackState??'STOPPED',ttsState:voice.getStatus().state,errors:report.errors.length,invariantFailures:report.invariants.filter(x=>!x.passed).length,report:null});
    const syncBroadcast=async()=>{await broadcast.observeRuntime(runtime.snapshot());const state=music.getState();await broadcast.observeMusic({state:state?.playbackState==='PLAYING'?'BACKGROUND':state?.playbackState==='PAUSED'?'PAUSED':'STOPPED',title:state?.title??null,artist:state?.artist??null,progressMs:state?.positionMs??null,durationMs:state?.durationMs??null,volume:duck.getState().musicLevel,ducked:duck.getState().speechActive});const av=avatar.snapshot();await broadcast.observeAvatar({state:av.state,emotion:av.emotion,expression:av.expression,gesture:av.gesture});};
    const getProduct=(id:string|null|undefined)=>!productUnavailable&&id?catalog.get(id):null;
    const addError=(code:RehearsalFailure|string,subsystem:string)=>{report.errors.push({atMs:Math.max(0,now-sessionStart),code,subsystem});runtime.recordError(subsystem,code,true);};
    const processSpeech=async(eventId:string,speech:string,response:HostResponse,queuedAt:number)=>{
      if(emergencyLatched||runtime.snapshot().humanTakeover){report.queuedEvents++;invariant('human-or-emergency-blocks-output',false,'Attempted to speak while human control or emergency latch was active');return false}
      if(currentFailure==='TTS_FAILURE'){ttsProvider.failNext=true;currentFailure=null}
      if(avatarFailure){avatarRuntime.failWith(new Error('simulated avatar unavailable'));avatarFailure=false}
      let avatarAccepted=false;try{avatarAccepted=await avatar.handleHostResponse(response,'COMMENT',personality.getActive().id)}catch{avatarAccepted=false}if(avatar.snapshot().state==='ERROR')avatarAccepted=false;runtime.observeAvatar(avatarAccepted);if(!avatarAccepted){addError('AVATAR_FAILURE','avatar');avatarRuntime.failWith(null);try{await avatar.disconnect();await avatar.connect()}catch{}}
      runtime.observeHostResponse('REHEARSAL_RESPONSE');const eventStart=voiceEvents.length;const accepted=await runtime.routeAction({type:'SPEAK',text:speech,language:'id-ID'});if(!accepted){ttsRecords.push({eventId,language:'id-ID',status:'CANCELLED',queueTimeMs:Math.max(0,now-queuedAt),generationTimeMs:0,speechDurationMs:null,provider:'rehearsal-mock'});return false}
      let ready:Extract<VoiceControllerEvent,{type:'VOICE_READY'}>|undefined;let failed:Extract<VoiceControllerEvent,{type:'VOICE_TEXT_ONLY'}>|undefined;
      for(let i=0;i<40;i++){await Promise.resolve();const latest=voiceEvents.slice(eventStart).find(x=>x.type==='VOICE_READY'||x.type==='VOICE_TEXT_ONLY');if(latest?.type==='VOICE_READY'){ready=latest;break}if(latest?.type==='VOICE_TEXT_ONLY'){failed=latest;break}}
      if(failed||!ready){runtime.observeSpeech(false);ttsRecords.push({eventId,language:'id-ID',status:'FAILED',queueTimeMs:Math.max(0,now-queuedAt),generationTimeMs:0,speechDurationMs:null,provider:'rehearsal-mock'});addError('TTS_FAILURE','tts');return false}
      const started=now;voice.controller.markPlaybackStarted(ready.requestId);currentHostState='SPEAKING';runtime.observeSpeechStarted();if(music.getState()?.playbackState==='PLAYING'){duck.duckForVoice();musicEvents.push({atMs:Math.max(0,now-sessionStart),action:'MUSIC_DUCK',state:'PLAYING',musicLevel:duck.getState().musicLevel,ducked:true})}if(avatar.snapshot().state!=='ERROR')await avatar.speechStarted(speech);voice.controller.markPlaybackComplete(ready.requestId,true);runtime.observeSpeech(true);if(avatar.snapshot().state!=='ERROR')await avatar.speechEnded();currentHostState='IDLE';if(duck.getState().speechActive){duck.restoreMusic();musicEvents.push({atMs:Math.max(0,now-sessionStart),action:'MUSIC_RESTORE',state:music.getState()?.playbackState??'STOPPED',musicLevel:duck.getState().musicLevel,ducked:false})}
      ttsRecords.push({eventId,language:'id-ID',status:'READY',queueTimeMs:Math.max(0,started-queuedAt),generationTimeMs:Math.max(0,ready.synthesisLatencyMs),speechDurationMs:ready.durationMs,provider:ready.providerId});report.responses.push({eventId,text:speech});invariant('simulated-speech-is-id-id',ready.actualLanguage.toLocaleLowerCase('en-US')==='id-id','Rehearsal TTS did not report id-ID');return true;
    };
    const beginPendingSpeech=async(eventId:string)=>{const speech='Simulated speech active at the emergency boundary.';const response=makeResponse(speech);const before=voiceEvents.length;runtime.observeHostResponse('EMERGENCY_BOUNDARY_SPEECH');const accepted=await runtime.routeAction({type:'SPEAK',text:speech,language:'id-ID'});if(!accepted)return;let ready:Extract<VoiceControllerEvent,{type:'VOICE_READY'}>|undefined;for(let i=0;i<40;i++){await Promise.resolve();const found=voiceEvents.slice(before).find(x=>x.type==='VOICE_READY');if(found?.type==='VOICE_READY'){ready=found;break}}if(ready){voice.controller.markPlaybackStarted(ready.requestId);runtime.observeSpeechStarted();currentHostState='SPEAKING';await avatar.speechStarted(speech);ttsRecords.push({eventId,language:'id-ID',status:'CANCELLED',queueTimeMs:0,generationTimeMs:ready.synthesisLatencyMs,speechDurationMs:ready.durationMs,provider:ready.providerId})}};
    const generate=async(request:HostRequest,product:Product|null,eventId:string,queuedAt:number)=>{
      report.llmCalls++;let result:HostGenerationResult;
      if(currentFailure==='OLLAMA_TIMEOUT'||currentFailure==='OLLAMA_UNAVAILABLE'){const code=currentFailure;currentFailure=null;report.errors.push({atMs:Math.max(0,now-sessionStart),code,subsystem:'ollama'});result={ok:false,code:code==='OLLAMA_TIMEOUT'?'AI_TIMEOUT':'AI_OFFLINE',message:code};}
      else if(currentFailure==='MALFORMED_LLM_OUTPUT'){currentFailure=null;report.errors.push({atMs:Math.max(0,now-sessionStart),code:'MALFORMED_LLM_OUTPUT',subsystem:'ollama'});result={ok:false,code:'INVALID_AI_RESPONSE',message:'Simulated malformed output'};}
      else if(mode==='REAL_OLLAMA'){if(!this.options.hostEngine){report.errors.push({atMs:Math.max(0,now-sessionStart),code:'OLLAMA_UNAVAILABLE',subsystem:'ollama'});result={ok:false,code:'AI_OFFLINE',message:'REAL_OLLAMA host is not configured'};}else{try{result=await this.options.hostEngine.generate(request)}catch{report.errors.push({atMs:Math.max(0,now-sessionStart),code:'OLLAMA_UNAVAILABLE',subsystem:'ollama'});result={ok:false,code:'AI_ERROR',message:'Host generation failed safely'}}}}
      else result=mockResponse(request,catalog,product);
      if(this.cancelRequested)return false;if(result.ok){hostLatencies.push(Math.max(0,result.latencyMs));report.llmResponses++;report.model=result.model}
      if(!result.ok){if(mode==='REAL_OLLAMA')this.current.pipipState=result.code==='MODEL_NOT_FOUND'?'MODEL_NOT_FOUND':result.code==='AI_TIMEOUT'?'TIMEOUT':'OLLAMA_UNAVAILABLE';const fallback=product&&request.context.audienceContext?.intent==='PRICE_QUESTION'?verifiedProductAnswer('PRICE_QUESTION',product):product&&request.context.audienceContext?.intent==='STOCK_QUESTION'?verifiedProductAnswer('STOCK_QUESTION',product):'Maaf, host AI sedang tidak tersedia. Saya tidak akan menebak informasi produk yang belum terverifikasi.';const response=makeResponse(fallback??'Informasi produk belum tersedia di katalog.','answer');report.fallbacks++;const judgeFailure=currentFailure==='OUTPUT_JUDGE_FAILURE';const judgment=judgeFailure?{status:'FAIL_CLOSED' as const,reasonCode:'OUTPUT_JUDGE_FAILURE'}:outputJudge.judge(response.speech,product?products.build(product):null);if(judgeFailure){currentFailure=null;report.errors.push({atMs:Math.max(0,now-sessionStart),code:'OUTPUT_JUDGE_FAILURE',subsystem:'output-judge'})}report.outputJudge.push({eventId,status:judgedStatus(judgment.status),reasonCode:judgment.reasonCode,speechReachedTts:judgment.status==='PASS'});if(judgment.status!=='PASS')return false;return processSpeech(eventId,response.speech,response,queuedAt)}
      const judgment=currentFailure==='OUTPUT_JUDGE_FAILURE'?{status:'FAIL_CLOSED' as const,reasonCode:'OUTPUT_JUDGE_FAILURE'}:outputJudge.judge(result.response.speech,product?products.build(product):null);if(currentFailure==='OUTPUT_JUDGE_FAILURE'){report.errors.push({atMs:Math.max(0,now-sessionStart),code:'OUTPUT_JUDGE_FAILURE',subsystem:'output-judge'});currentFailure=null}
      report.outputJudge.push({eventId,status:judgedStatus(judgment.status),reasonCode:judgment.reasonCode,speechReachedTts:false});if(judgment.status!=='PASS'){report.ignoredEvents++;ttsRecords.push({eventId,language:'id-ID',status:'REJECTED',queueTimeMs:Math.max(0,now-queuedAt),generationTimeMs:0,speechDurationMs:null,provider:'output-judge'});return false}report.outputJudge.at(-1)!.speechReachedTts=true;return processSpeech(eventId,result.response.speech,result.response,queuedAt);
    };
    this.current={simulation:'SIMULATION',running:true,scenarioId:scenario.id,scenarioName:scenario.name,simulatedTimeMs:0,currentState:'IDLE',currentEvent:null,pipipState:mode==='MOCK_LLM'||mode==='MOCK'?'MOCK_READY':'READY',currentDecision:'—',currentProduct:'Produk Mug',musicState:'STOPPED',ttsState:'IDLE',errors:0,invariantFailures:0,report:null};
    for(const [index,event] of scenario.events.entries()){
      if(this.cancelRequested)break;advance(event.atMs);report.eventCount++;if(report.events.length<max)report.events.push({...event});this.current.currentEvent=event.type;if(index<50||index%10===0)emit();report.observations.push({timestamp:now,eventId:`${scenario.id}-${index}`,event:event.type,state:runtime.snapshot().state,decision:null,provider:null,product:currentProductId,responseMode:null,confidence:null,latencyMs:null,ttsState:voice.getStatus().state,musicState:music.getState()?.playbackState??'STOPPED',takeover:runtime.snapshot().humanTakeover,emergency:runtime.snapshot().emergencyStopped,error:null,fallback:false});
      if(event.type==='LIVE_START'){failRuntimeStart=currentFailure==='RUNTIME_FAILURE';currentFailure=null;const s=await runtime.startSession();if(s.state==='ERROR')addError('RUNTIME_FAILURE','runtime');else{await broadcast.command('startPreview');await syncBroadcast()}invariant('session-starts-in-simulation',s.state==='RUNNING'||s.state==='ERROR','Live Runtime did not start or report injected failure');continue}
      if(event.type==='VIEWER_JOIN'||event.type==='FOLLOW'||event.type==='LIKE'||event.type==='GIFT'||event.type==='SYSTEM'){const eventId=`${scenario.id}-${index}`;const audienceType=event.type==='VIEWER_JOIN'?'NEW_VIEWER':event.type;const text=event.text??(event.type==='VIEWER_JOIN'?'synthetic viewer joined':`synthetic ${event.type.toLocaleLowerCase('en-US')} event`);const result=audience.ingest({source:'simulator',type:audienceType,text,timestamp:now,eventId});runtime.observeAudience(audienceType,result.accepted);const routed=await decisions.decide({eventType:audienceType,source:'simulator',text,intent:'UNKNOWN',liveState:runtime.snapshot().state,hostState:runtime.snapshot().humanTakeover?'HUMAN_TAKEOVER':currentHostState,timestamp:now});report.decisions.push({atMs:event.atMs,eventId,intent:'UNKNOWN',decision:routed.decision,route:routed.decision,provider:routed.provider,confidence:routed.confidence,requiresLlm:routed.requiresLlm,requiresHuman:routed.requiresHuman,toolAllowed:routed.toolAllowed,fallback:routed.provider==='fallback',latencyMs:routed.latencyMs??0,reasonCode:routed.reasonCode});report.knowledge.push({eventId,topic:'UNKNOWN',status:'UNKNOWN'});if(!result.accepted)report.ignoredEvents++;continue}
      if(event.type==='FAILURE'){const injected=event.failure??null;currentFailure=injected==='OLLAMA_MALFORMED_RESPONSE'?'MALFORMED_LLM_OUTPUT':injected==='AVATAR_RUNTIME_FAILURE'?'AVATAR_FAILURE':injected==='LIVE_RUNTIME_FAILURE'?'RUNTIME_FAILURE':injected;if(injected==='JEV_FAILURE'){if('available'in decisionProvider)(decisionProvider as RehearsalDecisionProvider).available=false;report.errors.push({atMs:event.atMs,code:'JEV_FAILURE',subsystem:'jev'})}if(currentFailure==='RUNTIME_FAILURE'){failRuntimeStart=true;addError(injected??currentFailure,'runtime')}if(currentFailure==='MUSIC_FAILURE')musicFailure=true;if(currentFailure==='AVATAR_FAILURE')avatarFailure=true;if(currentFailure==='PRODUCT_ENGINE_FAILURE'){productUnavailable=true;addError(currentFailure,'product-engine')}continue}
      if(event.type==='PRODUCT_DATA_UNAVAILABLE'){productUnavailable=true;report.productValidation.push({eventId:`${scenario.id}-${index}`,productId:null,verified:false,fact:'PRODUCT_DATA_UNAVAILABLE'});continue}
      if(event.type==='PRODUCT_CHANGE'){const product=getProduct(event.productId);if(!product){report.productValidation.push({eventId:`${scenario.id}-${index}`,productId:event.productId??null,verified:false,fact:'PRODUCT_NOT_FOUND'});addError('PRODUCT_ENGINE_FAILURE','product-engine');continue}currentProductId=product.id;await runtime.routeAction({type:'SELECT_PRODUCT',productId:product.id});runtime.observeProductSelected(product.id);await broadcast.observeProduct(product.id);report.productValidation.push({eventId:`${scenario.id}-${index}`,productId:product.id,verified:true,fact:'PRODUCT_ENGINE_CATALOG'});await syncBroadcast();continue}
      if(event.type==='MUSIC_START'){if(musicFailure){music.fail(track,'SIMULATED_MUSIC_FAILURE');musicFailure=false;addError('MUSIC_FAILURE','music-engine')}else{if(music.getState()?.playbackState==='PAUSED')music.resume();else music.play(track,'BACKGROUND');runtime.observeMusicStarted();duck.setMusicLevel(.58)}this.current.musicState=music.getState()?.playbackState??'STOPPED';await syncBroadcast();continue}
      if(event.type==='MUSIC_PAUSE'){music.pause();this.current.musicState=music.getState()?.playbackState??'STOPPED';await syncBroadcast();continue}
      if(event.type==='MUSIC_STOP'){music.stop();duck.fadeMusicOut();this.current.musicState='STOPPED';await syncBroadcast();continue}
      if(event.type==='HUMAN_TAKEOVER'){queuedSynthetic+=1;runtime.setQueueDepth(queuedSynthetic);await runtime.requestHumanTakeover();queuedSynthetic=0;await avatar.humanTakeover(true);this.current.currentState='HUMAN_TAKEOVER';report.takeovers.push({atMs:event.atMs,action:'TAKEOVER',state:runtime.snapshot().state});invariant('takeover-clears-queued-actions',runtime.snapshot().queueDepth===0,'Queued autonomous actions remained after takeover');const blockedAvatar=await runtime.routeAction({type:'AVATAR_COMMAND',gesture:'wave'});invariant('takeover-blocks-avatar-actions',!blockedAvatar,'Avatar command was accepted during human takeover');await syncBroadcast();continue}
      if(event.type==='AI_RESUME'){await runtime.releaseHumanTakeover();await avatar.humanTakeover(false);resumeCooldownUntil=now+5_000;report.takeovers.push({atMs:event.atMs,action:'RETURN_WITH_COOLDOWN',state:runtime.snapshot().state});await syncBroadcast();continue}
      if(event.type==='DEAD_AIR'){const action=showDirector.selectNext({now,activity:'WAIT',recentActivities:[],recentTopics:[],recentProducts:[],pendingAudience:0,pendingActions:0,availableProductIds:catalog.active().map(p=>p.id),musicAvailable:true,musicPlaying:false,lastMusicAt:null,sessionDurationMs:Math.max(0,now-sessionStart),timePeriod:'EVENING',paused:false,humanTakeover:false,stopped:false,afterSongPending:false});report.showActions.push({atMs:event.atMs,action:action.type,reason:action.reason??'none'});if(action.type==='PRODUCT'){currentProductId=action.productId??currentProductId;const p=getProduct(currentProductId);if(p){runtime.observeProductSelected(p.id);await broadcast.observeProduct(p.id)}}continue}
      if(event.type==='COMMENT'){
        const eventId=`${scenario.id}-${index}`;const audienceResult=audience.ingest({source:'simulator',type:'COMMENT',text:event.text??'',timestamp:now,eventId});runtime.observeAudience('COMMENT',audienceResult.accepted);const selected=getProduct(event.productId??currentProductId);const intent=audienceResult.intent;const knowledgeText=(event.text??'').toLocaleLowerCase('id-ID');const topic=/(aturan|kebijakan|boleh|dilarang|policy|guideline)/u.test(knowledgeText)?'PLATFORM_POLICY':/(harga|stok|varian|produk|barang|promo|spesifikasi|manfaat)/u.test(knowledgeText)?'PRODUCT':'GENERAL';const knowledgeRoute=await knowledge.route({query:event.text??'',topic,hasVerifiedProduct:Boolean(selected),market:'ID',platform:'tiktok'});report.knowledge.push({eventId,topic,status:knowledgeRoute.status});const decisionStarted=now;const decision=await decisions.decide({eventType:'COMMENT',source:'simulator',text:event.text??'',intent,productContext:selected?{productId:selected.id,verified:true}:undefined,liveState:emergencyLatched?'EMERGENCY_STOPPED':runtime.snapshot().state,hostState:runtime.snapshot().state==='HUMAN_TAKEOVER'?'HUMAN_TAKEOVER':currentHostState,timestamp:now});const latency=Math.max(0,now-decisionStarted);latencies.push(latency);report.decisions.push({atMs:event.atMs,eventId,intent,decision:decision.decision,route:decision.decision,provider:decision.provider,confidence:decision.confidence,requiresLlm:decision.requiresLlm,requiresHuman:decision.requiresHuman,toolAllowed:decision.toolAllowed,fallback:decision.provider==='fallback',latencyMs:latency,reasonCode:decision.reasonCode});const observation=report.observations.at(-1);if(observation){observation.decision=decision.decision;observation.provider=decision.provider;observation.responseMode=audienceResult.mode;observation.confidence=decision.confidence;observation.latencyMs=latency;observation.fallback=decision.provider==='fallback'}if(decision.provider==='fallback')report.fallbacks++;this.current.currentDecision=decision.decision;if(decision.decision==='IGNORE'||!audienceResult.accepted){report.ignoredEvents++;continue}if(decision.decision==='QUEUE'){report.queuedEvents++;continue}if(emergencyLatched||runtime.snapshot().humanTakeover){report.queuedEvents++;continue}if(now<resumeCooldownUntil){report.queuedEvents++;report.showActions.push({atMs:event.atMs,action:'WAIT',reason:'takeover_resume_cooldown'});invariant('takeover-return-cooldown-respected',true,'AI response remained queued during return cooldown');continue}
        if(decision.decision==='DETERMINISTIC'){report.deterministicDecisions++;if(intent==='PRICE_QUESTION'||intent==='STOCK_QUESTION'){const responseText=selected?verifiedProductAnswer(intent,selected):null;const safeProduct=selected?products.build(selected):null;const speech=responseText??(intent==='PRICE_QUESTION'?'Maaf, harga produk itu belum tersedia di katalog terverifikasi.':'Maaf, informasi stok produk itu belum tersedia di katalog terverifikasi.');const response=makeResponse(speech);const judged=currentFailure==='OUTPUT_JUDGE_FAILURE'?{status:'FAIL_CLOSED' as const,reasonCode:'OUTPUT_JUDGE_FAILURE'}:outputJudge.judge(speech,safeProduct);if(currentFailure==='OUTPUT_JUDGE_FAILURE'){report.errors.push({atMs:Math.max(0,now-sessionStart),code:'OUTPUT_JUDGE_FAILURE',subsystem:'output-judge'});currentFailure=null}report.outputJudge.push({eventId,status:judgedStatus(judged.status),reasonCode:judged.reasonCode,speechReachedTts:judged.status==='PASS'});report.productValidation.push({eventId,productId:selected?.id??null,verified:Boolean(selected),fact:intent});invariant(intent==='PRICE_QUESTION'?'unknown-price-not-invented':'unknown-stock-not-invented',Boolean(selected)||!/(?:Rp\s*\d|\b\d+\s*(?:unit|pcs|buah)\b)/iu.test(speech),'Unknown catalog fact became a numeric claim');if(judged.status==='PASS')await processSpeech(eventId,speech,response,now);else ttsRecords.push({eventId,language:'id-ID',status:'REJECTED',queueTimeMs:0,generationTimeMs:0,speechDurationMs:null,provider:'output-judge'})}continue}
        if(decision.decision==='LLM_FAST'||decision.decision==='LLM_STRONG'){
          if(!audienceResult.accepted)continue;const action=showDirector.selectNext({now,activity:'AUDIENCE_INTERACTION',recentActivities:['AUDIENCE_INTERACTION'],recentTopics:[],recentProducts:[],pendingAudience:1,pendingActions:0,availableProductIds:catalog.active().map(p=>p.id),musicAvailable:true,musicPlaying:music.getState()?.playbackState==='PLAYING',lastMusicAt:null,sessionDurationMs:Math.max(0,now-sessionStart),timePeriod:'EVENING',paused:false,humanTakeover:false,stopped:false,afterSongPending:false});report.showActions.push({atMs:event.atMs,action:action.type,reason:action.reason??'none'});
          const contextProduct=selected?products.build(selected):undefined;const request:HostRequest={type:'HOST_RESPONSE',trigger:'COMMENT',context:{sessionId:`rehearsal-${scenario.id}`,recentConversation:[],humanHostPresent:false,currentScene:'AVATAR',...(contextProduct?{currentProduct:contextProduct}:{}),audienceContext:{intent,mode:audienceResult.mode,comment:event.text??''},personality:personality.getActive()},instruction:`Respond briefly to this simulated comment. Use only verified fixture data. intent=${intent}`};const successSpeech=await generate(request,selected,eventId,now);if(successSpeech)report.llmCalls&&(report.decisions.at(-1)!.provider=mode==='MOCK_LLM'||mode==='MOCK'?'mock-llm':'ollama');continue
        }
        if(decision.decision==='ESCALATE'){report.queuedEvents++;continue}
      }
      if(event.type==='EMERGENCY_STOP'){const from=event.fromState??(runtime.snapshot().humanTakeover?'HUMAN_TAKEOVER':music.getState()?.playbackState==='PLAYING'?'MUSIC':'QUEUE');if(from==='HUMAN_TAKEOVER'&&!runtime.snapshot().humanTakeover)await runtime.requestHumanTakeover();if(from==='MUSIC'&&music.getState()?.playbackState!=='PLAYING')music.play(track,'BACKGROUND');if(from==='QUEUE'){runtime.setQueueDepth(2)}if(from==='AVATAR_COMMAND')await runtime.routeAction({type:'AVATAR_COMMAND',gesture:'wave'});if(from==='PRODUCT_RESPONSE'){const p=getProduct(currentProductId);if(p){const answer=verifiedProductAnswer('PRICE_QUESTION',p);if(answer)await processSpeech(`${scenario.id}-${index}-product`,answer,makeResponse(answer),now)}}if(from==='SPEAKING'&&!emergencyLatched)await beginPendingSpeech(`${scenario.id}-${index}-speech`);if(from==='HUMAN_TAKEOVER'&&!runtime.snapshot().humanTakeover)await runtime.requestHumanTakeover();const before=runtime.snapshot();await runtime.emergencyStop();emergencyLatched=true;await broadcast.observeRuntime(runtime.snapshot());const blocked=await runtime.routeAction({type:'SPEAK',text:'blocked after emergency',language:'id-ID'});const stopped=runtime.snapshot().emergencyStopped&&voice.getStatus().emergencyStopped&&music.getState()?.playbackState!=='PLAYING'&&avatar.snapshot().emergencyStopped&&!blocked&&runtime.snapshot().queueDepth===0;report.emergencies.push({atMs:event.atMs,fromState:from,stopped,resetRequired:runtime.snapshot().emergencyStopped});if(!stopped)addError('EMERGENCY_STOP_FAILED','runtime');invariant('emergency-stop-wins',stopped,`Emergency stop from ${from} did not stop every simulated output`);invariant('emergency-reset-required',runtime.snapshot().emergencyStopped,'Emergency stop did not remain latched');if(before.state==='HUMAN_TAKEOVER')report.takeovers.push({atMs:event.atMs,action:'EMERGENCY_PREEMPTS_TAKEOVER',state:runtime.snapshot().state});continue}
      if(event.type==='SESSION_END'){if(!emergencyLatched){await runtime.stopSession();await broadcast.command('stopPreview')}continue}
    }
    if(this.cancelRequested&&!emergencyLatched){await runtime.stopSession();await broadcast.command('stopPreview')}
    report.durationMs=scenario.durationMs;const average=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:0;const p95=(xs:number[])=>{const sorted=[...xs].sort((a,b)=>a-b);return sorted.length?sorted[Math.min(sorted.length-1,Math.ceil(sorted.length*.95)-1)]!:0};const ttsLatencies=ttsRecords.map(x=>x.generationTimeMs);const totalResponseLatency=latencies.reduce((sum,n)=>sum+n,0)+hostLatencies.reduce((sum,n)=>sum+n,0)+ttsLatencies.reduce((sum,n)=>sum+n,0);report.latency={averageMs:average(latencies),p95Ms:p95(latencies),hostAverageMs:average(hostLatencies),hostP95Ms:p95(hostLatencies),ttsGenerationAverageMs:average(ttsLatencies),responseAverageMs:report.llmCalls?totalResponseLatency/report.llmCalls:average(latencies)};report.finalState=emergencyLatched?'EMERGENCY_STOPPED':runtime.snapshot().state;report.toolExecutions=0;
    invariant('simulated-audience-remains-marked',report.simulation==='SIMULATION'&&report.audienceSource==='simulator','Synthetic audience lost its simulation marker');invariant('no-tiktok-live-claim',report.tiktokState==='NOT_CONFIGURED'||report.tiktokState==='NOT_AVAILABLE','Simulation claimed a TikTok LIVE connection');invariant('llm-cannot-execute-tools',report.toolExecutions===0&&report.decisions.every(x=>!x.toolAllowed),'A rehearsal decision authorized a tool');invariant('rejected-output-never-reaches-tts',report.outputJudge.filter(x=>x.status!=='PASS').every(x=>!x.speechReachedTts),'Rejected output reached simulated TTS');invariant('no-stale-runtime-queue',emergencyLatched?runtime.snapshot().queueDepth===0:report.finalState==='STOPPED'||report.finalState==='RUNNING','Final runtime queue/state is inconsistent');
    invariant('INVARIANT_001_PRODUCT_ENGINE_AUTHORITY',report.productValidation.filter(x=>x.verified).every(x=>x.productId!==null&&catalog.get(x.productId)!==null),'A verified product fact did not originate from Product Engine');
    invariant('INVARIANT_002_LLM_CANNOT_OVERRIDE_PRODUCT',report.outputJudge.filter(x=>x.status!=='PASS').every(x=>!x.speechReachedTts),'A rejected model claim overrode Product Engine');
    invariant('INVARIANT_003_LLM_CANNOT_EXECUTE_TOOLS',report.toolExecutions===0&&report.decisions.every(x=>!x.toolAllowed),'Model routing authorized a tool execution');
    invariant('INVARIANT_004_REJECTED_OUTPUT_BLOCKED',report.outputJudge.filter(x=>x.status!=='PASS').every(x=>!x.speechReachedTts),'Rejected output reached TTS');
    invariant('INVARIANT_005_EMERGENCY_PRIORITY',report.emergencies.every(x=>x.stopped&&x.resetRequired)&&(!emergencyLatched||runtime.snapshot().queueDepth===0),'Emergency Stop did not override autonomous output');
    invariant('INVARIANT_006_HUMAN_TAKEOVER_PRIORITY',report.takeovers.filter(x=>x.action==='TAKEOVER').every(x=>x.state==='HUMAN_TAKEOVER')&&report.decisions.filter(x=>report.observations.find(o=>o.eventId===x.eventId&&o.takeover)).every(x=>x.decision==='QUEUE'),'Human takeover failed to block autonomous decisions');
    invariant('INVARIANT_007_UNKNOWN_STOCK_SAFE',report.productValidation.filter(x=>x.fact==='STOCK_QUESTION'&&!x.verified).every(x=>!/(?:\b\d+\s*(?:unit|pcs|buah)\b)/iu.test(report.responses.find(r=>r.eventId===x.eventId)?.text??'')),'Unknown stock became a numeric claim');
    invariant('INVARIANT_008_UNKNOWN_PRICE_SAFE',report.productValidation.filter(x=>x.fact==='PRICE_QUESTION'&&!x.verified).every(x=>!/(?:Rp\s*\d)/iu.test(report.responses.find(r=>r.eventId===x.eventId)?.text??'')),'Unknown price became a numeric claim');
    invariant('INVARIANT_009_SIMULATED_AUDIENCE_ISOLATED',report.audienceSource==='simulator'&&report.events.every(x=>x.type==='COMMENT'||x.type==='VIEWER_JOIN'||x.type==='FOLLOW'||x.type==='LIKE'||x.type==='GIFT'||x.type==='SYSTEM'||x.type==='LIVE_START'||x.type==='SESSION_END'||x.type==='DEAD_AIR'||x.type==='MUSIC_START'||x.type==='MUSIC_PAUSE'||x.type==='MUSIC_STOP'||x.type==='PRODUCT_CHANGE'||x.type==='HUMAN_TAKEOVER'||x.type==='AI_RESUME'||x.type==='FAILURE'||x.type==='PRODUCT_DATA_UNAVAILABLE'||x.type==='EMERGENCY_STOP'),'Synthetic event escaped simulation labeling');
    invariant('INVARIANT_010_TIKTOK_NOT_CLAIMED_LIVE',report.tiktokState==='NOT_CONFIGURED'||report.tiktokState==='NOT_AVAILABLE','Rehearsal must not claim a TikTok LIVE connection');
    invariant('INVARIANT_011_JEV_CANNOT_OVERRIDE_SAFETY',report.decisions.every(x=>x.toolAllowed===false),'Decision provider bypassed safety routing');
    invariant('INVARIANT_012_SHOW_DIRECTOR_OWNS_SCHEDULING',report.showActions.every(x=>Boolean(x.action)&&Boolean(x.reason)),'Show Director returned an incomplete scheduling action');
    invariant('INVARIANT_013_SAFETY_RULES_PRECEDE_LLM',report.outputJudge.filter(x=>x.status!=='PASS').every(x=>!x.speechReachedTts),'Generated output bypassed deterministic safety');
    invariant('INVARIANT_014_EMERGENCY_RESET_REQUIRED',!emergencyLatched||report.finalState==='EMERGENCY_STOPPED','Latched emergency state was cleared without reset');
    this.lastReport=report;this.publish({...this.current,running:false,scenarioId:scenario.id,scenarioName:scenario.name,simulatedTimeMs:scenario.durationMs,currentState:report.finalState,pipipState:mode==='MOCK_LLM'||mode==='MOCK'?'MOCK_READY':this.current.pipipState,currentDecision:report.decisions.at(-1)?.decision??'—',currentProduct:currentProductId?catalog.get(currentProductId)?.name??null:null,musicState:music.getState()?.playbackState??'STOPPED',ttsState:voice.getStatus().state,errors:report.errors.length,invariantFailures:report.invariants.filter(x=>!x.passed).length,report});return structuredClone(report);
  }
  private publish(snapshot:RehearsalSnapshot){this.current=structuredClone(snapshot);this.options.onUpdate?.(this.snapshot())}
}
