import type {RehearsalEvent,RehearsalScenario} from './types.js';
const e=(atMs:number,type:RehearsalEvent['type'],extra:Partial<RehearsalEvent>={}):RehearsalEvent=>({atMs,type,...extra});
const comment=(atMs:number,text:string,productId='fixture-mug'):RehearsalEvent=>e(atMs,'COMMENT',{text,productId});
const basic:RehearsalScenario={id:'basic-sales-session',name:'Basic Sales Session',durationMs:180_000,events:[e(0,'LIVE_START'),e(5_000,'VIEWER_JOIN'),comment(10_000,'Hai Pipip, salam kenal.'),comment(25_000,'Apa manfaat Produk Mug?'),comment(40_000,'Kak, harga Produk Mug berapa?'),comment(55_000,'Stok Produk Mug ada berapa?'),comment(70_000,'Produk Mug cocok untuk siapa?'),comment(85_000,'Bandingkan Produk Mug dan Botol.'),comment(100_000,'Wah keren, terima kasih.'),e(180_000,'SESSION_END')]};
const longEvents:RehearsalEvent[]=[e(0,'LIVE_START')];for(let i=0;i<1000;i++){if(i===200)longEvents.push(e(360_000,'MUSIC_START'));if(i===240)longEvents.push(e(432_000,'MUSIC_PAUSE'));if(i===260)longEvents.push(e(468_000,'MUSIC_START'));if(i===500)longEvents.push(e(900_000,'HUMAN_TAKEOVER'));if(i===510)longEvents.push(e(918_000,'AI_RESUME'));longEvents.push(comment(1_000+i*1_800,i%23===0?'https://spam.invalid click promo':`Kak, apa manfaat Produk ${i%2?'Mug':'Botol'}? sesi ${i}`,'fixture-mug'));}longEvents.push(e(1_860_000,'SESSION_END'));
export const REHEARSAL_SCENARIOS:readonly RehearsalScenario[]=[basic,
 {id:'product-question-session',name:'Product Question Session',durationMs:90_000,events:[e(0,'LIVE_START'),comment(2_000,'Bahannya apa?','fixture-mug'),comment(10_000,'Ada varian warna?','fixture-mug'),comment(18_000,'Apa manfaatnya?','fixture-bottle'),comment(26_000,'Bisa bandingkan dua produk?','fixture-mug'),comment(34_000,'Berapa harga barang misterius?','missing-product'),comment(42_000,'Stoknya berapa?','unknown-stock'),e(90_000,'SESSION_END')]},
 {id:'high-comment-activity',name:'High Comment Activity',durationMs:30_000,events:[e(0,'LIVE_START'),...Array.from({length:60},(_,i)=>comment(500+i*400,`Hai, komentar simulasi nomor ${i}`)),e(30_000,'SESSION_END')]},
 {id:'spam-heavy-session',name:'Spam Heavy Session',durationMs:20_000,events:[e(0,'LIVE_START'),...Array.from({length:20},(_,i)=>comment(500+i*700,`https://spam${i}.invalid klik promo`)),comment(15_000,'promo klik tautan'),e(20_000,'SESSION_END')]},
 {id:'dead-air-session',name:'Dead Air Session',durationMs:150_000,events:[e(0,'LIVE_START'),e(60_000,'DEAD_AIR'),e(120_000,'DEAD_AIR'),e(150_000,'SESSION_END')]},
 {id:'music-session',name:'Music Session',durationMs:45_000,events:[e(0,'LIVE_START'),e(2_000,'MUSIC_START'),comment(8_000,'Halo, apa manfaat produk ini?'),e(10_000,'MUSIC_PAUSE'),e(18_000,'MUSIC_START'),comment(20_000,'Kak harganya berapa?'),e(25_000,'MUSIC_STOP'),e(45_000,'SESSION_END')]},
 {id:'human-takeover-session',name:'Human Takeover Session',durationMs:40_000,events:[e(0,'LIVE_START'),comment(3_000,'Apa manfaat Produk Mug?'),e(10_000,'HUMAN_TAKEOVER'),comment(12_000,'Kak, berapa harganya?'),e(25_000,'AI_RESUME'),comment(28_000,'Hai sesudah host kembali.'),comment(30_000,'Stoknya berapa?'),e(40_000,'SESSION_END')]},
 {id:'emergency-stop-session',name:'Emergency Stop Session',durationMs:30_000,events:[e(0,'LIVE_START'),e(5_000,'MUSIC_START'),e(10_000,'EMERGENCY_STOP',{fromState:'MUSIC'}),comment(15_000,'Hai setelah emergency'),e(30_000,'SESSION_END')]},
 {id:'ollama-failure-session',name:'Ollama Failure Session',durationMs:30_000,events:[e(0,'LIVE_START'),e(2_000,'FAILURE',{failure:'OLLAMA_TIMEOUT'}),comment(4_000,'Apa manfaat Produk Mug?'),e(8_000,'FAILURE',{failure:'OLLAMA_UNAVAILABLE'}),comment(10_000,'Apa manfaat produk?'),e(30_000,'SESSION_END')]},
 {id:'tts-failure-session',name:'TTS Failure Session',durationMs:25_000,events:[e(0,'LIVE_START'),e(2_000,'FAILURE',{failure:'TTS_FAILURE'}),comment(4_000,'Hai Pipip.'),comment(10_000,'Apa manfaat Produk Mug?'),e(25_000,'SESSION_END')]},
 {id:'product-data-failure-session',name:'Product Data Failure Session',durationMs:25_000,events:[e(0,'LIVE_START'),e(2_000,'PRODUCT_DATA_UNAVAILABLE'),comment(4_000,'Kak, harganya berapa?','fixture-mug'),comment(10_000,'Stoknya berapa?','fixture-mug'),e(25_000,'SESSION_END')]},
 {id:'price-and-stock-session',name:'PRICE_AND_STOCK_SESSION',durationMs:45_000,events:[e(0,'LIVE_START'),comment(2_000,'Kak, harga Produk Mug berapa?','fixture-mug'),comment(8_000,'Stok Produk Mug berapa?','fixture-mug'),comment(14_000,'Harga produk misterius berapa?','missing-product'),comment(20_000,'Stok barang misterius berapa?','missing-product'),e(45_000,'SESSION_END')]},
 {id:'product-recommendation-session',name:'PRODUCT_RECOMMENDATION_SESSION',durationMs:45_000,events:[e(0,'LIVE_START'),comment(3_000,'Rekomendasi produk yang mudah dibersihkan?','fixture-bottle'),comment(12_000,'Produk Mug cocok untuk siapa?','fixture-mug'),comment(22_000,'Bandingkan Produk Mug dan Produk Botol.','fixture-mug'),e(45_000,'SESSION_END')]},
 {id:'off-topic-session',name:'OFF_TOPIC_SESSION',durationMs:30_000,events:[e(0,'LIVE_START'),comment(2_000,'Bagaimana skor sepak bola tadi malam?'),comment(8_000,'Cuaca besok cerah?'),comment(14_000,'Kak, apa manfaat Produk Mug?'),e(30_000,'SESSION_END')]},
 {id:'product-rotation-session',name:'PRODUCT_ROTATION_SESSION',durationMs:60_000,events:[e(0,'LIVE_START'),comment(3_000,'Apa manfaat Produk Mug?','fixture-mug'),e(15_000,'PRODUCT_CHANGE',{productId:'fixture-bottle'}),comment(20_000,'Apa manfaat Produk Botol?','fixture-bottle'),e(30_000,'DEAD_AIR'),e(40_000,'PRODUCT_CHANGE',{productId:'fixture-mug'}),comment(45_000,'Ada varian Produk Mug?','fixture-mug'),e(60_000,'SESSION_END')]},
 {id:'jev-failure-session',name:'JEV_FAILURE_SESSION',durationMs:30_000,events:[e(0,'LIVE_START'),e(2_000,'FAILURE',{failure:'JEV_FAILURE'}),comment(4_000,'Apa manfaat Produk Mug?','fixture-mug'),comment(12_000,'Stok Produk Mug berapa?','fixture-mug'),e(30_000,'SESSION_END')]},
 {id:'mixed-live-session',name:'MIXED_LIVE_SESSION',durationMs:120_000,events:[e(0,'LIVE_START'),e(3_000,'VIEWER_JOIN'),e(4_000,'FOLLOW'),e(5_000,'LIKE'),e(6_000,'GIFT'),e(7_000,'SYSTEM',{text:'synthetic test notification'}),comment(10_000,'Hai Pipip, apa manfaat Produk Mug?'),e(20_000,'MUSIC_START'),comment(25_000,'Kak harga Produk Mug berapa?'),e(35_000,'MUSIC_PAUSE'),e(45_000,'MUSIC_START'),e(50_000,'PRODUCT_CHANGE',{productId:'fixture-bottle'}),comment(55_000,'Rekomendasi Produk Botol?','fixture-bottle'),e(70_000,'HUMAN_TAKEOVER'),comment(75_000,'Host manusia lanjut ya.'),e(90_000,'AI_RESUME'),comment(100_000,'Stok Produk Botol berapa?','fixture-bottle'),e(120_000,'SESSION_END')]},
 {id:'long-mixed-session',name:'LONG_RUNNING_SESSION · 31 Virtual Minutes',durationMs:1_860_000,events:longEvents}];
export function getRehearsalScenario(id:string){return REHEARSAL_SCENARIOS.find(x=>x.id===id)??null}
