export type RehearsalMode='MOCK'|'MOCK_LLM'|'REAL_OLLAMA';
export type RehearsalFailure='OLLAMA_TIMEOUT'|'OLLAMA_UNAVAILABLE'|'MALFORMED_LLM_OUTPUT'|'OLLAMA_MALFORMED_RESPONSE'|'PRODUCT_ENGINE_FAILURE'|'TTS_FAILURE'|'MUSIC_FAILURE'|'AVATAR_FAILURE'|'AVATAR_RUNTIME_FAILURE'|'JEV_FAILURE'|'OUTPUT_JUDGE_FAILURE'|'RUNTIME_FAILURE'|'LIVE_RUNTIME_FAILURE';
export type RehearsalEventType='LIVE_START'|'VIEWER_JOIN'|'FOLLOW'|'LIKE'|'GIFT'|'SYSTEM'|'COMMENT'|'DEAD_AIR'|'MUSIC_START'|'MUSIC_PAUSE'|'MUSIC_STOP'|'PRODUCT_CHANGE'|'HUMAN_TAKEOVER'|'AI_RESUME'|'FAILURE'|'PRODUCT_DATA_UNAVAILABLE'|'EMERGENCY_STOP'|'SESSION_END';
export type EmergencyOrigin='IDLE'|'PREPARING'|'SPEAKING'|'MUSIC'|'QUEUE'|'PRODUCT_RESPONSE'|'AVATAR_COMMAND'|'HUMAN_TAKEOVER';
export interface RehearsalEvent {atMs:number;type:RehearsalEventType;text?:string;productId?:string;failure?:RehearsalFailure;fromState?:EmergencyOrigin}
export interface RehearsalScenario {id:string;name:string;durationMs:number;events:RehearsalEvent[]}
export interface RehearsalDecisionRecord {atMs:number;eventId:string;intent:string;decision:string;route:string;provider:string;confidence:number;requiresLlm:boolean;requiresHuman:boolean;toolAllowed:boolean;fallback:boolean;latencyMs:number;reasonCode:string}
export interface RehearsalOutputRecord {eventId:string;status:'PASS'|'REJECT'|'FAIL_CLOSED';reasonCode:string;speechReachedTts:boolean}
export interface RehearsalTtsRecord {eventId:string;language:'id-ID';status:'READY'|'FAILED'|'CANCELLED'|'REJECTED';queueTimeMs:number;generationTimeMs:number;speechDurationMs:number|null;provider:string}
export interface RehearsalInvariant {id:string;passed:boolean;detail:string}
export interface RehearsalObservation {timestamp:number;eventId:string;event:string;state:string;decision:string|null;provider:string|null;product:string|null;responseMode:string|null;confidence:number|null;latencyMs:number|null;ttsState:string;musicState:string;takeover:boolean;emergency:boolean;error:string|null;fallback:boolean}
export interface RehearsalReport {simulation:'SIMULATION';scenarioId:string;scenarioName:string;mode:RehearsalMode;durationMs:number;eventCount:number;events:RehearsalEvent[];responses:Array<{eventId:string;text:string}>;ignoredEvents:number;queuedEvents:number;llmCalls:number;llmResponses:number;model:string|null;deterministicDecisions:number;fallbacks:number;decisions:RehearsalDecisionRecord[];knowledge:Array<{eventId:string;topic:string;status:string}>;observations:RehearsalObservation[];outputJudge:RehearsalOutputRecord[];productValidation:Array<{eventId:string;productId:string|null;verified:boolean;fact:string}>;tts:RehearsalTtsRecord[];music:Array<{atMs:number;action:string;state:string;musicLevel:number;ducked:boolean}>;takeovers:Array<{atMs:number;action:string;state:string}>;emergencies:Array<{atMs:number;fromState:string;stopped:boolean;resetRequired:boolean}>;showActions:Array<{atMs:number;action:string;reason:string}>;errors:Array<{atMs:number;code:RehearsalFailure|string;subsystem:string}>;invariants:RehearsalInvariant[];latency:{averageMs:number;p95Ms:number;hostAverageMs:number;hostP95Ms:number;ttsGenerationAverageMs:number;responseAverageMs:number};finalState:string;audienceSource:'simulator';tiktokState:'NOT_CONFIGURED'|'NOT_AVAILABLE';toolExecutions:0}
export interface RehearsalSnapshot {simulation:'SIMULATION';running:boolean;scenarioId:string|null;scenarioName:string|null;simulatedTimeMs:number;currentState:string;currentEvent:string|null;pipipState:string;currentDecision:string;currentProduct:string|null;musicState:string;ttsState:string;errors:number;invariantFailures:number;report:RehearsalReport|null}
