import type { RuntimeSnapshot } from '../../live-runtime/src/index.js';
import type { Product } from '../../product-engine/src/index.js';
import { OverlayQueue } from './overlay-queue.js';
import { SceneManager } from './scene-manager.js';
import { renderProduct } from './product-overlay.js';
import type { BroadcastCommand, BroadcastDiagnostics, BroadcastHealth, BroadcastOptions, BroadcastOverlay, BroadcastRenderState, BroadcastStatus, BroadcastStatusSnapshot, HostVisualState, MusicVisualState, ProductSource } from './types.js';
import type { BroadcastOutputAdapter } from './types.js';
import { BroadcastWatchdog } from './broadcast-watchdog.js';
const transitions:Record<BroadcastStatus,BroadcastStatus[]>={IDLE:['PREPARING','STOPPED'],PREPARING:['LIVE','STOPPED','ERROR','EMERGENCY_STOPPED'],LIVE:['PAUSED','HUMAN_TAKEOVER','STOPPING','ERROR','EMERGENCY_STOPPED'],PAUSED:['LIVE','HUMAN_TAKEOVER','STOPPING','ERROR','EMERGENCY_STOPPED'],HUMAN_TAKEOVER:['LIVE','PAUSED','STOPPING','ERROR','EMERGENCY_STOPPED'],EMERGENCY_STOPPED:['STOPPED'],STOPPING:['STOPPED','ERROR','EMERGENCY_STOPPED'],STOPPED:['PREPARING','IDLE'],ERROR:['PREPARING','STOPPED','EMERGENCY_STOPPED']};
const diag=():BroadcastDiagnostics=>({sceneChanges:0,overlaysCreated:0,overlaysDismissed:0,productRenders:0,ctaRenders:0,musicRenders:0,hostRenders:0,renderFailures:0,outputConnectionFailures:0,emergencyStops:0});
export class BroadcastEngine {
 private status:BroadcastStatus='IDLE';private readonly now:()=>number;private readonly scenes:SceneManager;private readonly queue:OverlayQueue;private readonly watchdog=new BroadcastWatchdog(2);private readonly overlays:BroadcastOverlay[]=[];private readonly maxOverlays:number;private readonly ttl:number;private renderCount=0;private lastRenderAt:number|null=null;private runtime:RuntimeSnapshot|null=null;private product:Product|null=null;private host:{state:HostVisualState;detail:string|null}={state:'IDLE',detail:null};private music:{state:MusicVisualState;title:string|null;artist:string|null;progressMs:number|null;durationMs:number|null;volume:number|null;ducked:boolean|null}={state:'UNKNOWN',title:null,artist:null,progressMs:null,durationMs:null,volume:null,ducked:null};private activity:string|null=null;private audience={available:false,event:null as string|null};private avatar={state:null as string|null,emotion:null as string|null,expression:null as string|null,gesture:null as string|null};private diag=diag();private emergency=false;private takeover=false;private failures=0;private resumeAfterEmergency=false;
 constructor(private readonly output:BroadcastOutputAdapter,private readonly productSource:ProductSource,options:BroadcastOptions={}){this.now=options.now??Date.now;this.scenes=new SceneManager(this.now);this.queue=new OverlayQueue(this.now,options.maxQueue??32);this.maxOverlays=options.maxOverlays??24;this.ttl=options.defaultOverlayTtlMs??30_000}
 getState(){return this.status}
 async command(command:BroadcastCommand){switch(command){case'startPreview':if(this.status==='LIVE')return this.snapshot();if(!this.move('PREPARING'))return this.snapshot();try{await this.output.connect();this.move('LIVE');await this.refresh();}catch{this.failures++;this.diag.outputConnectionFailures++;this.move('ERROR')}break;case'stopPreview':if(['STOPPED','IDLE'].includes(this.status))return this.snapshot();if(this.status==='EMERGENCY_STOPPED'){this.move('STOPPED');break}this.move('STOPPING');await this.output.clear();await this.output.disconnect();this.move('STOPPED');break;case'refresh':await this.refresh();break;case'clearOverlays':this.diag.overlaysDismissed+=this.overlays.length+this.queue.clear();this.overlays.splice(0);await this.refresh();break;case'testProduct':if(!this.runtime?.activeProductId)return this.snapshot();await this.observeProduct(this.runtime.activeProductId);break;case'testCTA':this.enqueue({type:'CTA',priority:40,data:{text:'LIHAT PRODUK'},source:'operator',dismissible:true});await this.refresh();break;case'testMusic':if(this.music.state!=='UNKNOWN'){this.setScene('MUSIC');this.diag.musicRenders++;await this.refresh()}break;case'testHost':if(this.runtime){this.host={state:this.runtime.health.voice==='playing'?'SPEAKING':this.runtime.state==='RUNNING'?'WAITING':this.runtime.state==='HUMAN_TAKEOVER'?'HUMAN_TAKEOVER':this.runtime.state==='ERROR'?'ERROR':'IDLE',detail:this.runtime.activeActivity};this.diag.hostRenders++;await this.refresh()}break;case'testHumanTakeover':this.takeover=true;this.setStatus('HUMAN_TAKEOVER');this.setScene('HUMAN_TAKEOVER');this.enqueue({type:'SYSTEM',priority:90,data:{text:'Mode manusia aktif'},source:'runtime',dismissible:false});await this.refresh();break;case'testEmergency':await this.emergencyStop();break;case'reset':if(this.emergency){this.emergency=false;this.takeover=false;this.diag.overlaysDismissed+=this.overlays.length;this.overlays.splice(0);this.restoreScene();await this.restorePreviewAfterEmergency()}break;}return this.snapshot()}
 async observeRuntime(snapshot:RuntimeSnapshot){this.runtime=structuredClone(snapshot);const wasEmergency=this.emergency;const wasTakeover=this.takeover;this.takeover=snapshot.humanTakeover;this.emergency=snapshot.emergencyStopped;if(this.emergency){this.resumeAfterEmergency=this.resumeAfterEmergency||['LIVE','PAUSED','HUMAN_TAKEOVER'].includes(this.status);this.status='EMERGENCY_STOPPED';this.setScene('EMERGENCY');this.diag.overlaysDismissed+=this.overlays.length+this.queue.clear();this.overlays.splice(0);if(!wasEmergency){try{await this.output.emergencyStop()}catch{this.diag.outputConnectionFailures++}}}else if(wasEmergency){this.status='STOPPED';this.restoreScene();await this.output.clear();await this.restorePreviewAfterEmergency()}else if(this.takeover){this.status='HUMAN_TAKEOVER';this.setScene('HUMAN_TAKEOVER')}else if(snapshot.state==='PAUSED'){if(['LIVE','PAUSED','HUMAN_TAKEOVER'].includes(this.status))this.status='PAUSED';this.setScene('WAITING')}else if(snapshot.state==='RUNNING'&&['PAUSED','HUMAN_TAKEOVER'].includes(this.status)){this.status='LIVE';if(wasTakeover)this.restoreScene();else this.setScene('DEFAULT')}else if(snapshot.state==='ERROR'&&this.status==='LIVE'){this.status='ERROR';this.setScene('ERROR')}const activityMap:Record<string,string>={GREETING:'Host menyapa',PRODUCT_INTRO:'Produk dipilih',PRODUCT_EDUCATION:'Produk dibahas',MUSIC_INTRO:'Musik diputar',MUSIC_SEGMENT:'Musik diputar',WAIT:'Menunggu respons',AUDIENCE_INTERACTION:'Interaksi audiens tersedia',CTA:'Ajakan lihat produk ditampilkan'};const activity=snapshot.activeActivity?activityMap[snapshot.activeActivity]:undefined;if(activity&&activity!==this.activity){this.activity=activity;if(!this.emergency&&!this.takeover)this.enqueue({type:'ACTIVITY',priority:10,data:{text:activity},source:'live-runtime',dismissible:true})}if(snapshot.health.audience==='ready')this.audience.available=true;else if(snapshot.health.audience==='unknown')this.audience={available:false,event:null};return this.refresh()}
 observeProduct(id:string|null){const previousId=this.product?.id??null;this.product=id?this.productSource(id):null;if(this.product&&this.product.id!==previousId){this.setScene('PRODUCT');this.diag.productRenders++;this.enqueue({type:'PRODUCT',priority:50,data:{productId:this.product.id,name:this.product.name},source:'product-engine',dismissible:true});}return this.refresh()}
 observeHost(state:HostVisualState,detail:string|null=null){if(this.emergency||this.takeover&&state!=='HUMAN_TAKEOVER')return Promise.resolve(this.snapshot());this.host={state,detail};if(state==='SPEAKING')this.setScene('HOST_SPEAKING');this.diag.hostRenders++;return this.refresh()}
 observeMusic(music:Partial<BroadcastRenderState['music']>){if(this.emergency)return Promise.resolve(this.snapshot());this.music={...this.music,...music};if(music.state&&music.state!=='UNKNOWN'){this.setScene(music.state==='PLAYING'||music.state==='BACKGROUND'?'MUSIC':'DEFAULT');this.diag.musicRenders++}return this.refresh()}
 observeAvatar(avatar:Partial<BroadcastRenderState['avatar']>){this.avatar={...this.avatar,...avatar};return this.refresh()}
 observeAudience(available:boolean,event:string|null){this.audience={available,event:available?event:null};if(available&&event&&!this.emergency&&!this.takeover)this.enqueue({type:'AUDIENCE_EVENT',priority:30,data:{text:event},source:'audience-engine',dismissible:true});return this.refresh()}
 observeActivity(event:string){this.activity=event;if(!this.emergency&&!this.takeover)this.enqueue({type:'ACTIVITY',priority:10,data:{text:event},source:'live-runtime',dismissible:true});return this.refresh()}
 enqueue(input:{type:BroadcastOverlay['type'];priority:number;data:BroadcastOverlay['data'];source:string;dismissible:boolean;ttlMs?:number}){if(this.emergency||this.takeover&&input.source!=='operator')return false;const overlay:BroadcastOverlay={id:`overlay-${this.now()}-${this.diag.overlaysCreated}`,type:input.type,priority:input.priority,visible:true,createdAt:this.now(),expiresAt:this.now()+(input.ttlMs??this.ttl),data:{...input.data},source:input.source,dismissible:input.dismissible};if(this.queue.depth>=32||this.overlays.length>=this.maxOverlays){this.queue.take()}if(!this.queue.enqueue(overlay))return false;this.diag.overlaysCreated++;if(input.type==='CTA')this.diag.ctaRenders++;return true}
 async refresh(){if(this.emergency){this.diag.overlaysDismissed+=this.overlays.length+this.queue.clear();this.overlays.splice(0)}else{while(this.queue.depth){const next=this.queue.take();if(next){this.overlays.push(next);if(this.overlays.length>this.maxOverlays){this.overlays.shift();this.diag.overlaysDismissed++}}}}const render=this.renderState();if(this.status==='LIVE'||this.status==='PAUSED'||this.status==='HUMAN_TAKEOVER'){try{await this.output.render(render);this.renderCount++;this.lastRenderAt=this.now();this.failures=0;this.watchdog.reset()}catch{this.failures++;this.diag.renderFailures++;if(!this.emergency&&this.watchdog.canRecover()){try{if(await this.output.isAvailable())await this.output.connect()}catch{this.diag.outputConnectionFailures++}}if(this.failures>=3)this.status='ERROR'}}return this.snapshot()}
 async emergencyStop(){if(this.emergency)return this.snapshot();this.resumeAfterEmergency=this.resumeAfterEmergency||['LIVE','PAUSED','HUMAN_TAKEOVER'].includes(this.status);this.emergency=true;this.takeover=false;this.status='EMERGENCY_STOPPED';this.setScene('EMERGENCY');this.diag.overlaysDismissed+=this.overlays.length+this.queue.clear();this.overlays.splice(0);this.diag.emergencyStops++;try{await this.output.emergencyStop()}catch{this.diag.outputConnectionFailures++}return this.snapshot()}
 snapshot():BroadcastStatusSnapshot {const render=this.renderState();const health:BroadcastHealth={status:this.status==='ERROR'||this.failures>=3?'error':this.status==='EMERGENCY_STOPPED'?'degraded':this.status==='LIVE'&&this.lastRenderAt!==null?'healthy':this.status==='IDLE'||this.status==='STOPPED'?'unknown':'degraded',output:this.status==='LIVE'||this.status==='PAUSED'||this.status==='HUMAN_TAKEOVER'?'connected':'disconnected',scene:render.scene.sceneId,overlayCount:render.overlays.length,queueDepth:this.queue.depth,renderCount:this.renderCount,renderFailures:this.diag.renderFailures,lastRenderAt:this.lastRenderAt,timestamp:this.now()};const output={connected:false,available:true,error:null,lastRenderAt:this.lastRenderAt};const findings=this.watchdog.inspect(health,{available:true,emergency:this.emergency,humanTakeover:this.takeover});return{state:this.status,render,health,output,queueDepth:this.queue.depth,diagnostics:{...this.diag},watchdogFindings:findings}}
 async detailedSnapshot(){const s=this.snapshot();const output=await this.output.getState();return{...s,output,watchdogFindings:this.watchdog.inspect(s.health,{available:output.available,emergency:this.emergency,humanTakeover:this.takeover})}}
 private async restorePreviewAfterEmergency(){if(!this.resumeAfterEmergency)return;this.resumeAfterEmergency=false;this.status='PREPARING';try{await this.output.connect();this.status='LIVE';await this.refresh()}catch{this.status='ERROR';this.diag.outputConnectionFailures++}}private restoreScene(){const before=this.scenes.currentScene().sceneId;this.scenes.restore();if(before!==this.scenes.currentScene().sceneId)this.diag.sceneChanges++}
 private renderState():BroadcastRenderState{return{status:this.status,scene:this.scenes.currentScene(),overlays:this.emergency?[]:this.overlays.filter(x=>x.expiresAt===null||x.expiresAt>this.now()).map(x=>structuredClone(x)),product:this.product?renderProduct(this.product):null,host:{...this.host},music:{...this.music},activity:this.activity,audience:{...this.audience},avatar:{...this.avatar},emergency:this.emergency,humanTakeover:this.takeover,timestamp:this.now()}}
 private move(next:BroadcastStatus){if(next===this.status)return true;if(!transitions[this.status].includes(next))return false;this.status=next;return true}private setStatus(next:BroadcastStatus){if(this.status!==next&&this.move(next))return;this.status=next}private setScene(id:import('./types.js').SceneId){const before=this.scenes.currentScene().sceneId;if(this.scenes.activate(id)&&before!==id)this.diag.sceneChanges++}private clearScene(){const before=this.scenes.currentScene().sceneId;this.scenes.clear();if(before!=='DEFAULT')this.diag.sceneChanges++}
}
