export type AudienceSource='simulator'|'local_rehearsal'|'tiktok'|'youtube'|'website'|'unknown';
export type AudienceEventType='COMMENT'|'NEW_VIEWER'|'FOLLOW'|'LIKE'|'GIFT'|'SYSTEM'|'UNKNOWN';
export type AudienceIntent='PRODUCT_QUESTION'|'PRICE_QUESTION'|'STOCK_QUESTION'|'VARIANT_QUESTION'|'PRODUCT_RECOMMENDATION'|'COMPARISON'|'PURCHASE_INTENT'|'JOKE'|'GENERAL_QUESTION'|'GREETING'|'REACTION'|'REQUEST_DEMO'|'COMPLAINT'|'OFF_TOPIC'|'SPAM'|'ABUSE'|'UNKNOWN';
export type ResponseMode='IGNORE'|'VISUAL_REACTION'|'SHORT_RESPONSE'|'FULL_RESPONSE'|'QUEUE';
export interface RawAudienceEvent {source?:unknown;type?:unknown;text?:unknown;timestamp?:unknown;eventId?:unknown;userId?:unknown;displayName?:unknown;priority?:unknown}
export interface AudienceEvent {source:AudienceSource;type:AudienceEventType;text:string;timestamp:number;eventId?:string}
export interface AudienceTask {event:AudienceEvent;intent:AudienceIntent;mode:ResponseMode;priority:number;enqueuedAt:number}
export interface AudienceDecision {accepted:boolean;intent:AudienceIntent;mode:ResponseMode;priority:number;reason:'accepted'|'empty'|'unsupported_event'|'duplicate'|'spam'|'abuse'|'stale'|'queue_full'|'ignored';task?:AudienceTask}
const sources:AudienceSource[]=['simulator','local_rehearsal','tiktok','youtube','website','unknown'];const types:AudienceEventType[]=['COMMENT','NEW_VIEWER','FOLLOW','LIKE','GIFT','SYSTEM','UNKNOWN'];
const normalize=(s:string)=>s.normalize('NFKC').toLocaleLowerCase('id-ID').replace(/[^\p{L}\p{N}\s]/gu,' ').replace(/\s+/g,' ').trim();
export function normalizeAudienceEvent(raw:RawAudienceEvent,now=Date.now()):AudienceEvent {const text=typeof raw.text==='string'?raw.text.normalize('NFKC').trim().slice(0,500):'';const time=typeof raw.timestamp==='number'?raw.timestamp:typeof raw.timestamp==='string'?Date.parse(raw.timestamp):now;return{source:sources.includes(raw.source as AudienceSource)?raw.source as AudienceSource:'unknown',type:types.includes(raw.type as AudienceEventType)?raw.type as AudienceEventType:'UNKNOWN',text,timestamp:Number.isFinite(time)?time:now,...(typeof raw.eventId==='string'?{eventId:raw.eventId.slice(0,100)}:{})}}
export function classifyAudienceIntent(text:string):AudienceIntent {const s=normalize(text);if(!s)return'UNKNOWN';if(/\b(bodoh|anjing|bangsat|babi|tolol|idiot|fuck|kontol|memek)\b/.test(s))return'ABUSE';if(/https?:\/\/|www\.|bit\.ly|wa\.me/i.test(text)||/(promo.*klik|follow.*akun)/.test(s))return'SPAM';if(/\b(politik|pemilu|bitcoin|crypto|cuaca|sepak bola|football|skor bola)\b/.test(s))return'OFF_TOPIC';if(/\b(stok|tersedia|ready|habis|available)\b/.test(s))return'STOCK_QUESTION';if(/\b(harga|price|diskon|promo|potongan)\b/.test(s))return'PRICE_QUESTION';if(/\b(bandingkan|perbandingan|beda|perbedaan|compare|versus|vs)\b/.test(s))return'COMPARISON';if(/\b(rekomendasi|rekomendasikan|cocok|saran|recommended)\b/.test(s))return'PRODUCT_RECOMMENDATION';if(/\b(kecewa|komplain|rusak|buruk|lambat|refund)\b/.test(s))return'COMPLAINT';if(/\b(beli|checkout|pesan|order)\b/.test(s))return'PURCHASE_INTENT';if(/\b(varian|warna|ukuran|size|model)\b/.test(s))return'VARIANT_QUESTION';if(/\b(cara pakai|demo|demokan|tunjuk|lihatkan)\b/.test(s))return'REQUEST_DEMO';if(/\b(halo|hai|hello|assalamualaikum|pagi|siang|malam)\b/.test(s))return'GREETING';if(/\b(joke|bercanda|lelucon)\b/.test(s))return'JOKE';if(/\b(bagus|keren|mantap|love|wkwk|haha|lucu)\b/.test(s))return'REACTION';if(/\b(produk|barang|bahan|fungsi|manfaat|garansi|berat|ukuran|bisa|apakah|apa|bagaimana|gimana|kenapa|why|what|how)\b/.test(s))return'PRODUCT_QUESTION';if(s.length<3)return'UNKNOWN';if(/^(?:wkwk){2,}w?k?$/.test(s))return'JOKE';return'GENERAL_QUESTION'}
export function selectResponseMode(intent:AudienceIntent):ResponseMode {if(intent==='ABUSE'||intent==='SPAM'||intent==='OFF_TOPIC')return'IGNORE';if(intent==='REACTION')return'VISUAL_REACTION';if(intent==='COMPLAINT'||intent==='PRODUCT_QUESTION'||intent==='PRICE_QUESTION'||intent==='STOCK_QUESTION'||intent==='VARIANT_QUESTION'||intent==='PRODUCT_RECOMMENDATION'||intent==='COMPARISON'||intent==='PURCHASE_INTENT'||intent==='REQUEST_DEMO')return'FULL_RESPONSE';if(intent==='JOKE'||intent==='UNKNOWN')return'SHORT_RESPONSE';return'SHORT_RESPONSE'}
export class AudienceQueue {private items:AudienceTask[]=[];private seen=new Map<string,number>();constructor(private readonly maxSize=100,private readonly ttlMs=120_000,private readonly now=()=>Date.now()){} enqueue(task:AudienceTask):boolean{this.expire();const key=normalize(task.event.text);if(!key||this.seen.has(key)||this.items.length>=this.maxSize)return false;this.seen.set(key,this.now());this.items.push(task);this.items.sort((a,b)=>b.priority-a.priority||a.enqueuedAt-b.enqueuedAt);return true} requeue(task:AudienceTask):boolean{this.expire();if(this.items.length>=this.maxSize||this.items.some(x=>x===task))return false;this.items.push(task);this.items.sort((a,b)=>b.priority-a.priority||a.enqueuedAt-b.enqueuedAt);return true} pop():AudienceTask|undefined{this.expire();return this.items.shift()} clear(){this.items=[];this.seen.clear()} size(){this.expire();return this.items.length} private expire(){const cutoff=this.now()-this.ttlMs;this.items=this.items.filter(x=>x.enqueuedAt>=cutoff);for(const [key,time] of this.seen)if(time<cutoff)this.seen.delete(key)}}
export class AudienceEngine {readonly queue:AudienceQueue;private memory:string[]=[];private readonly now:()=>number;constructor(options:{maxQueue?:number;ttlMs?:number;now?:()=>number}={}){this.now=options.now??Date.now;this.queue=new AudienceQueue(options.maxQueue,options.ttlMs,this.now)} ingest(raw:RawAudienceEvent,options:{humanOverride?:boolean;paused?:boolean}={}){const event=normalizeAudienceEvent(raw,this.now());const intent=classifyAudienceIntent(event.text);let mode=selectResponseMode(intent);if(options.humanOverride)mode='IGNORE';if(options.paused&&mode!=='IGNORE')mode='QUEUE';let priority=intent==='COMPLAINT'?100:intent==='PRICE_QUESTION'||intent==='STOCK_QUESTION'?80:intent==='COMPARISON'?75:intent==='PRODUCT_QUESTION'||intent==='VARIANT_QUESTION'||intent==='PRODUCT_RECOMMENDATION'||intent==='PURCHASE_INTENT'?70:intent==='REQUEST_DEMO'?60:intent==='GENERAL_QUESTION'?40:intent==='GREETING'?20:10;let reason:AudienceDecision['reason']='accepted';if(!event.text||!normalize(event.text))reason='empty';else if(event.type!=='COMMENT'&&event.type!=='UNKNOWN')reason='unsupported_event';else if(intent==='ABUSE')reason='abuse';else if(mode==='IGNORE')reason='ignored';else if(/(.)\1{7,}/u.test(normalize(event.text))||/(https?:|www\.|bit\.ly)/i.test(event.text))reason='spam';else if(this.memory.includes(normalize(event.text)))reason='duplicate';else if(this.now()-event.timestamp>120_000)reason='stale';const decision:AudienceDecision={accepted:reason==='accepted',intent,mode,priority,reason};if(decision.accepted){const task={event,intent,mode,priority,enqueuedAt:this.now()};if(this.queue.enqueue(task)){decision.task=task;this.memory=[...this.memory,normalize(event.text)].slice(-50)}else{decision.accepted=false;decision.reason='queue_full'}}return decision} next(){return this.queue.pop()} requeue(task:AudienceTask){return this.queue.requeue(task)} clear(){this.queue.clear();this.memory=[]} get size(){return this.queue.size()}}
