import { RuntimeEventBus } from './event-bus.js';
import type { LiveRuntimeContext, LiveRuntimeOptions, LiveRuntimePorts, LiveRuntimeState, RuntimeAction, RuntimeActivity, RuntimeEventMap, RuntimeEventName, RuntimeHealth, RuntimeMetrics, RuntimeSnapshot, SubsystemHealth } from './types.js';
import { RuntimeWatchdog, type WatchdogFinding } from './runtime-watchdog.js';
import { RuntimeErrorRecovery } from './error-recovery.js';

const transitions: Record<LiveRuntimeState, readonly LiveRuntimeState[]> = {
  IDLE: ['STARTING'], STARTING: ['RUNNING', 'ERROR', 'STOPPING'], RUNNING: ['PAUSED', 'HUMAN_TAKEOVER', 'STOPPING', 'ERROR'],
  PAUSED: ['RUNNING', 'HUMAN_TAKEOVER', 'STOPPING', 'ERROR'], HUMAN_TAKEOVER: ['RUNNING', 'PAUSED', 'STOPPING', 'ERROR'],
  STOPPING: ['STOPPED', 'ERROR'], STOPPED: ['STARTING'], ERROR: ['STOPPING', 'STOPPED'],
};
const freshMetrics = (): RuntimeMetrics => ({ sessionDurationMs: 0, speechCount: 0, speechFailures: 0, musicPlays: 0, musicFailures: 0, avatarCommands: 0, avatarFailures: 0, audienceEvents: 0, processedEvents: 0, ignoredEvents: 0, queuedActions: 0, droppedActions: 0, recoveredErrors: 0, humanTakeoverCount: 0, emergencyStopCount: 0 });
const message = (_error: unknown) => 'Subsystem operation failed';
const safeIdentifier=(value:string,max=60)=>/(?:api.?key|access.?token|refresh.?token|password|secret|cookie|credential)/i.test(value)?'redacted':value.replace(/[^A-Za-z0-9_.:-]/g,'').slice(0,max)||'unknown';

export class LiveRuntime {
  readonly events: RuntimeEventBus;
  private state: LiveRuntimeState = 'IDLE'; private sessionId: string | null = null; private startedAt: number | null = null; private endedAt: number | null = null;
  private activeProductId: string | null = null; private activeActivity: string | null = null; private humanTakeover = false; private takeoverReturnState: 'RUNNING'|'PAUSED'|null = null; private emergencyStopped = false;
  private errorCount = 0; private consecutiveFailures = 0; private eventLoopLagMs = 0; private queueDepth = 0; private lastActivityAt: number | null = null; private lastActionAt: number | null = null; private lastSpeechAt: number | null = null; private lastProductActionAt: number | null = null; private activity: RuntimeActivity[] = []; private metrics = freshMetrics(); private operation: Promise<unknown> | null = null; private idSequence = 0; private hostResponsePending = false; private recovering = false; private readonly watchdog = new RuntimeWatchdog();
  private readonly now: () => number; private readonly maxActivity: number;
  constructor(private readonly ports: LiveRuntimePorts = {}, private readonly options: LiveRuntimeOptions = {}) { this.now = options.now ?? (() => Date.now()); this.maxActivity = Math.max(1, options.maxActivity ?? 100); this.events = new RuntimeEventBus(this.now); }
  private transition(next: LiveRuntimeState): void { if (next === this.state) return; if (!transitions[this.state].includes(next)) throw new Error(`Invalid runtime transition ${this.state} -> ${next}`); this.state = next; }
  private record(event: string, detail: string): void { const item = { timestamp: this.now(), event: event.slice(0, 80), detail: detail.slice(0, 240) }; this.activity.push(item); if (this.activity.length > this.maxActivity) this.activity.splice(0, this.activity.length - this.maxActivity); this.lastActivityAt = item.timestamp; this.emit('ACTIVITY', { detail: `${item.event}: ${item.detail}` }); }
  private emit<K extends RuntimeEventName>(type: K, payload: RuntimeEventMap[K]): void { const event = this.events.emit(type, payload) as import('./types.js').RuntimeEvent; try { this.ports.onEvent?.(event); } catch { /* observers cannot break runtime control */ } }
  async startSession(): Promise<RuntimeSnapshot> {
    if (this.emergencyStopped || this.state === 'RUNNING' || this.state === 'PAUSED' || this.state === 'HUMAN_TAKEOVER' || this.state === 'STARTING') return this.snapshot();
    if (this.operation) { await this.operation; return this.snapshot(); }
    if (this.state === 'STOPPED') { this.sessionId = null; this.activeProductId = null; this.lastActionAt = null; this.lastSpeechAt = null; this.lastProductActionAt = null; }
    this.operation = (async () => { this.transition('STARTING'); this.sessionId ??= this.makeSessionId(); this.startedAt = this.now();this.endedAt=null; this.metrics = freshMetrics(); this.errorCount = 0;this.consecutiveFailures=0; this.record('SESSION_STARTING', 'Local runtime starting');
      try { this.ports.orchestrator?.start(this.sessionId); this.transition('RUNNING'); this.activeActivity = 'WAITING'; this.emit('SESSION_STARTED', { sessionId: this.sessionId }); this.record('SESSION_STARTED', 'Live runtime is running'); }
      catch (error) { this.errorCount++; this.transition('ERROR'); this.emit('RUNTIME_ERROR', { subsystem: 'orchestrator', code: 'START_FAILED', recoverable: true }); this.record('RUNTIME_ERROR', message(error)); }
    })(); try { await this.operation; } finally { this.operation = null; } return this.snapshot();
  }
  async pauseSession(): Promise<RuntimeSnapshot> { if (this.state === 'PAUSED' || this.state !== 'RUNNING') return this.snapshot(); this.ports.orchestrator?.pause(); this.ports.voice?.pause?.(); this.transition('PAUSED'); this.activeActivity = 'PAUSED'; this.emit('SESSION_PAUSED', {}); this.record('SESSION_PAUSED', 'Autonomous activity paused'); return this.snapshot(); }
  async resumeSession(): Promise<RuntimeSnapshot> { if (this.emergencyStopped || this.state === 'RUNNING' || this.state !== 'PAUSED') return this.snapshot(); this.ports.voice?.resume?.(); this.ports.orchestrator?.resume(); this.transition('RUNNING'); this.activeActivity = 'WAITING'; this.emit('SESSION_RESUMED', {}); this.record('SESSION_RESUMED', 'Runtime resumed'); return this.snapshot(); }
  async requestHumanTakeover(): Promise<RuntimeSnapshot> { if (this.emergencyStopped || this.state === 'HUMAN_TAKEOVER' || !['RUNNING', 'PAUSED'].includes(this.state)) return this.snapshot(); this.takeoverReturnState=this.state as 'RUNNING'|'PAUSED';this.ports.orchestrator?.pause();this.metrics.droppedActions+=this.queueDepth;this.queueDepth=0;if(this.ports.voice?.setHumanTakeover)this.ports.voice.setHumanTakeover(true);else this.ports.voice?.stop(true); this.ports.avatar?.humanTakeover(true); this.humanTakeover = true; this.metrics.humanTakeoverCount++; this.transition('HUMAN_TAKEOVER'); this.activeActivity = 'HUMAN_TAKEOVER'; this.emit('HUMAN_TAKEOVER_STARTED', {}); this.record('HUMAN_TAKEOVER_STARTED', 'Operator has control; queued autonomous actions were cleared'); return this.snapshot(); }
  async releaseHumanTakeover(): Promise<RuntimeSnapshot> { if (!this.humanTakeover || this.emergencyStopped) return this.snapshot(); const resumeState=this.takeoverReturnState??'RUNNING';this.ports.avatar?.humanTakeover(false); this.ports.voice?.setHumanTakeover?.(false); if(resumeState==='RUNNING')this.ports.orchestrator?.resume(); this.humanTakeover = false;this.takeoverReturnState=null; this.transition(resumeState); this.activeActivity = resumeState==='RUNNING'?'COOLDOWN':'PAUSED'; this.emit('HUMAN_TAKEOVER_ENDED', {}); this.record('HUMAN_TAKEOVER_ENDED', resumeState==='RUNNING'?'Autonomy resumed with existing cooldown':'Session remains paused'); return this.snapshot(); }
  async stopSession(): Promise<RuntimeSnapshot> { if (this.state === 'STOPPED' || this.state === 'IDLE' || this.state === 'STOPPING') return this.snapshot(); if (this.state !== 'ERROR') this.transition('STOPPING'); this.emit('SESSION_STOPPING', {}); this.record('SESSION_STOPPING', 'Stopping runtime activity');
    this.ports.orchestrator?.stop('live'); this.ports.voice?.setHumanTakeover?.(false);this.ports.voice?.stop(true); this.ports.music?.stop(); this.ports.avatar?.humanTakeover(false); this.humanTakeover = false;this.takeoverReturnState=null; this.transition('STOPPED');this.endedAt=this.now(); this.activeActivity = null; this.emit('SESSION_STOPPED', {}); this.record('SESSION_STOPPED', 'Runtime stopped'); return this.snapshot(); }
  async emergencyStop(): Promise<RuntimeSnapshot> { if (this.emergencyStopped) return this.snapshot(); this.emergencyStopped = true; this.metrics.emergencyStopCount++; this.queueDepth = 0; this.ports.orchestrator?.stop('live'); this.ports.voice?.emergencyStop?.(); this.ports.voice?.stop(true); this.ports.music?.stop(); this.ports.avatar?.humanTakeover(true); await this.ports.avatar?.emergencyStop().catch(() => undefined); if (this.state !== 'STOPPED' && this.state !== 'STOPPING') { if (this.state === 'IDLE') this.transition('STARTING'); if (this.state !== 'ERROR') this.transition('ERROR'); }
    this.humanTakeover = false;this.takeoverReturnState=null; this.activeActivity = 'EMERGENCY_STOPPED'; this.emit('EMERGENCY_STOP', { reason: 'operator' }); this.record('EMERGENCY_STOP', 'All runtime outputs stopped; explicit reset required'); return this.snapshot(); }
  async resetAfterEmergency(): Promise<RuntimeSnapshot> { if (!this.emergencyStopped) return this.snapshot(); this.ports.voice?.resetEmergency?.(); await this.ports.avatar?.resume?.().catch(() => undefined); this.emergencyStopped = false; if (this.state === 'ERROR') this.transition('STOPPED'); this.sessionId = null; this.startedAt = null; this.activeActivity = null; this.queueDepth = 0; this.record('EMERGENCY_RESET', 'Runtime remains stopped until explicitly started'); return this.snapshot(); }
  async shutdown(): Promise<RuntimeSnapshot> { if (this.state !== 'STOPPED' && this.state !== 'IDLE') await this.stopSession(); await this.ports.avatar?.disconnect?.().catch(() => undefined); return this.snapshot(); }
  async routeAction(action: RuntimeAction): Promise<boolean> { const control = ['PAUSE','RESUME','TAKEOVER','STOP','WAIT'].includes(action.type); if (this.emergencyStopped || this.humanTakeover && !['STOP', 'WAIT'].includes(action.type) || this.state !== 'RUNNING' && !control) { this.metrics.ignoredEvents++; if(action.type==='SPEAK'&&this.hostResponsePending){this.hostResponsePending=false;this.emit('HOST_RESPONSE_FAILED',{code:'SPEECH_SUPPRESSED'})}this.emit('ACTION_ROUTED', { action: action.type, accepted: false }); return false; }
    let accepted = true;
    try { switch (action.type) {
      case 'SPEAK': if (action.language && action.language !== 'id-ID') { accepted = false; break; } if (!action.text.trim() || action.text.length > 4000 || /[\u0000-\u0008\u000B\u000C\u000E-\u001F\u007F]/u.test(action.text)) { accepted = false; break; } { const result = await this.ports.voice?.speak({ text: action.text.trim(), language: 'id-ID', priority: 'HIGH' }); accepted = result?.accepted ?? false; if (accepted) { this.metrics.queuedActions++; this.lastSpeechAt = this.now(); } else this.metrics.droppedActions++; } break;
      case 'PLAY_MUSIC': accepted = this.ports.playMusic?.(action.trackId) ?? false; break;
      case 'STOP_MUSIC': this.ports.music?.stop(); break;
      case 'DUCK_MUSIC': this.ports.duckMusic?.(); break;
      case 'RESTORE_MUSIC': this.ports.restoreMusic?.(); break;
      case 'AVATAR_COMMAND': { const emotions = ['neutral','happy','friendly','excited','thinking','surprised','confused','sad','serious']; const expressions = ['neutral','smile','big_smile','surprised','thinking','serious']; const gestures = ['none','wave','nod','shake_head','point_product','point_left','point_right','open_hands','thinking','celebrate']; if (!action.emotion && !action.expression && !action.gesture || action.emotion && !emotions.includes(action.emotion) || action.expression && !expressions.includes(action.expression) || action.gesture && !gestures.includes(action.gesture)) { accepted = false; break; } accepted = await (this.ports.avatar?.command?.({ ...(action.emotion ? { emotion: action.emotion } : {}), ...(action.expression ? { expression: action.expression } : {}), ...(action.gesture ? { gesture: action.gesture } : {}) }) ?? false); if (!accepted) this.metrics.droppedActions++; break; }
      case 'SELECT_PRODUCT': accepted = this.ports.product?.hasProduct?.(action.productId) !== false && (this.ports.selectProduct?.(action.productId) ?? false); if (accepted) { const previous = this.activeProductId; this.activeProductId = action.productId; this.lastProductActionAt = this.now(); if (previous !== action.productId) this.emit('PRODUCT_CHANGED', { productId: action.productId, previousProductId: previous }); this.emit('PRODUCT_SELECTED', { productId: action.productId }); } break;
      case 'WAIT': break; case 'PAUSE': await this.pauseSession(); break; case 'RESUME': await this.resumeSession(); break; case 'TAKEOVER': await this.requestHumanTakeover(); break; case 'STOP': await this.stopSession(); break;
    } } catch { accepted = false; this.errorCount++; }
    if(!accepted&&action.type==='SPEAK'&&this.hostResponsePending){this.hostResponsePending=false;this.emit('HOST_RESPONSE_FAILED',{code:'SPEECH_REJECTED'})}this.metrics.processedEvents++; this.lastActionAt = this.now(); this.emit('ACTION_ROUTED', { action: action.type, accepted }); this.record('ACTION_ROUTED', `${action.type} ${accepted ? 'accepted' : 'rejected'}`); return accepted;
  }
  observeAudience(kind: string, accepted: boolean): void { this.metrics.audienceEvents++; if(accepted)this.metrics.processedEvents++;else this.metrics.ignoredEvents++;this.emit('AUDIENCE_EVENT', { kind: ['COMMENT', 'NEW_VIEWER', 'FOLLOW', 'LIKE', 'GIFT', 'SYSTEM', 'UNKNOWN'].includes(kind) ? kind : 'UNKNOWN', accepted }); this.record('AUDIENCE_EVENT', `${kind} ${accepted ? 'accepted' : 'ignored'}`); }
  observeTikTokConnectionStatus(state:'TIKTOK_DISCONNECTED'|'TIKTOK_CONNECTED'|'TIKTOK_PERMISSION_LIMITED'|'TIKTOK_REAUTH_REQUIRED'|'TIKTOK_ERROR'):void{this.emit('TIKTOK_CONNECTION_STATUS',{state})}
  observeSpeech(success: boolean): void { if (success) { this.consecutiveFailures=0;this.metrics.speechCount++; this.lastSpeechAt = this.now(); this.emit('SPEECH_COMPLETED', {}); if(this.hostResponsePending){this.hostResponsePending=false;this.emit('HOST_RESPONSE_COMPLETED',{})} } else { this.metrics.speechFailures++; this.emit('SPEECH_FAILED',{code:'VOICE_FAILED'}); if(this.hostResponsePending){this.hostResponsePending=false;this.emit('HOST_RESPONSE_FAILED',{code:'VOICE_FAILED'})} this.recordError('voice', 'VOICE_FAILED', true); } }
  observeSpeechStarted(): void { this.emit('SPEECH_STARTED', {}); if(this.hostResponsePending)this.emit('HOST_RESPONSE_STARTED',{}); this.record('SPEECH_STARTED', 'Voice engine began playback'); }
  observeMusicStarted(): void { this.metrics.musicPlays++; this.emit('MUSIC_STARTED', {}); this.record('MUSIC_STARTED', 'Music engine began playback'); }
  observeMusic(success: boolean): void { if (success) { this.consecutiveFailures=0;this.emit('MUSIC_COMPLETED', {}); } else { this.metrics.musicFailures++; this.emit('MUSIC_FAILED',{code:'MUSIC_FAILED'}); this.recordError('music', 'MUSIC_FAILED', true); } }
  observeHostResponse(action: string): void { this.hostResponsePending=true; this.emit('HOST_RESPONSE_READY', { action: action.slice(0, 60) }); this.record('HOST_RESPONSE_READY', action.slice(0, 60)); }
  observeProductSelected(productId: string | null): void { const previous=this.activeProductId;this.activeProductId=productId;if(previous!==productId)this.emit('PRODUCT_CHANGED',{productId,previousProductId:previous});this.emit('PRODUCT_SELECTED', { productId }); this.record('PRODUCT_SELECTED', productId ?? 'unknown'); }
  observeAvatar(success: boolean): void { if (success) { this.consecutiveFailures=0;this.metrics.avatarCommands++; this.emit('AVATAR_COMMAND_READY', {}); } else { this.metrics.avatarFailures++; this.emit('AVATAR_COMMAND_FAILED',{code:'AVATAR_FAILED'});this.recordError('avatar', 'AVATAR_FAILED', true); } }
  setQueueDepth(size: number): void { this.queueDepth = Number.isFinite(size) ? Math.max(0, Math.floor(size)) : 0; }
  recordError(subsystem: string, code: string, recoverable: boolean): void { const safeSubsystem=safeIdentifier(subsystem,40),safeCode=safeIdentifier(code,60);this.errorCount++;this.consecutiveFailures++; this.emit('RUNTIME_ERROR', { subsystem:safeSubsystem, code:safeCode, recoverable }); this.record('RUNTIME_ERROR', `${safeSubsystem}: ${safeCode}`); }
  health(): RuntimeHealth { const voiceStatus = this.ports.voice?.getStatus?.(); const musicStatus = this.ports.music?.getStatus?.(); const avatarStatus = this.ports.avatar?.snapshot?.(); const voice: SubsystemHealth = !voiceStatus || !voiceStatus.state || voiceStatus.state === 'UNKNOWN' ? 'unknown' : voiceStatus.lastError || voiceStatus.state === 'FAILED' ? 'error' : ['PLAYING', 'SYNTHESIZING', 'PREPARING'].includes(voiceStatus.state) ? 'busy' : 'ready'; const music: SubsystemHealth = !musicStatus || !musicStatus.playbackState && !musicStatus.state && musicStatus.playing === undefined ? 'unknown' : musicStatus.error || musicStatus.playbackState === 'FAILED' ? 'error' : musicStatus.playing || musicStatus.playbackState === 'PLAYING' || musicStatus.state === 'PLAYING' ? 'playing' : musicStatus.playbackState && !['IDLE','STOPPED','PAUSED','FINISHED','PLAYING'].includes(musicStatus.playbackState) ? 'unknown' : 'ready'; const avatar: SubsystemHealth = !avatarStatus || !avatarStatus.state ? 'unknown' : avatarStatus.lastError || avatarStatus.state === 'ERROR' ? 'error' : avatarStatus.state === 'SPEAKING' || avatarStatus.state === 'GESTURING' ? 'busy' : avatarStatus.connected ? 'ready' : 'unknown'; const audience = this.ports.audience?.getStatus?.() ?? 'unknown'; const product = this.ports.product?.getStatus?.() ?? 'unknown'; const degraded = [voice, music, avatar].includes('error') || audience === 'error' || product === 'error' || [voice, music, avatar, audience, product].includes('unknown') || this.eventLoopLagMs>250 || this.queueDepth>40 || this.consecutiveFailures>=3; return { status: this.state === 'ERROR' ? 'failed' : this.recovering ? 'recovering' : this.errorCount || degraded ? 'degraded' : 'healthy', sessionState: this.state, voice, music, avatar, audience, product, queueDepth: this.queueDepth + (voiceStatus?.queueLength ?? 0) + (avatarStatus?.queueLength ?? 0), eventLoopLagMs:this.eventLoopLagMs,errorCount: this.errorCount, lastActivityAt: this.lastActivityAt, timestamp: this.now() }; }
  context(): LiveRuntimeContext { const health = this.health(); return { sessionId: this.sessionId, startedAt: this.startedAt, state: this.state, activeProductId: this.activeProductId, activeActivity: this.activeActivity, speechActive: health.voice === 'busy', musicActive: health.music === 'playing', avatarActive: health.avatar === 'busy', humanTakeover: this.humanTakeover, emergencyStopped: this.emergencyStopped, lastActionAt: this.lastActionAt, lastSpeechAt: this.lastSpeechAt, lastProductActionAt: this.lastProductActionAt, errorCount: this.errorCount }; }
  observeEventLoopLag(lagMs: number): void { this.eventLoopLagMs=Number.isFinite(lagMs)?Math.max(0,lagMs):0; }
  inspectWatchdog(): WatchdogFinding[] { return this.watchdog.inspect(this.snapshot(), this.now(), { eventLoopLagMs:this.eventLoopLagMs, consecutiveFailures:this.consecutiveFailures }); }
  async recoverSubsystem(subsystem: string, recover: () => Promise<boolean> | boolean): Promise<boolean> { const safeSubsystem=safeIdentifier(subsystem,40);this.recovering=true;this.emit('RECOVERY_STARTED', { subsystem: safeSubsystem });let result;try{result=await new RuntimeErrorRecovery(1).run(safeSubsystem, recover)}finally{this.recovering=false}if (result.recovered) { this.metrics.recoveredErrors++;this.consecutiveFailures=0; } this.emit('RECOVERY_COMPLETED', { subsystem: safeSubsystem, recovered:result.recovered }); this.record(result.recovered ? 'RECOVERY_COMPLETED' : 'RECOVERY_FAILED', `${result.subsystem} · ${result.code}`); return result.recovered; }
  snapshot(): RuntimeSnapshot { const now = this.now(); const metrics = { ...this.metrics, sessionDurationMs: this.startedAt === null ? 0 : Math.max(0, (this.state==='STOPPED'?(this.endedAt??now):now) - this.startedAt) }; return { sessionId: this.sessionId, state: this.state, startedAt: this.startedAt, activeProductId: this.activeProductId ?? this.ports.orchestrator?.getState()?.currentProductId ?? null, activeActivity: this.activeActivity ?? this.ports.orchestrator?.getState()?.currentIntent ?? null, humanTakeover: this.humanTakeover, emergencyStopped: this.emergencyStopped, errorCount: this.errorCount, queueDepth: this.queueDepth, health: this.health(), metrics, activity: this.activity.map(item => ({ ...item })) }; }
  private makeSessionId(): string { return (this.sessionId = this.sessionId ?? this.options.sessionId?.() ?? `live-${this.now()}-${++this.idSequence}`); }
}

export { transitions as LIVE_RUNTIME_TRANSITIONS };
